### ISSUE TITLE
No Support for Bats code coverage for Sonarqube

### ISSUE THREAD

**Issue by aditya-malviya** [bats-core/bats-core#1008]
Hi Team,

We've invested a lot on bats test for our shell scripts. Now we are integrating all our code coverage with SonarQube, apparently bats-core is not friendly with Sonarqube, and we are forced to move out of Bats. 
Can you let us know if there's a way or could you please check for the feature in plan? 

Thanks,

**Comment by aditya-malviya** [comment]
Also, let me know if it's not in plan or in plan for the next few months.

**Comment by martin-schulze-vireso** [comment]
Unless some volunteer steps up, it is highly unlikely. 

I am not sure what would be necessary for sonarcube integration. If kcov reports are enough, there is at least an issue for that.

**Comment by aditya-malviya** [comment]
Got it. Thanks.
