### ISSUE TITLE
grep: RE error 41: No remembered search string

### ISSUE THREAD

**Issue by jas-** [bats-core/bats-core#1016]
**Describe the bug**
Bats version `1.11.0` on Solaris 11 using bash version `5.1.12` and grep version `3.1-11` throws the error in the title when running tests like the following `./bats/bin/bats foo.bats`

**Test case**
accounts.bats
```
setup() {
  DIR="$( cd "$( dirname "$BATS_TEST_FILENAME" )" >/dev/null 2>&1 && pwd )"
  PATH="$DIR/../src:$PATH"

  load plugins/bats-assert/load
  load plugins/bats-file/load
  load plugins/bats-support/load

  files=($(find $DIR/../src/configs $DIR/../src/libs -type f -name "*.sh"))
  for file in ${files[@]}; do
    load ${file}
  done
}


@test "accounts.get_users" {
  local -a users
  users=($(accounts.get_users))
  [ ${#users[@]} -gt 0 ]
}
```

**Expected behavior**
Below is the output for an ansible test harness run for four operating systems. Solaris is the only one that fails.

```
$ ansible all -b --become-user root -m shell -a 'cd /projects; ./tests/bats/bin/bats -r tests/accounts.bats'
rh_9 | CHANGED | rc=0 >>
1..1
ok 1 accounts.get_users

rh_8 | CHANGED | rc=0 >>
1..1
ok 1 accounts.get_users

rh_7 | CHANGED | rc=0 >>
1..1
ok 1 accounts.get_users

sol11 | FAILED | rc=1 >>
1..0
ok 1 accounts.get_users
# bats warning: Executed 1 instead of expected 0 tests
grep: RE error 41: No remembered search string.
non-zero return code
```

**Environment (please complete the following information):**
 - Bats version: 1.11.0
 - operating system (including version): Solaris 11
 - `bash --version`: 5.1.12
 - Install method: zip archive

**Additional context**
It looks like use of `ggrep` might be helpful as it is available by default in Solaris 11.

**Comment by martin-schulze-vireso** [comment]
Is this reproducible in one of the [supported systems](https://bats-core.readthedocs.io/en/stable/support-matrix.html#supported-operating-systems)?

**Comment by jas-** [comment]
Based on the other test results, no, maybe I am missing a road map or coverage map of the project?

I did go through the supported systems page you provided. Just hoping that the test loader functions could support other OS's.

Thanks for a great project!

**Comment by jas-** [comment]
@martin-schulze-vireso I don't have access to ALL of the supported systems. However I do know that older versions of `grep` (pretty sure it is anything < 3.2) the BRE pattern error is thrown on empty or whitespace patterns.

The following replacement for [line 32 of libexec/bats-exec-suite](https://github.com/bats-core/bats-core/blob/89a7fae3b651d5c2f42a3874ec32e821014814eb/libexec/bats-core/bats-exec-suite#L132) works and might be a quick fix for other operating system such as Solaris (even for older version 10 implementations).

```sh
test_count=$(awk '$0 !~ /^$/' "$TESTS_LIST_FILE" 2>/dev/null | wc -l || true) # don't fail here when there are no tests
```

Thanks for keeping up a great tool!

**Comment by jas-** [comment]
I can tell you that fix works on the following systems solaris 11, red hat 7, 8 & 9 as well as ubuntu 18 and 20.

It looks like the project uses the github actions for the test suite?

**Comment by martin-schulze-vireso** [comment]
Yes, the CI system is GitHub Actions.

Under our current assumptions the test list file has no empty lines. If there are no tests, it will be empty. I think a simple `wc -l` might be sufficient. Since this command is already used elsewhere, I don't see this being a huge issue. However, I still wonder why I used `grep` in the first place. Maybe it was the trailing newline controversy (not relevant here, because all lines are `\n` terminated) or the performance (`grep` is rumored to be much faster than `wc`.

Does `grep -c ^` work for your system?

**Comment by jas-** [comment]
I will test today but I believe the correct BRE pattern would be `^$`
