### ISSUE TITLE
Backgrounded process hangs tests with run and close_non_std_fds

### ISSUE THREAD

**Issue by dcarley** [bats-core/bats-core#1021]
**Describe the bug**
Background processes started from `run` block the test suite even with `close_non_std_fds`.

With a large test suite, that may occasionally background processes from scripts further down the stack, this makes it very hard to figure out which is the offending test and process. Especially when using external timeouts to guard against it happening, due to #1020.

Related but not the same as:
- #533
- #155

**To Reproduce**

Given this test and inlining the functions from [issue-205.bats](https://github.com/bats-core/bats-core/blob/master/test/fixtures/bats/issue-205.bats):
```sh
@test "should not block on background processes with run" {
	close_non_std_fds
	run bash -c 'sleep infinity & echo foo'
	assert_success
}
```

The test hangs indefinitely:
```
% nix run nixpkgs#bats -- demo.bats
demo.bats
   should not block on background processes with run
```

The process doesn't have FD3 or FD4:
```
% lsof -p 32169                                         
COMMAND     PID    USER   FD   TYPE             DEVICE SIZE/OFF     NODE NAME
coreutils 32169 dcarley  cwd    DIR               1,15       96 60565278 /Users/dcarley/projects/flox/bats
coreutils 32169 dcarley  txt    REG               1,17  1496256  9441761 /nix/store/4q1ilwxg18vyz4p1mp7k9wv0wrycn325-coreutils-9.5/bin/coreutils
coreutils 32169 dcarley  txt    REG               1,17   500832  9440809 /nix/store/7y2i75x5rriibsb0hkp2miprbz6b2lz6-gmp-with-cxx-6.3.0/lib/libgmp.10.dylib
coreutils 32169 dcarley    0r   CHR                3,2      0t0      335 /dev/null
coreutils 32169 dcarley    1   PIPE 0x66f747e1d92ef138    16384          ->0xa4bb7c86bd6ee11d
coreutils 32169 dcarley    2   PIPE 0x66f747e1d92ef138    16384          ->0xa4bb7c86bd6ee11d
```

Forcible closing STDIN and STDOUT:
```
(2) ~
% lldb -p 32169
(lldb) process attach --pid 32169
…
(lldb) call (int)close(1)
(int) $0 = 0
(lldb) call (int)close(2)
(int) $1 = 0
```

Allows Bats to continue (though the background process remains orphaned):
```
demo.bats
   should not block on background processes with run                                                                                                                                                             
   bats warning: Executed 0 instead of expected 1 tests

1 test, 0 failures, 1 not run
```

**Expected behaviour**
The test should pass.

Bonus if it can warn that a process was leaked.

**Environment (please complete the following information):**
 - Bats version: 1.11.0
 - operating system (including version): MacOS
 - `bash --version`: GNU bash, version 5.2.15(1)-release (aarch64-apple-darwin22.6.0)
 - Install method: Nix

**Additional context**
N/A

**Comment by martin-schulze-vireso** [comment]
Thanks for your report.

It is a bad idea to use `close_non_std_fds` in this location for two reasons:

1. this will interfere with Bats internal communication via FD3
2. the intermediate code in `run` can create new fds

For this reason, `run` itself should do this (which is #533). 

To break `run` free from the background process you have to close all connecting FDs and `disown` the background process:

```
run_background() { # use function instead of `bash -c` to avoid exporting close_non_std_fds
	(
		close_non_std_fds # close FDs >2
		exec 2>&- 1>&- # close remaining FDs, to prevent holding the pipe open
		sleep infinity
	) & 
	disown
	echo foo
}

@test "should not block on background processes with run" {
	run run_background
	assert_success
}
```

**Comment by martin-schulze-vireso** [comment]
Since this would be solved by `run` doing the `close_non_std_fds` part and the rest is documented now, I am closing this.
