### ISSUE TITLE
Request for new Docker image release to include recent changes

### ISSUE THREAD

**Issue by ibakshay** [bats-core/bats-core#1024]
Hi maintainers,

I noticed that the latest Docker image release for bats ([bats/bats on Docker Hub](https://hub.docker.com/r/bats/bats/tags)) is from version 1.11.0, which was released approximately six months ago. Since then, there have been several important commits merged into the main branch, including:
https://github.com/bats-core/bats-core/commit/ce80064fbee5118520326d2d3ae6ef09d294dbc6
Would it be possible to create a new release and update the Docker image to include these recent changes? This would allow users to benefit from the latest improvements through the official Docker image without having to build custom images.
## Current Status:
Latest Docker image tag: 1.11.0
Docker Hub repository: https://hub.docker.com/r/bats/bats/tags
Latest commit we'd like to include: ce80064fbee5118520326d2d3ae6ef09d294dbc6

## Request:

Create a new release incorporating recent changes
Build and publish an updated Docker image to Docker Hub

Thank you for maintaining this valuable tool and considering this request. Let me know if you need any additional information.

**Comment by martin-schulze-vireso** [comment]
Originally I was working on a quarterly release schedule for exactly this reason but lack the time right now (see #1023).

I hope to release a new version this year.

**Comment by martin-schulze-vireso** [comment]
Here you go: https://github.com/bats-core/bats-core/releases/tag/v1.11.1

**Comment by ibakshay** [comment]
@martin-schulze-vireso, Thanks so much. I really appreciate your work!
