### ISSUE TITLE
Create bats-core packages to install easilly on linux

### ISSUE THREAD

**Issue by kenden** [bats-core/bats-core#103]
As the moment it's only possible to install bats from bats-core from source on linux.

We should create packages to install easily on Linux.
It could be:
- `apt install bats-core` for Debian/Ubuntu/Linux Mint
- `yum install bats-core` for Fedora/RedHat/CentOS
- a package on (Flathub](www.flathub.org)
- a snap on https://snapcraft.io/
...

Flathub is probably the easiest to support most distributions in one package.
Starting point: https://github.com/flathub/flathub/wiki/App-Submission

**Comment by kenden** [comment]
Related: the package for mac:
https://github.com/bats-core/bats-core/issues/11

**Comment by mbland** [comment]
Sounds like a good idea to me. I hadn't heard of Flathub before; it seems it's primarily geared towards desktop apps, though. Have you any examples of dev tools handy? (Plus, we don't have an app icon yet.)

**Comment by kenden** [comment]
I don't sorry, it was just an idea, I don't know if is a good fit or not for utilities.

**Comment by bvberkum** [comment]
fwiw. Basher is supported but appearantly not listed on wiki/docs (ie. #90 )

**Comment by jasonkarns** [comment]
Since node is included OOTB on many linux distros, I would also mention that bats is available on npm: https://www.npmjs.com/package/bats

and I suspect the bats-core formula probably works via linuxbrew

**Comment by virgilwashere** [comment]
> btw, may be worth removing https://github.com/bats-core/bats-core/wiki/Install-Bats-Using-a-Package#ubuntu for now from the wiki as one could assume they get `bats-core` if they followed the guide, but don't at the time of writing this.

I had actually editted this a yesterday, before seeing this.  Added the ⚠️ icon and suggestion to use `npm i -g bats`.

As for #193 and the original issue here, I've been researching what's involved in Debian packaging and git recently.  Will try to create a packaging fork and see hard it is to maintain... then continue down the road of getting it accepted upstream upstream.

**Comment by abegosum** [comment]
Noticing that the Fedora package is listed in the wiki- but, none of the RHEL based distributions are in the supported operating systems list.  Is this an oversight, or are RHEL / CentOS / Fedora officially not supported?

**Comment by martin-schulze-vireso** [comment]
Keeping up with men different distributions and package managers seems to be wasteful. We should only provide a standardized means (e.g. install.sh) for distro package managers to package Bats easily.

**Comment by brokenpip3** [comment]
@kenden bats itself is present in all the major distro: https://pkgs.org/search/?q=bats, If its' no update I will suggest you to contact the maintainer for that package.
