### ISSUE TITLE
Run Specific Test

### ISSUE THREAD

**Issue by jkstrauss** [bats-core/bats-core#106]
When doing TDD it would be advantageous to be able to run specific test(s). Perhaps this could be an option at the CLI.

I currently play games like removing all the other tests to be able to get a single to run in a reasonable amount of time.

**Comment by mbland** [comment]
Absolutely, we can do this. I've implemented a mechanism to do this in my own project that I think'd be easily portable into the framework (`test_filter` from https://github.com/mbland/go-script-bash/blob/master/lib/bats/helpers).

**Comment by jkstrauss** [comment]
I wouldn't mind doing this myself. Do you suggest using an environment variable, or perhaps it makes more sense to have a command line argument for this. Also, it might be useful to allow the user to list the test names without running them, so that he/she can easily select the test to run.

**Comment by jt-nti** [comment]
A command line argument would be nice to have for this. Looks like there was a pull request to do this kind of thing in the original repository (also an environment variable)...

https://github.com/sstephenson/bats/pull/117

**Comment by jasonkarns** [comment]
Started collecting data on what other test runners use for their filtering features...
My _hope_ was that there would at least be some convention, but that doesn't seem to be the case thus far:

rspec: 

        -P, --pattern
minitest:

       -n, --name
       -e, --exclude
mocha:

        -g, --grep <pattern>    only run tests matching <pattern>
        -f, --fgrep <string>    only run tests containing <string>
        -i, --invert            inverts --grep and --fgrep matches
jasmine:

        --filter

However, I would still like to suggest that we not use `-f` as the short flag as that seems overwhelmingly conventional as a `--force` shorthand. (Which we don't have yet, but...)

I'd rather see `-e` as per `grep` (and to a degree, `sed`). Would also be fine with `-P` ala `tree`.
