### ISSUE TITLE
Update or create bats formula on homebrew-core

### ISSUE THREAD

**Issue by btamayo** [bats-core/bats-core#11]
Currently, `brew info bats` would print this:

```shell
$ brew info bats
bats: stable 0.4.0, HEAD
TAP-compliant test framework for Bash scripts
https://github.com/sstephenson/bats
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/bats.rb
```

This needs to be updated in Homebrew's core tap, or a new one should be created.

**Comment by btamayo** [comment]
[Opened a PR](https://github.com/Homebrew/homebrew-core/pull/20073) for 0.4.0 and hoping for some feedback.

**Comment by btamayo** [comment]
https://github.com/Homebrew/homebrew-core/pull/20073#issuecomment-341291907

🎉 Good to know we'll be able to secure the alias!

**Comment by btamayo** [comment]
Closing for hygiene, will reopen again when needed.

**Comment by AnneTheAgile** [comment]
To use bats-core instead of bats with a homebrew install, even before bats-core patch is merged,  follow tips here; https://superuser.com/a/730111/23354

**Comment by mbland** [comment]
Time to reopen: https://github.com/bats-core/bats-core/releases/tag/v1.0.0

**Comment by kenden** [comment]
@btamayo could you reopen ? Wee need a way to install via brew

**Comment by kenden** [comment]
I made a PR for homebrew https://github.com/Homebrew/homebrew-core/pull/28977

**Comment by kenden** [comment]
this can be closed:
```
$ brew install bats-core
==> Downloading https://github.com/bats-core/bats-core/archive/v1.0.1.tar.gz
Already downloaded: /Users/redacted/Library/Caches/Homebrew/bats-core-1.0.1.tar.gz
==> ./install.sh /usr/local/Cellar/bats-core/1.0.1
🍺  /usr/local/Cellar/bats-core/1.0.1: 12 files, 51.4KB, built in 1 second
$ bats --version
Bats 1.0.1
```

**Comment by mbland** [comment]
Thanks, @kenden!
