### ISSUE TITLE
bats can't find BATS_ROOT on CentOS 7 when /bin -> /usr/bin

### ISSUE THREAD

**Issue by rgm3** [bats-core/bats-core#113]
I suspect that bats_absolute_path() could be reimplemented as simply:
```bash
local path="$1"
local result="$2"
local canonical
canonical=$(readlink -e "$1")
printf -v "${result}" -- '%s' "${canonical%/*}"
```
Currently, when /bin is symlinked to /usr/bin as on CentOS 7 systems then bats can't find bats-core.

**Comment by mbland** [comment]
If I'm understanding correctly, then `readlink -e` will break on macOS without `greadlink` installed. But I see the problem you're describing—we only anticipated `bats` itself being symlinked, not `/bin`—and we need to fix it.

**Comment by mbland** [comment]
@bats-core/bats-core barring any suggestions/objections, I'll look to merge this by tomorrow.
