### ISSUE TITLE
Possible bug in run() function

### ISSUE THREAD

**Issue by markmurphy242** [bats-core/bats-core#121]
Within a test, issued a command very similar to the following:

run mkdir -p mark

The output basically resulted in the following error in the output variable:

bats-exec-test: line 52: mkdir -p mark: No such file or directory

Line 52:
output="$("$@" 2>&1)"

After running a few test cases with the above line from a command line, I've found:

On centos 6 bash version 4.1.2(2)-release (x86_64-redhat-linux-gnu):
echo "$("mkdir -p mark" 2>&1)" $?

result:
-bash: mkdir -p mark: command not found 127

Same result on Mac OS 10.11.6 GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15):
echo "$("mkdir -p mark" 2>&1)" $?

Result:
-bash: mkdir -p mark: command not found 127

I'm unsure why line 52 is:
output="$("$@" 2>&1)"

For this use case, the following resolved the issue:
output="$($@ 2>&1)"

From the command line:
echo "$(mkdir -p mark 2>&1)" $?

Result:
 0

Not sure if this is just an edge case for "make -p dir" or might raise issues with different args to the run function?

**Comment by markmurphy242** [comment]
Here's the test case:

`#!/usr/bin/env bats

RUN='run'

@test "mark" {
  $RUN "mkdir -p mark"
  [ "$status" -eq 0 ]
}
`

**Comment by cdevinesr** [comment]
Try it without quoting `mkdir -p mark` and see if you get better results.  `run` is not designed to have what it's running quoted fully like that.

**Comment by markmurphy242** [comment]
Yes, I agree.  I realized it appeared the source at line 52 was not going to expand out the quoted string.

Thank you for the response.

**Comment by mbland** [comment]
For future reference, in case anyone else is surprised by this behavior: `run` uses the double-quoted `$@` to expand its argument list into an executable command line. Quoting the entire command means `run` only sees one argument, defeating the mechanism.

Check out the description of `$@`, `$*`, and the semantics of double-quoting them in the `bash` man page.
