### ISSUE TITLE
doc clarification: do I need to use --tap to see diagnostic data (fd 3) on test failures?

### ISSUE THREAD

**Issue by joshrabinowitz** [bats-core/bats-core#125]
It's not clear to me from  README.md if I need to use --tap to see the diagnostic data I output in my script using `echo "# message here".

I know that data is only passed on if the test fails, and the readme says "The produced TAP stream is by default piped to a pretty formatter for human consumption, but if Bats is called with the -t flag, then the TAP stream is directly printed to the console."

Will the will the pretty formatter used if -t/--tap isn't used strip of diagnostic messages sent to FD 3 on errors?

**Comment by mbland** [comment]
No, you don't need to specify `--tap` it to see the messages printed to the console. Yes, it will pipe through the pretty formatter if `--tap` isn't specified.

If you specify `--tap`, it will get emitted to the output stream immediately. If you don't, or specify `--pretty`, the pretty-formatter will buffer and format the output, but will eventually emit it.

Best way to get a feel for it is to emit some output to FD 2 or FD 3, force your test to fail, and see what happens with and without `--tap`.

**Comment by mbland** [comment]
Closing this, but reopen if this doesn't answer your question.
