### ISSUE TITLE
README Refresh

### ISSUE THREAD

**Issue by btamayo** [bats-core/bats-core#13]
Update information that needs to be updated on current README, including but not limited to:

 - [x] Installing and usage - partially covered in [README](https://github.com/bats-core/bats-core/blob/master/README.md#installing-bats-from-source) (TODO: sufficient?)
 - [x] Platform support - fixed in https://github.com/bats-core/bats-core/pull/67
 - [x] Adding versioning info - fixed in https://github.com/bats-core/bats-core/pull/71 (unmerged)
 - [x] Changelog update - fixed in https://github.com/bats-core/bats-core/pull/66 (unmerged)
 - [x]  Bash minimum version - fixed in https://github.com/bats-core/bats-core/pull/67

**Comment by mbland** [comment]
Ah, I forgot to add the Appveyor badge in #10:

```markdown
[![Continuous integration status for Windows](https://img.shields.io/appveyor/ci/bash-core/master.svg)](https://ci.appveyor.com/project/bash-core)
```

**Comment by tterranigma** [comment]
I created some PRs that address all but the versioning points in @btamayo's post.

**Comment by sublimino** [comment]
@btamayo @mbland I've edited https://github.com/bats-core/bats-core/issues/13#issue-261867464 to reflect what I think the state of that list is. Many thanks for @tterranigma for filling in some of the blanks!

**Comment by mbland** [comment]
All these features are merged. I also reformated, reorganized, and slightly edited the file as part of #92.
