### ISSUE TITLE
Docker bats/bats doesn't have Bats 1.1.0 in it

### ISSUE THREAD

**Issue by lox** [bats-core/bats-core#133]
It appears the latest official docker image is out of date:

```bash
docker run --rm -it bats/bats:latest --version
Bats 1.0.1
```

Can I assist with this in any way?

**Comment by sublimino** [comment]
Thanks @lox - we don't have these auto-pushed yet, it's on the list.

I've pushed `v1.1.0` (and `v1`, `v1.1`) to the hub.
