### ISSUE TITLE
Print all output even if last line is not followed by a newline

### ISSUE THREAD

**Issue by steff1193** [bats-core/bats-core#141]
```
@test "demo output with no newline is not shown" {
    echo "line 1"
    echo -n "line 2"
    [ 1 -eq 2 ]
}
```

The above test prints out
```
 ✗ demo output with no newline is not shown
   (in test file test.bats, line 63)
     `[ 1 -eq 2 ]' failed
   line 1
```

It should also print out "line 2"

**Comment by mbland** [comment]
Run `bats -v` to see what version you're running. If it _doesn't_ print `Bats v1.0.0`, reopen the issue with the version you're seeing.

From https://github.com/bats-core/bats-core/releases/tag/v1.0.1:

> Ensure the last line of test output prints when it doesn't end with a newline (#99). This was a quasi-bug introduced by replacing sed with while in #88.
