### ISSUE TITLE
Maintain dockerhub bats/bats:latest

### ISSUE THREAD

**Issue by rfay** [bats-core/bats-core#142]
The README demonstrates using `docker run -it bats/bats:latest --version`, however, the :latest tag has not been pushed. It's at 1.0.1. Please push :latest or change the readme.

**Comment by sublimino** [comment]
@rfay thanks, I've pushed the latest.

@btamayo please can I have the Travis CI keys? I'd like to automate this process for new tags.

Or it could be added to the automated release? /cc @mbland @jasonkarns

**Comment by sublimino** [comment]
Ah, it appears that I'm part of the organisation (sorry @btamayo!). Looks like this should be possible, have created https://github.com/bats-core/bats-core/issues/144 to track.
