### ISSUE TITLE
weird ${lines} behavior

### ISSUE THREAD

**Issue by joshfactorial** [bats-core/bats-core#151]
When I try to check against lines, I get weird behavior. It is picking up the names of all the files in the directory where the test script lives. If I echo out the output variable, it looks perfect. If I echo out the lines varible with a for loop, it prints the names of all the files in the directory 

for item in ${lines[@]}
do
   echo "$item" >&3
done

filename1.sh
filename2.sh
actual output1
actual output2
filname1.sh
filname2.sh
actual output2

**Comment by mbland** [comment]
My guess is that `lines` contains strings that contain some globbing metacharacters, namely `*`. Try quoting `"${lines[@]}"`:

```bash
for item in "${lines[@]}"; dp
  echo "$item" >&3
done
```

**Comment by joshfactorial** [comment]
I thought of that on the drive home, and that's exactly it. Putting it in quotes didn't help. Is there a way to force it to see those asterisks as strings or should I try to change it in the script I'm testing?

**Comment by joshfactorial** [comment]
I think it has to be happening when it splits it into lines. I had the test working in one folder, then moved it to another and all the line numbers were wrong.

**Comment by mbland** [comment]
I think you're right. On my phone now; but yes, `run` splits `output` via `lines=($output)`, which would interpret globs. Feel free to file a bug if I don't get to it first.

**Comment by mbland** [comment]
Wait, duh...this _is_ the bug you've already filed.

It's been a long damn day/week/month.

**Comment by martin-schulze-vireso** [comment]
Closing this in favor of #156
