### ISSUE TITLE
Ctrl-C leaves some process running filling disk space with error message

### ISSUE THREAD

**Issue by tardypad** [bats-core/bats-core#154]
Using bats-core 1.1.0 on Arch Linux

When trying to interrupt a test suite running, one process is left running.
And this process keeps adding error data to a file `/tmp/bats.{pid}.out` which fill the disk rather quickly.

I don't know if these are 2 different issues or not.

I've encountered this issue on one of my project but I see now that a similar behavior happens when doing it on the bats-core tests itself.

Here is what I run from the bats-core repository:
- `bats test/bats.bats`
- Hit Ctrl-C before the end

Often (not always though...), the process hangs and I see in the `/tmp/bats.{pid}.out` file many lines containing `/usr/libexec/bats-core/bats-exec-test: line 296: printf: write error: Broken pipe`
The process left running is  that`usr/libexec/bats-core/bats-exec-test`

I had a bit of a different behavior on my project where the main bats command was not left hanging (it was closed properly and I got a prompt back). But that background process was silently filling my disk space all the same.

**Comment by mbland** [comment]
Sounds like we need to check the return value of `printf` on that line and break the loop if it fails. I'll try to repro and dig in if I can; or, if you're inclined, feel free to send a PR.

**Comment by martin-schulze-vireso** [comment]
This might have been solved by #354. Closing for now.
