### ISSUE TITLE
Bats seems to hang with some tests when run on the command line and canceled with SIGINT

### ISSUE THREAD

**Issue by jswaro** [bats-core/bats-core#155]
To work around the issue, our bats test files trap SIGINT and run a handler for that signal. Is this expected behavior? 

```
_cancel() {
    echo caught sigint
    kill -s SIGKILL
}

# necessary to avoid deadlocks during termination/interrupt
trap _cancel SIGINT

```

BASH: GNU bash, version 4.4.12(1)-release (x86_64-suse-linux-gnu)
OS: Linux host 4.12.14-3.2-default #1 SMP Mon Nov 6 10:59:19 UTC 2017 (45613df) x86_64 x86_64 x86_64 GNU/Linux (SLES 12 SP3)

**Comment by jswaro** [comment]
@mbland  I read another issue in the list, and thought you might find this interesting. I am not sure that it is the same problem, but they seem related.

**Comment by mbland** [comment]
[Check for subprocesses that might not close FD 3](https://github.com/bats-core/bats-core#file-descriptor-3-read-this-if-bats-hangs).

That said, we may want to consider adding a `SIGINT` handler while also addressing #154.

**Comment by jswaro** [comment]
Is this specifically an issue that could occur when not explicitly using FD 3? Our scripts don't attempt to write to FD 3 in any way.

**Comment by cdevinesr** [comment]
They don't have to.  They will inherit it from Bats unless you explicitly close it.

There is a pull request (#140) to add a `background` function as a convenience function to close FD 3 for you without you having to think about it when running asynchronous stuff, which could help if that applies to your particular use case.

**Comment by mbland** [comment]
A subprocess might have FD 3 open because it inherited it from the Bats parent process. So if you launch a long-running process and don't close FD 3 when launching it (as illustrated in that README section), your process will still keep it open and hang.

That's _if_ you have any long-running processes, mind you.

**Comment by jswaro** [comment]
In addition to a background function, perhaps a general function to not expose FD 3 ? I mean this is achievable to me by wrapping run, but if there were a general command for it -- then I'd use it.

For the case that I'm looking at, we are using bats to launch jobs on the system, record the output, and produce a tap output file that our jenkins job can read. One of the potential problems is that the workload manager may take certain signals and treat them differently than you might expect, which is why the higher level trap seems to be necessary in our use case. We don't have long-running processes in the sense that we are running services or anything like that, but the jobs could exist in the queue for up to 5 minutes before the timeout command would effectively remove them. 

Example: 
```
run_wrapper() {
    run $@ 3>- 
}
```

**Comment by mbland** [comment]
True, maybe we could just shut off FD 3 in `run` itself. D'oh!

**Comment by jswaro** [comment]
That FD seems to be limited in scope to BATS and the ability to print to bats. 

It could useful, but generally speaking my application/bash function/script would hopefully be delightfully devoid of that file descriptor, and hopefully any functionality associated with it unless there was some good reason to pass it along to the child process/sub processes.

**Comment by cdevinesr** [comment]
FD 3 is used by Bats specifically for handling TAP output, so I doubt your processes will need it, unless they're putting stuff into the TAP stream directly, which seems ill-advised.

**Comment by joshrabinowitz** [comment]
I've been hitting this for a while in bats-core (see issue in git-secret linked above), and I'm not clear how to resolve it, no matter what I do with fd3 or trapping SIGINT. (In our case, we definitely don't need to output to fd3 from the subprograms run in the tests.) 

Would love to see clearer docs, or especially code assistance, in working around/fixing this issue.

**Comment by martin-schulze-vireso** [comment]
@jswaro Explicit SIGINT handling has been added by #354 but the scope of this ticket changed towards shutting down FD3 within run. For more clarity I am closing this issue now and reopen another one that deals with run and FD3.
