### ISSUE TITLE
Testing bats

### ISSUE THREAD

**Issue by vonbrand** [bats-core/bats-core#157]
There are no clear guidelines on running tests on a modified version of bats. E.g., if I patch bats for some bug/enhancement:
- Where should I place tests for my patch? Where/how to document it?
- How do I run existing tests? How do I add my test case to be included as a regression test to be run?

For example, git has a directory with tests, with scripts called `t<number>-<name>`, where `number` codes the area tested and so on. See `t/README` in the git sources.

**Comment by mbland** [comment]
You can run the Bats tests by running `bin/bats test/` in the root directory.

You test should be in the `test/` directory as well. You can add it to `test/bats.test`, or create a new file in the `test/` directory.

Just commented on #156 as well.

**Comment by vonbrand** [comment]
OK, I figured that out. Please document it!

**Comment by martin-schulze-vireso** [comment]
There are several commits which added documentation.
