### ISSUE TITLE
It seems that I am unable to kill the parent BATS process conditionally.

### ISSUE THREAD

**Issue by carlosonunez** [bats-core/bats-core#166]
Consider the following set of test cases:

```bash
#!bats
source fail_fast

teardown() {
  fail_fast
}
@test "Test 1" {
  run whoami
  [ "$status" -eq 0 ]
}

@test "Test 2" {
  run whoami
  [ "$status" -ne 0 ]
}
```

With the following helper defined at `fail_fast.bash`:

```bash
#!/usr/bin/env bash

fail_fast() {
  if [ "$BASH_ERROR_STATUS" -ne 0 ]
  then
    kill -SIGINT $PPID
  fi
}
```

Given that `teardown` runs after a test case finishes executing and the (internal, undocumented) variable `$BASH_ERROR_STATUS` is set with the result of the test, I would expect `fail_fast` to only run when a failing test is hit.

However, it seems to run regardless of whether the first test failed or passed. This can be tested by switching "Test 2" and "Test 1" around.

Weirdly enough, if I use some other mechanism of killing the parent process (through `pkill` or other means), I'm unable to.

Is this a bug? If not, is there some other way to fail a test run if any test in the suite fails?

**Comment by bvberkum** [comment]
Can you post output, this to seems to pass what you describe.

```
 ✓ Test 1
 ✗ Test 2
   (in test file test/fail-fast.bats, line 14)
     `[ "$status" -ne 0 ]' failed
   fail_fast: line 4: [: : integer expression expected
```

Replace expression with ``${BASH_ERROR_STATUS:-0} -ne 0``. Then with switching the tests around pass/fail, fail/pass:

```
 ✓ Test 1
 ✗ Test 2
   (in test file test/fail-fast.bats, line 14)
     `[ "$status" -ne 0 ]' failed

2 tests, 1 failure

shell returned 1
```

```
 ✗ Test 2
   (in test file test/fail-fast.bats, line 10)
     `[ "$status" -ne 0 ]' failed
 ✓ Test 1

shell returned 1
```

**Comment by carlosonunez** [comment]
I'm closing this issue, as I was able to find a better workaround to what I was trying to accomplish. (It can be found [here](https://github.com/sstephenson/bats/issues/135#issuecomment-242366074)
