### ISSUE TITLE
Test "name" has to be equal?

### ISSUE THREAD

**Issue by Andy1978** [bats-core/bats-core#170]
This test file fails twice:

```
@test "foo" {
  run echo 0
  [ "$output" -eq 0 ]
}

@test "foo" {
  run echo 1
  [ "$output" -eq 0 ]
}
```

Is this expected? I didn't find any hint, that the tests "name/output" has to be unique

**Comment by jasonkarns** [comment]
Yes, they have to be unique. The test names are converted to functions (using the test name as the function name) so the second test overrides the first definition of that function.

**Comment by Andy1978** [comment]
Okay, thank you. I think there should be a hint, that test names should be unique or even better: show a warning if this is not the case.
