### ISSUE TITLE
Handle case where bats is not called directly from bash

### ISSUE THREAD

**Issue by pawamoy** [bats-core/bats-core#182]
I use bashcov to get coverage data for my scripts, and I encounter this issue:

https://github.com/infertux/bashcov/issues/48

Since I run `bashcov bats tests`, bats does not find its correct path because `$0` is not what it expects.

Of course I can run `bashcov /path/to/bats tests` so it's not a critical issue.

**Comment by waterkip** [comment]
Could you maybe check this with my branch, see #183 and #184

**Comment by pawamoy** [comment]
@waterkip yup, working for me! :tada: thanks

**Comment by pawamoy** [comment]
There's a PR, closing.
