### ISSUE TITLE
Add output debug functions

### ISSUE THREAD

**Issue by krufab** [bats-core/bats-core#186]
I'd find it useful to have a couple fo debug functions like `bats_debug_output` and / or `
bats_debug_lines`, to avoid manually echoing the output when writing tests.
I could create a PR for this, if it might be of interest

**Comment by waterkip** [comment]
I'd like to have something like this as well. I've created `diag()` in one of my tests that just does that.
You can than do things like `diag "$output"` and well, anything.

```
diag() {
    echo "$@" | sed -e 's/^/# /' >&3 ;
}
```

**Comment by nqb** [comment]
Hello,

I'm interesting by this feature too.

**Comment by kolyshkin** [comment]
Here's my version of the [above](https://github.com/bats-core/bats-core/issues/186#issuecomment-465875518):

```bash
diag() {
    echo "# DEBUG $@" >&3
}

**Comment by martin-schulze-vireso** [comment]
@krufab Did it work? If not, feel free to reopen with more details.
