### ISSUE TITLE
Prining to FD 3 shows before the test result in the TAP stream

### ISSUE THREAD

**Issue by filmil** [bats-core/bats-core#187]
As an example, I have a teardown print the total test timing like this:

```
1..1
# total time: 22786ms
ok 1 All acme corp created
```

This is not conforming to TAP as the comment should follow the line with `ok`.

**Comment by phillipao** [comment]
I don't think this is confined to shutdown(). Rather, anything sent to FD 3 in setup, test, or shutdown is printed immediately to stdout. I'd say that, as written, FD 3 should only be written by bats itself. It just happens to be accessible to tests. But it shouldn't be. A good solution would be to redirect 3 to a file during setup/test/shutdown execution, and dump that to stdout at the end.

**Comment by martin-schulze-vireso** [comment]
Since the behavior is as expected, I decided to Mark this as won't fix. If you need Output to be aligned, print to stderr/out. If you need to show it even in success, there is `--show-output-of-passing-tests` for that.
