### ISSUE TITLE
how to get summary with --tap

### ISSUE THREAD

**Issue by archenemies** [bats-core/bats-core#188]
It looks like there is a function called 'summary' which summarizes the test results,

    $ grep -r summary /usr/lib/bats/
    /usr/lib/bats/bats-format-tap-stream:summary() {
    /usr/lib/bats/bats-format-tap-stream:buffer summary

however this function is not available to my test script and it doesn't seem to be getting called when I pass `--tap`

    $ ./t-bats
    1..2
    ok 1 sample test
    ok 2 another test

here's the script

    #!/usr/bin/bats --tap

    @test "sample test" {
    true;
    }

    @test "another test" {
    true;
    }

Can we make "summary" the default and/or document how to get it called? thanks

**Comment by archenemies** [comment]
By the way I may be running the wrong version, I installed via Arch repos and it points to the "other" project:

    $ pacman -Qi bash-bats
    Name            : bash-bats
    Version         : 0.4.0-2
    Description     : Bash Automated Testing System
    Architecture    : any
    URL             : https://github.com/sstephenson/bats

Should Arch be packaging "bats-core/bats-core" instead of "sstephenson/bats"?

**Comment by martin-schulze-vireso** [comment]
bats' tap format does not offer a summary. That is part of the pretty formatter, which bats-format-tap-stream is actually implementing.

> By the way I may be running the wrong version

Thanks for pointing that out. The wiki now advises about installing bats-core from the AUR.
