### ISSUE TITLE
Support for commands that return non-zero exit status

### ISSUE THREAD

**Issue by archenemies** [bats-core/bats-core#190]
I wanted to reference [this issue](https://github.com/sstephenson/bats/issues/251) from sstephenson/bats.

The question was how to run a command with non-zero exit status.

Seems to be a couple of solutions

* prefix 'run'
* [use '|| true'](https://superuser.com/a/940514/576570)

The second one worked better when I was calling 'read'.

**Comment by martin-schulze-vireso** [comment]
I am not sure what exactly you want to achieve here.
If you want to check the output from the command as well, use `run`, else simply run the command with `!`. Then there is also `assert_failure` from the asserts library, if you only want to have output for the `run` when `assert_failure` fails.
