### ISSUE TITLE
get bats-core in debian

### ISSUE THREAD

**Issue by joshrabinowitz** [bats-core/bats-core#193]
`bats` is in debian, (See https://packages.debian.org/search?keywords=bats); `bats-core`, as the updated mutated twin of bats, should be there too!

Perhaps approach whoever packaged `bats` for debian about packaging `bats-core`, or replicate their work?

Related to #103

**Comment by ycdtosa** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=925095 was open 19 Mar 2019

**Comment by ycdtosa** [comment]
And it seems the sources for the debian package are in github.
https://github.com/neurodebian/bats/tree/debian/debian

It is a fork from sstephenson:master.

**Comment by martin-schulze-vireso** [comment]
Debian bullseye and sid have [bats-core v1.1.0](https://packages.debian.org/search?keywords=bats).
