### ISSUE TITLE
update bats-core documentation to not tell people to install bats, or clarify difference

### ISSUE THREAD

**Issue by joshrabinowitz** [bats-core/bats-core#194]
As mentioned at https://github.com/bats-core/bats-core/issues/103#issuecomment-436977847 , bats-core documentation in many cases currently directs people to install bats, and not bats-core. 

It seems that this is intentional, but maybe users should be made more aware of the difference at in the page at https://github.com/bats-core/bats-core/wiki/Install-Bats-Using-a-Package#ubuntu

Relates to #103 and #193

**Comment by martin-schulze-vireso** [comment]
The current wiki now says this for Ubuntu

> ⚠️ Caution: This repository 📦 distributes sstephenson bats v0.4.0 🐼
