### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by juanibiapina** [bats-core/bats-core#195]
It seems this project has gained a lot of traction, has fixed a bunch of the most annoying issues of bats and gathered many contributors.

So, why not rename it and make it into its own framework? Currently it has a weird name (`bats-core`) and it doesn't really stand by itself. This makes it much harder for people to adopt it, in my opinion. The main binary name also conflicts with `bats` so people can't have both installed at the same time.

**Comment by btamayo** [comment]
Hm, I'm not opposed to renaming/aliasing the project itself as long as it's planned and done carefully if there's a compelling reason. However, this is essentially a community-maintained continuation of bats, so the binaries being named the same is intentional.
