### ISSUE TITLE
Add an option to pass command line flags to bats tests

### ISSUE THREAD

**Issue by filmil** [bats-core/bats-core#198]
Sometimes it is useful to be able to accept parameters from outside a `bats` test.  
As use case, I have a bats test that I'm developing on `bazel` (http://bazel.build). I'm testing a certain binary.  However, the location of the binary is decided by bazel at compile time, and has to be passed in as a parameter into the tests in order to run the tests cleanly.

**Comment by tterranigma** [comment]
Can't you use environment variables to pass the the location of the binary?

**Comment by filmil** [comment]
Hi folks! Yes, I can use environment variables.

A potential issue with them is that you have no control over what envs gets propagated where and more often than not that propagation is kind of opaque.  At least more opaque when compared to doing the same with flags.  Flags you must pass explicitly, and scripts that don't support them can reject them. No such checks are typically made on env vars.

I can imagine, however, that you may not consider this as a burning enough issue to modify bats-core over it, and that's fine. I can make do with envs and have implemented something to that effect already.

If you don't think this is worth the effort, feel free to close.

Cheers, and thank you for your feedback,
F

**Comment by sublimino** [comment]
Agreed that propagation can be tricky. In this case I was imagining that, instead of 

```
bats --some-flag my-value
```

One could use

```
ENV_VAR=my-value bats
```

> Flags you must pass explicitly, and scripts that don't support them can reject them. No such checks are typically made on env vars.

As a workaround one could fail a test if the required environment variable isn't populated.

I'll close this for now, please add more if I've missed the point. Thanks :D

**Comment by filmil** [comment]
> As a workaround one could fail a test if the required environment variable isn't populated.

I'm not so much worried about non-populated variables but rather env var declarations that leak into scripts and libraries and potentially misconfigure them due to naming clashes.  Yes you can work around them, and it's normally not an issue, except when it is :)  If I were writing a specific test then I wouldn't worry so much about it, but since I'm working on a library to support bats-core in bazel, then I need to think about such stuff just as well.

**Comment by sublimino** [comment]
Ah, I see - it's a generic Bats running for Bazel, rather than testing a specific project that happens to use Bazel?

Could another option be to reassign the env var to a local, then unset it in the test scripts? Doesn't quite solve the case though.

If not, could you provide some example CLI invocations so we can open up the discussion? Perhaps `bats --custom-variable X=Y` - although of course then further variables may be required. Suggestions welcome :pray:
