### ISSUE TITLE
Package relying on ncurses/terminal info fails to build

### ISSUE THREAD

**Issue by ladar** [bats-core/bats-core#201]
@oreinert et al, if you're still working to fix the issue described [here](https://lists.opensuse.org/opensuse-factory/2017-02/msg00502.html) I think I figured out waht is causing `tput` to barf.

I stumbled across that list message because I was getting the same error message on my project. It seems that `tput` gets very unhappy on some distros when it's run without a TTY. Arch and Fedora 27 in particular. To workaround the issue, I updated my `bash` scripts to use the following logic:

```
[[ -t 0 ]] && tput setaf 1
```

This will test for the `0` file descriptor (usually stdin), and only run `tput` only if that descriptor is valid. In my case I also needed to reset the status code, so I used the following:

```
[[ -t 0 ]] && tput setaf  1 || true
```

I also wanted to account for systems with a TTY, but no TERM environment variable (which I also ran  into), so I changed `tput` into the `${TPUT}` macro, so I could provide a term value if necessary:

```
if [[ -n "$TERM" ]] && [[ "$TERM" != "dumb" ]]; then
  export TPUT="tput"
else
  export TPUT="tput -Tvt100"
fi
```

In the end I had:

```
[[ -t 0 ]] && ${TPUT} setaf 2 || true ; printf "Done.\n" ; [[ -t 0 ]] && ${TPUT} sgr0 || true
```

Yes, I should turn this into `bash` function, to simplify things. I'll do that later.

For one of my actual scripts, see [the setup](https://github.com/lavabit/magma/blob/782bb921da28818e75c9e962fb86af1e086f5613/dev/scripts/database/schema.reset.sh#L29-L34) and [its use](https://github.com/lavabit/magma/blob/782bb921da28818e75c9e962fb86af1e086f5613/dev/scripts/database/schema.reset.sh#L165). Because `tput` was the last command, it's error code was making the script return `1` which is why I ended up adding the `true`. I eventually added it to all invocations, since I sometimes like to run scripts with `set -e` aka `bash -e` and didn't want `tput` to force a premature exit.

**Comment by martin-schulze-vireso** [comment]
As I see no bats code in your referenced projects, I assume that you just wanted to ping @oreinert with relevant info @ladar?
Thanks for reaching out.

I am closing this, since there is no further discussion going on here.
