### ISSUE TITLE
ensure unofficial bash script mode test fails when run out of the tree

### ISSUE THREAD

**Issue by ycdtosa** [bats-core/bats-core#202]
I am trying to pass the source tree tests out of place, running an installed bats binary.
This is the failing test from the bats.bats file.
```
@test 'ensure compatibility with unofficial Bash strict mode' {
  local expected='ok 1 unofficial Bash strict mode conditions met'

  # Run Bats under `set -u` to catch as many unset variable accesses as
  # possible.
  run bash -u "${BATS_TEST_DIRNAME%/*}/bin/bats" \
    "$FIXTURE_ROOT/unofficial_bash_strict_mode.bats"
  if [[ "$status" -ne 0 || "${lines[1]}" != "$expected" ]]; then
    cat <<END_OF_ERR_MSG
          ...blah blah blah
END_OF_ERR_MSG
    emit_debug_output && return 1
  fi
}
```

However it is failing because there is no "${BATS_TEST_DIRNAME%/*}/bin/bats" since i copied the tests out of the tree to a different location.

I want to test that the installed (/usr/bin/bats) bats is working!

The test tries to run bats with
```
run -u "${BATS_TEST_DIRNAME%/*}/bin/bats" \
   "$FIXTURE/unofficial_bash_script_mode.bats"
```

Is there any reason why i can not just use bats like most other tests at bats.bats
without the relative path trough the tests dirname? 

```
run -u bats \
   "$FIXTURE/unofficial_bash_script_mode.bats"

```

I have changed it and the test passes in both locations, in the source tree and in the isolated tree.

**Comment by ycdtosa** [comment]
to fully reproduce the issue...

```
cp -r bats-core/test ~/test
# bats has been installed, and bats is in the path.
# I want to test if the bats binary in the path works.
bats ~/test
```

the test will fail, because there is no `~/test/../bin/bats` to run

**Comment by ycdtosa** [comment]
I would say this is related

> To close the loop on this: I found and explained the breakage in #93, which actually wasn't due to #92. The "unofficial Bash strict mode" test failed because it was looking for `bats` relative to `BATS_TEST_DIRNAME`, which it couldn't because the `test` directory was mounted into the container in isolation. Mounting the root of the Bats project resolved the issue.

_Originally posted by @mbland in https://github.com/bats-core/bats-core/pull/91_

**Comment by martin-schulze-vireso** [comment]
@ycdtosa  Can you verify that this is fixed now?
