### ISSUE TITLE
bats waits for disowned processes even when FD3 is closed

### ISSUE THREAD

**Issue by 3hhh** [bats-core/bats-core#205]
Example:

```bash
#!/usr/bin/env bats

function bgfunc {
sleep 3

echo "bgfunc done"

return 0
}

function otherfunc {
bgfunc 3>&- &
disown
return 0
}

@test "min bg" {
echo "sec: $SECONDS"
run otherfunc
echo "$output"
[ $status -eq 0 ]
echo "sec: $SECONDS"
echo "check done"
[ 1 -eq 0 ]
}
```

Expected behaviour:
```
sec: 0
...
sec: 0
```

Actual behaviour:
```
sec: 0
...
sec: 3
```

The behaviour without `run` appears to be similar: The single statement doesn't wait anymore, but the entire test will wait until all background processes finish. That may well be forever for e.g. daemons with a continuous background loop. Closing FD3 apparently only makes background statements last as long as they usually do (e.g. 3 seconds instead of forever). Sometimes I didn't observe any effect.

bats version: 1.1.0

**Comment by martin-schulze-vireso** [comment]
I can still reproduce this behavior on master.

**Comment by martin-schulze-vireso** [comment]
To sum up what I found so far:

1. when using `run`, the stdout is captured via `output=$()`. This necessitates waiting for stdout to be closed. If the process under run has a subprocess (`bgfunc`) that did not yet close stdout, the `$()` will block. This means we need to override stdout for the background process. When we do this we are equal to ...
2. when not using `run`, the pipe to the formatter hangs until the background process finished
