### ISSUE TITLE
Is loops supported?

### ISSUE THREAD

**Issue by AnthonyWC** [bats-core/bats-core#206]
In the original bat repo, there are some issues (e.g. https://github.com/sstephenson/bats/issues/179) that talked about why bats didn't support loop but there was also mention of loop support for version 1.0.

Is loop feature supported (or still plan to be)?  If not, is there any workaround?

**Comment by AnthonyWC** [comment]
Note: As a workaround; I used a bash script to generate the bats script so I am able to use loop (in bash).

**Comment by blag** [comment]
Issue sstephenson/bats#179 was linked to from sstephenson/bats#196, but nowhere has anybody said that it would be supported.

Furthermore, it seems like you didn't read [this comment](https://github.com/sstephenson/bats/issues/136#issuecomment-201120112) from sstephenson/bats#136 as to why it's not supported, **and** why you should not use a script to generate the BATS file.

He does mention how you should structure your tests though, so there is a workaround available.

This issue can be closed.

**Comment by jasonkarns** [comment]
Documented fairly well above (thanks @blag ) on why loops aren't supported and some better alternatives.
