### ISSUE TITLE
hooks for after_run / before_run

### ISSUE THREAD

**Issue by joshrabinowitz** [bats-core/bats-core#207]
Feature Request:

I've found myself wanting a hook, let's call it `after_run`, that is called after each `run` invocation and allows me to inspect or log the contents of `$status`, `$output`, and `$lines`. 

Otherwise, by the time the `teardown` callback is called, they only hold the values from the last `run` command.

For consistency, perhaps a `before_run` hook should be added too.

(This is similar to the issues discussed in #39 but is distinct as it concerns hooks for each `run` command.)

**Comment by joshrabinowitz** [comment]
See #208

**Comment by dimo414** [comment]
What do you want to do in this hook? Shouldn't you be inspecting those variables in your test? Some concrete use-cases would help identify whether this feature is the best way to provide what you're trying to accomplish.

Note you can always add your function that wraps `run` to do anything special you need, e.g.:

```
spy_run() {
  run "$@"
  run_hook # $status, $output, and $lines will be accessible here
}
```

**Comment by joshrabinowitz** [comment]
It's been over a year since I wrote this feature request, and my motivation is unclear now, I haven't been working on this project for a bit. Will try to remember why I made this request.

**Comment by jasonkarns** [comment]
Closing for now. Happy to reopen if @joshrabinowitz 's initial motivation returns!
