### ISSUE TITLE
curl output mismatch

### ISSUE THREAD

**Issue by oskude** [bats-core/bats-core#211]
manual test:
```
❯ curl -s http://kernel.org
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
❯ echo $?
0
```

`hmm.bats` test file:
```
@test "hmm" {
	run curl -s http://kernel.org
	[ "$status" -eq 0 ]
	[ "${lines[0]}" = "<html>" ]
}
```

i would think that above bats file would not fail, but it does:
```
❯ bash --version | head -n 1
GNU bash, version 5.0.2(1)-release (x86_64-pc-linux-gnu)
❯ bats --version
Bats 0.4.0
❯ bats hmm.bats 
 ✗ hmm
   (in test file hmm.bats, line 4)
     `[ "${lines[0]}" = "<html>" ]' failed

1 test, 1 failure
```

whats wrong?

FWIW, output lines seem to end with `\r\n`:
```
❯ curl -s http://kernel.org | od -c | head -n 1
0000000   <   h   t   m   l   >  \r  \n   <   h   e   a   d   >   <   t
```

**Comment by rockandska** [comment]
seems related to the redirection because the example bellow who follow the redirection works

```
bash-4.4$ bash --version | head -n1
GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)
bash-4.4$ bats --version
Bats 1.1.0
bash-4.4$ cat hmm.bats
@test "hmm" {
	run curl -sL http://kernel.org
	[ "$status" -eq 0 ]
	[ "${lines[0]}" = "<!DOCTYPE html>" ]
}
bash-4.4$ bats hmm.bats 
 ✓ hmm

1 test, 0 failures

bash-4.4$ 
```

**Comment by sublimino** [comment]
@rockandska do you have a shell alias in your Bash (non-Bats) session perhaps? `type curl` will reveal it if so

**Comment by rockandska** [comment]
@sublimino , no alias at all for curl
```
$ type curl
curl is /usr/bin/curl
```
the main difference i see between the original example and mine is the carriage return on first line and this carriage return seems interpreted and seems to be the reason of the failure

```
$ cat plop.bats 
test_curl(){
  curl -s http://kernel.org | sed 's/\r//g'
}

@test "original" {
	run curl -s http://kernel.org
	printf "x%sx\n" "${lines[0]}"
	printf "x%sx\n" "${lines[0]}" | od -c
	[ "$status" -eq 0 ]
	[ "${lines[0]}" = "<html>" ]
}

@test "tr removed" {
	run test_curl
	printf "x%sx\n" "${lines[0]}"
	printf "x%sx\n" "${lines[0]}" | od -c
	[ "$status" -eq 0 ]
	[ "${lines[0]}" = "<html>" ]
}
```

```
$ bats plop.bats 
 ✗ original
   (in test file plop.bats, line 10)
     `[ "${lines[0]}" = "<html>" ]' failed
x  x<html>
   0000000   x   <   h   t   m   l   >  \r   x  \n
   0000012
 ✓ tr removed

2 tests, 1 failure

```

**Comment by norricorp** [comment]
Hi @rockandska 
can you explain why status requires everything to be in the function.
For instance if I have function of curl .... | sed ... | jq '. | length' and the call run function, I get status of 0.
But if I have code after run eg run function |  jq '. | length' (having it removed jq from function) then I get status error.
Using your approach things now work, but be interesting to know why the code needs to be in a function.
Regards,
John

**Comment by martin-schulze-vireso** [comment]
@norricorp Please don't hijack other issues for unrelated problems. If you have trouble writing your bats tests as intended, there is a discussion channel on [gitter.im](https://gitter.im/bats-core/bats-core) where you can get help.

I still think we should put up a tutorial and list of common beginner mistakes so I propose you add your question in #358.

**Comment by norricorp** [comment]
Apologies, I didn't think I was hijacking, more wondering why running the code indirectly via a function gave the desired result.

**Comment by martin-schulze-vireso** [comment]
> this carriage return seems interpreted and seems to be the reason of the failure

Then let's move the discussion to #249
