### ISSUE TITLE
bats-core in alpine: error rm: command not found

### ISSUE THREAD

**Issue by divramod** [bats-core/bats-core#218]
Hey, 

thx for the awesome project!

i am running bats-core in a alpine-3.9 docker container and getting this error message:

```
$ command -v rm
/bin/rm
$ testing -S -f cicd
...
1..1
ok 1 [ cicd ] cicd -T
/builds/calponia/devops/vendors/bats-core/libexec/bats-core/bats-exec-test: line 303: rm: command not found
```

Does anyone has an idea by what this problem could be triggered by?

**Comment by martin-schulze-vireso** [comment]
Could this be the same problem as #230? Please reopen and provide more details (the test file and the exact bats invocation) if this issue still persists.
