### ISSUE TITLE
Automatic output of `run` contents upon a failed test

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [bats-core/bats-core#22]
Hi!

When I have a test like this,

```bash
@test "integers: 0" {
   cat <<-PROGRAM >program.scm
		0
	PROGRAM
   run ocameel program.scm

   [ "$status" -eq 0 ]
   [ "$output" = "0" ]
}
```

… output like this seems surprisingly unhelpful:

```
 ✗ integers: 0
   (in test file test/tests-1.1.bats, line 25)
     `[ "$output" = "0" ]' failed
```

I would expect to see, at least, something like this:

```
 ✗ integers: 0
   (in test file test/tests-1.1.bats, line 25)
     `[ "$output" = "0" ]' failed;
       $status: 0
       $output:
         this
         was some output
```

----

Of course, there's some concerns with output-length here; as well as some UX determination. For instance, if a failed line's variables are short enough, I'd *really* love to see interpolated output (i.e., instead of `` `[ "$output" = "0" ]' failed ``, if `$output` is ≤50 characters or something else arbitrary, `` `[ "this\nwas some output" = "0" ]' failed ``.)

Hope this is a well-received Issue, and one of some interest to the new team! Thanks for your consideration!

**Comment by ELLIOTTCABLE** [comment]
(Of note, things like @ztombol's [bats-assert](https://github.com/ztombol/bats-assert) can already be used to do something like this — I just think it belongs in the core tool!)

**Comment by mbland** [comment]
I've also [a ton of Bats assertions and other helpers in mbland/go-script-bash](https://github.com/mbland/go-script-bash/tree/master/lib/bats) that could probably live in bats-core or bats-assert or some other library. (Though tested in my framework's Bats suite, they're independent of the go-script-bash framework itself.)

**Comment by elfgoh** [comment]
Wished there was an upvote button for this!

**Comment by espoelstra** [comment]
This would definitely be handy, though using `bats-assert` works pretty well. What I discovered after running bats from a vendored test/lib directory instead of via the Docker container is that using the `echo "# status: $status" >&3` syntax pollutes/overwrites the pretty output, but doesn't appear to affect the fallback `--tap` output that occurs in the container, even if I tried to force `--pretty`.

**Comment by jasonkarns** [comment]
Closing this for now, since the discussion about which (if any) helper libs to include in bats is over here: https://github.com/bats-core/bats-core/issues/44
