### ISSUE TITLE
need input files for a test

### ISSUE THREAD

**Issue by salderma** [bats-core/bats-core#220]
Hi, this is my first stab at BATS.

I have a simply script which takes a -f to pass a file name into the script.  In my BATS test I have this:
```
@test "with -f arg" {
  run echo 'testing with -f test.file' > test.file
  [ $status -eq 0 ]

  run ./myscript.sh -f test.file
  [ $status -eq 0 ]
  [ "${lines[0]}" == 'testing with -f test.file' ]
}
```
Executing bats shows the test fails quoting the `${lines[0]}` part.  The resulting test.file is empty, and it should have the specified string in it.

Can someone point me in the right direction?

P.S. I realize that I probably should put the creation of the test inputs in a the setup function and cleanup both inputs and outputs in the teardown function... but baby steps.

**Comment by pawamoy** [comment]
Try this:

```bats
@test "with -f arg" {
  echo 'testing with -f test.file' > test.file

  run ./myscript.sh -f test.file
  [ $status -eq 0 ]
  [ "${lines[0]}" == 'testing with -f test.file' ]
}
```

**Comment by salderma** [comment]
Thanks a bunch! That takes care of it...I guess I was too strictly following the examples to realize the consequence of the run function.
