### ISSUE TITLE
`$lines`  keep blank empty lines in `$output` 

### ISSUE THREAD

**Issue by Sylvain303** [bats-core/bats-core#224]
The bats code involved is also related to: #151 

The faulty code is [here](https://github.com/bats-core/bats-core/blob/master/libexec/bats-core/bats-exec-test#L64) 

```bash
run() {
  local origFlags="$-"
  set +eET
  local origIFS="$IFS"
  output="$("$@" 2>&1)"
  status="$?"
  IFS=$'\n' lines=($output)
  IFS="$origIFS"
  set "-$origFlags"
}
```

Reproduce:

```bash
#!/bin/bash

usage() {
  cat << EOT
pipo

molo
EOT
}

@test "test lines with empty line" {
  run usage
  echo "$output" >> log
  num_lines=$(wc -l <<<"$output")
  [[ $num_lines -eq 3 ]]
  n=${#lines[@]}
  for i in $(seq 0 $((n - 1)))
  do
    echo "$i:${lines[$i]}" >> log
  done

  [[ ${lines[0]} == "pipo" ]]
  [[ ${lines[1]} == "" ]]
  [[ ${lines[2]} == "molo" ]]
  [[ $num_lines -eq ${#lines[@]} ]]
}
```

I suppose that fixing it will introduce some outside test failure based on this bugged behavior.

**Comment by Sylvain303** [comment]
One fix could be, using bash internal function [readarray](https://www.gnu.org/software/bash/manual/html_node/Bash-Builtins.html#index-readarray)

```bash
readarray -t lines <<< "$output"
```

As we could expect, bats self tests are now failing based on wrong index line.

```
sylvain@lap42:~/code/bats-core/test$ ../bin/bats  .
[...]
75 tests, 21 failures, 2 skipped
```

**Comment by dimo414** [comment]
`readarray` / `mapfile` is Bash 4.0+ only, so I don't think BATS can use it currently, but I definitely agree this behavior is busted and unreliable (see also #281). I've mailed #289 to hopefully address this.

**Comment by martin-schulze-vireso** [comment]
Hm, I had a typo. c6278fd was meant to close this.
