### ISSUE TITLE
Remove preprocessed source

### ISSUE THREAD

**Issue by Flamefire** [bats-core/bats-core#231]
The preprocessed source is not removed after the test is run.

Chain of events:
- Create preprocessed source
- Set trap on `err exit int` to remove it
- Start `perform_test`
- Set traps in `err exit` overwriting the prior one
- Run test function
- exit

Solution: Call `bats_cleanup_preprocessed_source` in `bats_exit_trap`

**Comment by sublimino** [comment]
This solution seems reasonable to me @Flamefire 	

It also highlights an annoyance with `trap`s -- I've seen mechanisms for adding multiple traps, or adding them to a queue, but they can easily be accidentally overwritten.

Will test and merge 🙏

**Comment by Flamefire** [comment]
> It also highlights an annoyance with traps -- I've seen mechanisms for adding multiple traps, or adding them to a queue, but they can easily be accidentally overwritten.

Have seen them too and wouldn't recommend using it. Looks very fragile and adds quite some complexity.

Hope you've seen #232 which implements the suggested change. It's 1 line :)
