### ISSUE TITLE
bats fail to run when installed locally

### ISSUE THREAD

**Issue by DazEdword** [bats-core/bats-core#233]
Occurs on MacOs with bash version 5.0.7(1)-release (x86_64-apple-darwin18.5.0).

I have cloned the repo, and installed to `./my-project/dependencies/bats` using `install.sh`, which seems to succeed:

`Installed Bats to .my-project/dependencies/bats-core/bin/bats`

However, when I try to run my test file:

`./dependencies/bats-core/bin/bats tests/scripts/my-test.bats`

```
.my-project/dependencies/bats-core/libexec/bats-core/bats: line 171: exec: bats-exec-suite: not found
.my-project/dependencies/bats-core/libexec/bats-core/bats: line 171: bats-format-tap-stream: command not found
```

I think the issue has to be with `$PATH`, since if I manually edit `./dependencies/bats/bin/bats` to add bats` path like the following:

`export PATH="$PATH:<user-absolute-path>/project/dependencies/bats/bin/"`

Then everything works as intended and tests run perfectly. Classic `bats` (as opposed to `bats-core`) works on local installation without requiring that $PATH update.

Any ideas on the best way to fix this?

**Comment by Pixcell** [comment]
This fails for me too, I ran `git clone https://github.com/bats-core/bats-core.git && cd bats-core && sudo ./install.sh /usr/local` from my $HOME dir.

I now have those errors:
```
[16:35]$>bats -v
/usr/bin/readlink: illegal option -- f
usage: readlink [-n] [file ...]
Bats 1.2.0-dev
```
```
[16:35]$>bats test/smoke.bats
/usr/bin/readlink: illegal option -- f
usage: readlink [-n] [file ...]
/usr/local/libexec/bats-core/bats: line 171: exec: bats-exec-suite: not found
/usr/local/libexec/bats-core/bats: line 171: bats-format-tap-stream: command not found
```

It used to work with https://github.com/sstephenson/bats

**Comment by bilke** [comment]
You need to install `coreutils` via Homebrew or MacPorts.

**Comment by alvations** [comment]
This seems to work:

```
$ brew install bats-core

$ which bats
/usr/local/bin/bats

$ cp /usr/local/Cellar/bats-core/1.2.0/libexec/bats-core/* /usr/local/bin/
```

**Comment by sublimino** [comment]
@DazEdword @Pixcell [this recently merged PR](https://github.com/bats-core/bats-core/pull/312) re-implements readlink so `coreutils` may not be required. I don't have an OSX device to test, if you hav the time to verify this in master it would be appreciated : ] No worries if not 🙏
