### ISSUE TITLE
Bats-Core much slower than bats

### ISSUE THREAD

**Issue by bemeyert** [bats-core/bats-core#235]
Bats Version: 1.1.0 (installed via `install.sh` from the repo)

Hi all, I a test file with slightly over 4000 tests containing only curl commands. When I run the test with the old `bats` it takes about 24 minutes. I had to cancel a run with `bats-core` after an hour where it managed to run about 1000 tests.
Why is it so much slower? Am I doing something wrong?

Thx for any help

**Comment by sublimino** [comment]
It's difficult to say without seeing what's being tested @bemeyert - can you provide a reproduction case? It could be a regression, but we'd want to rule out network conditions etc. 

There is no performance regression suite for `bats-core`, this may be an opportunity to add one.

**Comment by bemeyert** [comment]
Example code:
```
#!/usr/bin/env bats

[[ ! $VARNISH_URL ]] && { echo "# ERROR: Environment variable \$VARNISH_URL ist not set!" >&3; exit 1; }


@test "redirect -> target code" {
    run curl -s -o /dev/null -w "%{http_code}" -H "Host: redirect" "$VARNISH_URL"
    echo $output
    [[ $output -eq 301 ]]
    [[ $status -eq 0 ]]
}

@test "redirect -> target location" {
    run curl -s -o /dev/null -w "%{redirect_url}" -H "Host: redirect" "$VARNISH_URL"
    echo $output
    [[ $output == "https://target/" ]]
    [[ $status -eq 0 ]]
}
[...]
```
And there are about 2000 of those pairs.

**Comment by sublimino** [comment]
Thank you. I will set this up with a local test endpoint to validate and consider a performance regression baseline. 

In the meantime bats-core has a new `--jobs n` flag for parallelism that may be of use.

**Comment by bemeyert** [comment]
Cheers for checking this out. I already tried running with parallel (-j 4 and 6). But that didn't speed up noticeably the process (but my laptop was cooking ;) ).

**Comment by bemeyert** [comment]
@kr1sp1n FYI

**Comment by martin-schulze-vireso** [comment]
I recently have gone through the plumbing of both the current bats-core and the last pre-fork version. One difference that I spotted: the old version had all tests in one shell instance while the new one starts each test in its own subshell.

However, your reported values imply your average time per test increased from <0.5s to >3s. An additional 2.5s sounds like a long time just for setting up a new subshell.

**Comment by martin-schulze-vireso** [comment]
I compared the timings for v0.4.0 and current master again and master seems slightly faster thanks to #335.
