### ISSUE TITLE
parallel tests fail (on Debian sid, bash 5.0.3)

### ISSUE THREAD

**Issue by yarikoptic** [bats-core/bats-core#240]
```shell
$> bin/bats --tap --filter '.*parallel.*' test
1..2
not ok 1 parallel test execution with --jobs
# (in test file test/bats.bats, line 477)
#   `[ "$status" -eq 0 ]' failed
not ok 2 parallel suite execution with --jobs
# (in test file test/suite.bats, line 136)
#   `[ "$status" -eq 0 ]' failed
```

what would be the best (easiest) way to figure out details?
In our case (since could not find anything better) we added helpers to report what was actually received and comparison helpers: https://github.com/ReproNim/containers/pull/27/files#diff-20f43f2d38899fc3bd54a8b6110e1e14
Sorry for derailing -- What would be really cool if, similar to pytest/nose in Python world, there was --dbg option to jump into that environment (may be using bashdb if possible/benefitial) to investigate

**Comment by yarikoptic** [comment]
ok, trying it out resolves the mystery:
```shell
$> bin/bats --jobs 2 test/bats.bats 
parallel: invalid option -- 'q'

59 tests, 0 failures, 59 not run
```
and I have
```shell
$> dlocate `which parallel` 
moreutils: /usr/bin/parallel

$> acpolicy moreutils      
moreutils:
  Installed: 0.62-1
  Candidate: 0.62-1
  Version table:
     0.63-1 600
        600 http://http.debian.net/debian sid/main amd64 Packages
 *** 0.62-1 900
        900 http://http.debian.net/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
```
upgrade to 0.63 didn't help... but I guessed it is not actually the "parallel" bats wants -- it is not the "GNU parallel" which is provided by the "parallel" package.  Installing that one resolved the failure.

I guess it would be great if `bats` sensed first if available "parallel" is the right one first, and fall back to serial execution if NA.

**Comment by sublimino** [comment]
@yarikoptic we have replaced parallel with a Bash-native implementation, please re-open if this doesn't work for you :pray:
