### ISSUE TITLE
Reading a multi-line here document fails inside a test

### ISSUE THREAD

**Issue by Ian2020** [bats-core/bats-core#245]
Attempting to read a multi-line here document seems to fail on bats 1.1.0:

```
#!/usr/bin/env bats

@test "here document" {
read -r -d '' VAR << EOF
LINE1
LINE2
EOF
}
```

Output:

```
 ✗ here document
   (in test file test.bats, line 4)
     `read -r -d '' VAR << EOF' failed
```

It seems it's the `-d ''` argument on `read` that upsets things. Remove that and it works except read stops at the first line (as it should, though not what we want). I wonder if it's somehow related to stdin issue #197 ?

**Comment by martin-schulze-vireso** [comment]
This seems to be unrelated to bats. The read command itself exits with 1, which fails the test. That is also expected: The delimiter is not encountered in the string, so read runs until EOF and returns non-zero as indicated by the documentation:

> The return code is zero, unless end-of-file is encountered, [...]

**Comment by Ian2020** [comment]
Sorry for the trouble, I should have investigated further first :-)
