### ISSUE TITLE
declaring variables results in unbound variables

### ISSUE THREAD

**Issue by thorstenkampe** [bats-core/bats-core#248]
Consider the following test suite
```bash
test_var=5
test_array=(value1 value2)
test_assoc_array=([key1]=value1 [key2]=value2)

@test test_var {
    [[ $test_var                 == 5 ]]
}

@test test_array {
    [[ ${test_array[1]}          == value2 ]]
}

@test test_assoc_array {
    [[ ${test_assoc_array[key1]} == value1 ]]
}
```
Result:
```
 ✓ test_var
 ✓ test_array
 ✗ test_assoc_array
   (in test file test.bats, line 22)
     `[[ ${test_assoc_array[key1]} == value1 ]]' failed
```
That's expected because we have to declare associative arrays in bash...
```bash
declare -A test_assoc_array
```
...still the same error

No idea what the issue is so we add...
```
shopt -os nounset
```
```
 ✓ test_var
 ✓ test_array
 ✗ test_assoc_array
   (in test file test.bats, line 22)
     `[[ ${test_assoc_array[key1]} == value1 ]]' failed
   /tmp/bats.18888.src: line 22: key1: unbound variable
```
The key definitely exists but does the associative array exist? Declaring integer variables and non-associative arrays doesn't hurt so we add
```
declare -i test_var
declare -a test_array
```
Now all three tests fail...
```
 ✗ test_var
   (in test file test.bats, line 14)
     `[[ $test_var                 == 5 ]]' failed
   /tmp/bats.18966.src: line 14: test_var: unbound variable
 ✗ test_array
   (in test file test.bats, line 18)
     `[[ ${test_array[1]}          == value2 ]]' failed
   /tmp/bats.18972.src: line 18: test_array[1]: unbound variable
 ✗ test_assoc_array
   (in test file test.bats, line 22)
     `[[ ${test_assoc_array[key1]} == value1 ]]' failed
   /tmp/bats.18977.src: line 22: key1: unbound variable
```

**Comment by sublimino** [comment]
I can't say I use associative arrays in Bash so I don't instinctively know what's afoot here. Help appreciated if anybody else would like to investigate? :pray:

**Comment by d630** [comment]
They fail, because they have been declared local to `bats_evaluate_preprocessed_source()` (which runs before `bats_perform_test()`), I believe

Test with `echo "${FUNCNAME[@]}" >&7` and then run `bats file 7>/dev/tty`

**Comment by d630** [comment]
use `declare -g -A` etc.

**Comment by thorstenkampe** [comment]
`The -g option forces variables to be created or modified at the global scope, even when declare is executed in a shell function. `

I can confirm that the above solution works. I'm closing this issue.

**Comment by thorstenkampe** [comment]
Just a final note: I would advise to document the need to use `-g` when declaring a variable. It's not obvious to the user that declaring any kind of variable will result in a failure of a test that uses that variable. Especially because from the perspective of the user the variable is not declared within a function.

**Comment by sublimino** [comment]
Thank you for the insight @d630!

@thorstenkampe a PR to the README would be appreciated if you have the time :pray:
