### ISSUE TITLE
Line endings in ${lines[@]} not sanitized

### ISSUE THREAD

**Issue by thorstenkampe** [bats-core/bats-core#249]
Default line endings on different platforms are not stripped - making it hard to interact with native applications on Cygwin.

Consider the following test suite
```
@test 'Cygwin Python' {
    run python3.8 -m this
    [[ ${lines[0]} == 'The Zen of Python, by Tim Peters' ]]
}

@test 'Windows Python' {
    run python -m this
    [[ ${lines[0]} == 'The Zen of Python, by Tim Peters' ]]
}
```
Result:
```
 ✓ Cygwin Python
 ✗ Windows Python
   (in test file test.bats, line 8)
     `[[ ${lines[0]} == 'The Zen of Python, by Tim Peters' ]]' failed

2 tests, 1 failure
```
By the way: unless you already know what the issue is, `bats` gives you no aide for debugging. I suspected `\r\n` line endings from Windows Python. Let's sanitize [explicitly](https://superuser.com/a/1215968)
```
@test 'Windows Python' {
    run python -m this
    [[ ${lines[0]%[[:cntrl:]]} == 'The Zen of Python, by Tim Peters' ]]
}
```
...works...
```
 ✓ Cygwin Python
 ✓ Windows Python

2 tests, 0 failures
```

**Comment by sublimino** [comment]
Hello @thorstenkampe, thanks for the code in this report. I think stripping line endings would be a very wide breaking change to existing test suites. While this is annoying to debug (as are all control characters!) I don't know how we can address this. 

What would be your ideal resolution here, a change to Bats' behaviour under Windows to strip trailing `\r\n`?

**Comment by thorstenkampe** [comment]
@sublimino from what I can see, bats is already stripping `\n` line endings. Otherwise testing...
```
[[ ${lines[0]} == text ]]
```
...could never succeed. In my opinion, Bats should be platform agnostic and strip all kinds of line endings (`\r\n`, `\n`, `\r`). The code for all output lines could be as simple as
```bash
lines=("${lines[@]%[[:cntrl:]]}")
```

**Comment by rolweber** [comment]
Maybe define a flag to switch between current and future behavior?
That should address compatibility concerns.

**Comment by dimo414** [comment]
Can you see if #289 helps? I haven't tried it with `\r\n` but this is yet another example of problems with the existing `run` implementation.

Perhaps it would be worth simply scrapping `run` (leaving it as-is and deprecating it) and introducing a new function with cleaner, more usable semantics.

**Comment by thorstenkampe** [comment]
My solution in the end was to implement a helper module and load that in my unit test. Right now the helper module has just one function that platform agnostic removes the line endings:
```bash
function remove_line_endings {
    # * get rid of Windows line endings (https://superuser.com/a/1215968)
    #   https://stackoverflow.com/questions/12744031/how-to-change-values-of-bash-array-elements-without-loop
    lines=("${lines[@]%[[:cntrl:]]}")
}
```

**Comment by martin-schulze-vireso** [comment]
I tried to implement this as a flag for `run` but decided against it. There does not seem to be widespread demand, there is a workaround and making users, who don't use it, pay for this does not seem worth it for me.

The only thing I would want to consider is giving users a helping hand in finding the problem, as you said it took you quite a while to see. Maybe we can get bats-assert to add more detail for this case?
