### ISSUE TITLE
Consider adding pull request and issue templates and a CODEOWNERS file 

### ISSUE THREAD

**Issue by mbland** [bats-core/bats-core#25]
These might make it easier for people to file high-quality issues and PRs, and to automatically request a code review from the bats-core organization.

* https://github.com/blog/2111-issue-and-pull-request-templates
* https://help.github.com/articles/about-codeowners/

**Comment by btamayo** [comment]
On it!

**Comment by jasonkarns** [comment]
Have any PRs been created that don't include the necessary information? My experience with the templates is that they are mostly boilerplate that PR authors just need to delete every time they open a PR.

I'm fine with them if they solve a problem. But I don't think I've seen many or any PRs (or Issues) that are missing critical information for a template to address. If we do decide to use them, I would at least home they are super minimal and have just the core information we're looking for.

Regarding codeowners, are there sections of the code that we would attribute to different people?

**Comment by mbland** [comment]
Regarding your first question (Have any PRs been created...), not that I'm aware.

Regarding your second (CODEOWNERS), I wasn't thinking as much about attributing ownership to different people as automatically assigning reviewers. Not that clicking the "Reviewers" field isn't easy enough.

And regarding the boilerplate in general, I'm thinking of it as more of a gentle reminder to folks that they should look through the existing issues, possibly the [Bash CHANGES list][CHANGES].

[CHANGES]: https://tiswww.case.edu/php/chet/bash/CHANGES

I'm not pushing super-hard for these things, but it might be interesting to try them and see if they add value or become a PITA. Easy enough to remove them if the latter case plays out. And by way of example, here's the [go-script-bash .github templates][gsb].

[gsb]: https://github.com/mbland/go-script-bash/tree/master/.github

**Comment by jasonkarns** [comment]
> automatically assigning reviewers

Good point. I always forget about that feature since I was just thinking "get notified" which being a maintainer already covers.

> gentle reminder

cool. there's also `CONTRIBUTING.md` as the more subtle reminder. but also so subtle, it's also less useful :D

Might be worth checking bats' old issues for some common concerns and throwing together a wiki FAQ to reference as well?

**Comment by mbland** [comment]
Yeah, some sort of wiki FAQ/"Gotchas"/etc. documentation is probably a good idea. Good documentation in general is always a great thing—in fact, it's the biggest push I'm making at my new-ish job right now.

This touches on #12 and @sublimino's [style guide idea][] from #26 as well.

[style guide idea]: https://github.com/bats-core/bats-core/pull/26#discussion_r143354561

**Comment by btamayo** [comment]
We can also tag requests with `help-wanted` label and `good-first-issue` to encourage contributors! :)

**Comment by jasonkarns** [comment]
I think the major items were codeowners and PR template, which were added in #1

FAQ/gotchas and style guide can be opened in separate issues or PRs
