### ISSUE TITLE
Is it kosher to skip in setup/teardown?

### ISSUE THREAD

**Issue by jchampio** [bats-core/bats-core#250]
We have a suite that we'd like to skip entirely if some condition is not met on the developer's machine. So rather than put an identical conditional `skip` in every test, we're putting that `skip` call at the beginning of the `setup()` function. The only problems with that are
- it doesn't appear to be documented, and
- we have to also `skip` in `teardown()` in the same way.

Is this a supported use case, and is the "skip-both-setup-and-teardown" method the preferred way to do it?

**Comment by sublimino** [comment]
One pattern I've used here (that I'm sure I got from somebody else!) is:

```bash
# _helper.bash

_global_setup() {                                                                          
  [ ! -f "${BATS_PARENT_TMPNAME}.skip" ] || skip "skip remaining tests"                    
}                                                                                          
                                                                                           
_global_teardown() {                                                                       
  if [ ! -n "${BATS_TEST_COMPLETED}" ]; then                                               
    touch "${BATS_PARENT_TMPNAME}.skip"                                                    
  fi                                                                                       
}                                                                                        
```

```bash
# some_test.bats

load '_helper'

setup() {
  _global_setup
}

teardown() {
  _global_teardown
}

@test "something" {
   # ...
```

While this isn't exactly your use case (as it will "fail fast" and skip every remaining suite if set) it's based on the same idea. 

So in this case the teardown's `touch "${BATS_PARENT_TMPNAME}.skip"` skips the remaining tests.

So yes, it's undocumented, but I think your approach is fine :grinning:. If you'd like to contribute your approach to the README or add some clarification there it would be appreciated!
