### ISSUE TITLE
GitHub Action

### ISSUE THREAD

**Issue by mig4** [bats-core/bats-core#251]
Hi :wave:  I've created a [GitHub Action](https://help.github.com/en/github/automating-your-workflow-with-github-actions/about-actions) to setup BATS to be able to run BATS tests in CI [workflows](https://help.github.com/en/github/automating-your-workflow-with-github-actions). It's available [here](https://github.com/mig4/setup-bats).

Would this be something that you'd be interested in having under the https://github.com/bats-core group? I'm happy to move it there if there's an interest.

**Comment by sublimino** [comment]
Thank you @mig4! This looks great, and is certainly something we'd be interested in. I have a few other bits to merge first -- if anybody else has time for a review of the action it will help to move the process along faster :pray:

**Comment by virgilwashere** [comment]
I'll have a look.  I wrote the wiki entries on installing for Travis 😃

**Comment by mig4** [comment]
Cool, thanks guys, let me know if I can help/explain/improve something :smile: 

BTW one project where I've a PR open for using this is [kubectl-neat](https://github.com/mig4/kubectl-neat/tree/5-auto-build-test) - [workflow runs here](https://github.com/mig4/kubectl-neat/actions) (in case you want to see it in action).

Also one thing to note is that I followed GitHub's [versioning guide](https://github.com/actions/toolkit/blob/master/docs/action-versioning.md) for actions which means the code that actually runs when this action is invoked is in [releases/v1](https://github.com/mig4/setup-bats/tree/releases/v1) branch, although I merged things back into master so it should be up to date as well, it just isn't executable.

**Comment by jasonkarns** [comment]
re: GitHub's [versioning guide](https://github.com/actions/toolkit/blob/master/docs/action-versioning.md)

I can't believe they're suggesting to force-overwrite tags repeatedly as part of their recommended release process. :(

**Comment by jasonkarns** [comment]
@mig4 

> master so it should be up to date as well, it just isn't executable.

Why should master not be executable if v1 has been merged into it? I know it's not recommended for users to pin to master, but that should still be _possible_, right? How else would users test and verify the current HEAD of the action works before it has a release/tag?

Aside from that, the action looks 👍 to me. (Haven't tested, just a cursory review.)

**Comment by mig4** [comment]
@jasonkarns 

> I can't believe they're suggesting to force-overwrite tags repeatedly as part of their recommended release process. :(

yeah it's a bit weird but that's why I also tagged commits with full vX.Y.Z semver tag and only overwrote the vX one so one can refer to "latest v1", etc. That way it feels a bit better for me, but there probably should be a better mechanism for version lookup/aliases.

> Why should master not be executable if v1 has been merged into it? I know it's not recommended for users to pin to master, but that should still be _possible_, right? How else would users test and verify the current HEAD of the action works before it has a release/tag?

Bad choice of words on my part, I cherry-picked the relevant changes from v1 into master (rather than merged), apart from the first commit in v1 which included contents of `node_modules` thereby making it executable. This was the approach suggested by the versioning guide, but I see they changed it a couple of days ago.

I think the original idea was that if you had a breaking change you'd branch off to `v2` first and create that "rolling" `v2` tag for it which would avoid the need from binding to master, but I see it may be a bit of a nuisance so I can make master executable too if that'd be preferred?

**Comment by kolyshkin** [comment]
Would be nice for someone to pick it up and move it to under this org, as https://github.com/mig4/setup-bats seems to be no longer maintained :(

**Comment by martin-schulze-vireso** [comment]
Seeing that the other one seems to have much more stars, I'd prefer to preserve its Interface. Then again, I am no user of either and likely won't have the capacity to contribute to this. So if you are willing to support this, then go for it!

**Comment by martin-schulze-vireso** [comment]
Closing this, since we now have https://github.com/bats-core/bats-action
