### ISSUE TITLE
Getting strange output when running bats with git, or trying to use >&2 with any command

### ISSUE THREAD

**Issue by byronaltice** [bats-core/bats-core#252]
If I run bats with any code outside a test block, even if I redirect to stderr, the output gets displayed twice.

example script: 
```
git checkout master >&2
echo testing >&2
@test "hey" {
  [[ true == true ]]
}
```

produces this output:

> Already on 'master'
> testing
> Already on 'master'
> testing
>  ✓ hey

I've tried a couple things here... if I do 1>&2, same result except that it seems to add some of the output of ls, even though I'm not calling ls anywhere:

> M       config.xml
> M       package.json
> M       src/app/services/update/version.ts
> Already on 'master'
> Your branch is up to date with 'o/master'.
> testing
> M       config.xml
> M       package.json
> M       src/app/services/update/version.ts
> Already on 'master'
> Your branch is up to date with 'o/master'.
> testing
>  ✓ hey

If I change it to 1>/dev/null, I get this:

> Already on 'master'
> Already on 'master'
>  ✓ hey
> 
> 1 test, 0 failures

So at least this way I can ignore the output from certain commands, but git is still an issue.

**Comment by sublimino** [comment]
Hello @byronaltice. I think the answer is in the [README](https://github.com/bats-core/bats-core#writing-tests):

> Each Bats test file is evaluated n+1 times, where n is the number of test cases in the file. The first run counts the number of test cases, then iterates over the test cases and executes each one in its own process.

There has been discussion of a global before_test hook but it's not implemented. Personally, I use a `_helper.bats` file with functions in, and I source that in a wrapped `make test` job too, so I can perform global setup and teardown with the same set of functions as the tests use themselves.

You could also perhaps move the code into a test so the return code can be asserted.

**Comment by martin-schulze-vireso** [comment]
There has been no response on this for close to a year.
