### ISSUE TITLE
Output from "run" is not shown but everything else is

### ISSUE THREAD

**Issue by kaysond** [bats-core/bats-core#257]
I'm not sure if this is deliberate or not, but when a test fails, all of the output from within a test is shown, except for whatever is `run`. It seems odd to me that this particular output is excluded. I can get around it by a for loop around `echo ${lines}`, but its annoying to have to do that... Is there an option I'm missing?

**Comment by martin-schulze-vireso** [comment]
Yes, this is intended. It helps keeping the log of longer tests clean. The canonical usage is together with the assert libraries, which will only print the latest `run`'s output on failure of the assert.

As an example with run:
```
@test "test many commands" {
    run first_command
    assert_success
    run second_command
    assert_success
}
```
and without:
```
@test "test many commands" {
    first_command
    second_command
}
```

When second_command fails, we would see the output from first_command in the logs too. With `run` we will only see second_command's output, thus giving a much shorter log.

**Comment by kaysond** [comment]
This is an old issue, so I'm not 100% sure, but if I remember correctly, my issues was that none of the `run`'s showed any output. So for example, in your first example, there would just be no output except from the second `assert_success`.

**Comment by martin-schulze-vireso** [comment]
Yeah, that is exactly what I described above as the intended behavior.

**Comment by kaysond** [comment]
> which will only print the latest `run`'s output on failure of the assert.

> With `run` we will only see second_command's output, thus giving a much shorter log.

This is not the same as what I described.

For example:
```
@test "run ls on nonexistent dir" {
    run ls /asdf
    [ "$status" -eq 0 ]
}
```

Returns
```
administrator@fserver:~$ bats test.bats
 ✗ run ls on nonexistent dir
   (in test file test.bats, line 3)
     `[ "$status" -eq 0 ]' failed with status 2

1 test, 1 failure
```

What I really want to see here is the output of `ls /asdf`. But by default it doesn't show it. If however, I add 
`echo "${lines[@]}"` after the `run` but before the assert, then my output looks like:
```
administrator@fserver:~$ bats test.bats
 ✗ run ls on nonexistent dir
   (in test file test.bats, line 4)
     `[ "$status" -eq 0 ]' failed with status 2
   ls: cannot access '/asdf': No such file or directory

1 test, 1 failure
```
which is what I would like

**Comment by martin-schulze-vireso** [comment]
Okay, that was a bit unclear in my part.

By assert I specifically meant commands like assert_success or assert_output from the asserts library, not arbitrary userwritten checks. The behavior is by design, if you want to have unconditional output, you can omit run. See the "when not  to use run" section in the readme.

**Comment by kaysond** [comment]
Ah that is the missing link. Thanks!
