### ISSUE TITLE
Publish new release so brew formula is up to date

### ISSUE THREAD

**Issue by simeg** [bats-core/bats-core#262]
I'd like to use the `-j` flag for utilizing `parallel` when running my tests. This requires the latest version which is not available on brew.

If you publish a new release here on GitHub I can make a PR to [the bats-core formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/bats-core.rb).

Thanks.

**Comment by dimo414** [comment]
See https://github.com/bats-core/bats-core/issues/266

**Comment by simeg** [comment]
Awesome, thanks! Closing this now.
