### ISSUE TITLE
Release bats 1.2 and subsequently 1.2.1

### ISSUE THREAD

**Issue by sublimino** [bats-core/bats-core#266]
> 1.1 was released 2018-07-08

see [releasing guide](docs/releasing.md).

- [x] update changelog
- [x] update version numbers (code, package.json)
- [x] update wiki (no entries @sublimino could find)
- [ ] update man page (man/bats.7)
- [x] move [roadmap](https://github.com/bats-core/bats-core/projects/4#card-32105912) into 1.3
- [x] cut release 
    - [x] git tag 1.2
    - [x] create release (any automation? cc @jasonkarns anything to add here please?)

> some bugs were found in 1.2, and 1.2.1 is now the release that will be pushed downstream. Restart process!

- [x] update changelog
- [ ] remove banner in README, then re-add it with the new version (step missed in v1.2.1)
- [x] run `contrib/release.sh --patch 1` (or `--major 2`, `--minor 3` to bump those semver parts etc)
- [ ] verify roadmap project and issues

post-release:
- [ ] update docker images tags (`bats-core:1`, `:v1, 1.2, v1.2, 1.2.1, v1.2.1`) and push to Docker Hub
- [ ] publish to npm (@jasonkarns)
- [ ] publish to homebrew
- [ ] publish to Alpine
- [ ] publish to Gentoo
- [ ] publish to RH
- [ ] announce to https://gitter.im/bats-core/bats-core
- [ ] notify any other distributors (?)

**Comment by fwip** [comment]
Are there any tasks on the above list that you'd especially like to see pull requests for?

**Comment by sublimino** [comment]
@fwip thanks for asking! If you'd like to bump any version numbers or docs in a PR that will be a useful start : D Feel free to PR any scripts you build if you want too :pray: 

Then @jasonkarns and I are thinking about general release and test automation, but will probably just do as much as possible manually for this release.

**Comment by sublimino** [comment]
I will be undertaking this release today, please stand by! /cc @jasonkarns

**Comment by sublimino** [comment]
v1.2.0 has been released : ] 

- https://github.com/bats-core/bats-core/commit/73b8d2f95513207b319efe34685553b75c0b214e
- https://github.com/bats-core/bats-core/releases/tag/v1.2.0

I'll leave it for a few days before pushing out to other consumers in case of error on my behalf :pray: 

The automation scripts built while releasing this are in https://github.com/bats-core/bats-core/pull/284

**Comment by vainikkaj** [comment]
Congrats for the new release. :partying_face: 
Great to see that this project is still under active development.

Are there any issues preventing uploading new version to npm?

**Comment by sublimino** [comment]
Thanks for asking @vainikkaj  : ] Outstanding issues:

- https://github.com/bats-core/bats-core/pull/302
- https://github.com/bats-core/bats-core/issues/307

I think we can probably release 1.2.1 with the just the first issue fixed, #307 breaks OSX so there's a little work to be done there that I won't be able to address for a week or two I fear, but the workaround is to use `homebrew` to install coreutils. PRs always welcome if anybody wants to address it :pray:

**Comment by dmytri** [comment]
Any plan to publish 1.2 to npm?

**Comment by sublimino** [comment]
@dmytri I've had a few weeks off due to external cirucmstances, I'd like #307 closed via #312 to release `1.2.1`, or if @jasonkarns has bandwidth to do the release we could cut and publish `1.2.1` now and move #307 to `1.2.2`. Time is my constraint at the moment so would welcome opinion 🙏

**Comment by dmytri** [comment]
It would be great to get whatever is stable no released to npm, as the current version there is 1.1.0, which is two years old and quite different that the current version

**Comment by sublimino** [comment]
#312 was merged last weekend and there don't appear to be any problems with it :tada: If anybody on OSX would like to verify that `master` works as expected without gnu coreutils installed (the fix that was in #312), that would be a great help.

Then the next job is to release `1.2.1`, which I will try to do this weekend, then we can push `1.2.1` to npm : ]

**Comment by sublimino** [comment]
I've just tagged and released `v1.2.1`, which should be suitable for an LTS release.

[Docker Hub](https://hub.docker.com/r/bats/bats/tags) has been updated for tags `v1.2.1` and `1.2.1`. I'm currently on holiday so not able to respond quickly if this release causes problems, so I'll avoid pushing `:latest` and `:v1` until I'm back next week  : ] (and that will conclude part of https://github.com/bats-core/bats-core/issues/144)

Next up is pushing to NPM, and distributions. @jasonkarns if you're happy can you release to NPM please?

/cc @bats-core/bats-core

**Comment by jbergstroem** [comment]
> Next up is pushing to NPM, and distributions. @jasonkarns if you're happy can you release to NPM please?

It would be great if 1.2.x could be pushed to npm for `-j` support (among other things).

**Comment by dmytri** [comment]
would be great to have 1.2.x on npm, @jasonkarns, if I can help in anyway let me know. npm is the easiest way to install bats in ci/cd, i.e travis-ci, and also to make sure all devs have the same version, regardless of OS.

**Comment by simeg** [comment]
cc @bats-core, any chance anyone could find some time to push `1.2` to NPM? Seems like we're a bunch that would be very happy about it!

**Comment by sublimino** [comment]
Hi @simeg, @jasonkarns is looking to push this to NPM sometime this week : ]

**Comment by Sineaggi** [comment]
Would love to the the `latest` tag in docker updated.

**Comment by martin-schulze-vireso** [comment]
Updates are automatic with each release again, thanks to Github Actions.
