### ISSUE TITLE
`load` doesn't source

### ISSUE THREAD

**Issue by rico-chet** [bats-core/bats-core#268]
According to the readme https://github.com/bats-core/bats-core/blame/master/README.md#L319, `load` sources the script addressed, but apparently it's not the case (at least not as documented).

I added a couple tests: https://github.com/bats-core/bats-core/compare/master...rico-chet:test-load-declared-var?expand=1
which run as follows:
```
❯ $(which bats) load.bats
 ✓ calling a loaded helper
 ✓ load supports plain variables
 ✗ load supports constants
   (in test file load.bats, line 14)
     `[ -n "${constant}" ]' failed
 ✗ load supports integer variables
   (in test file load.bats, line 19)
     `[ -n "${integer_var}" ]' failed
4 tests, 2 failures
```

Note that `declare` changes scope of the symbol, as mentioned in the `bash` docs: https://www.tldp.org/LDP/abs/html/declareref.html, so it seems like the `load`ed file is interpreted in context of a function, which is not exactly `source`-ing as users understand it.

My guess is that docs need to be fixed to mention this shortcoming.

**Comment by dimo414** [comment]
Tale a look at the [implementation](https://github.com/bats-core/bats-core/blob/118391d/libexec/bats-core/bats-exec-test#L43), perhaps you can contribute some improved docs? Personally I find `load`'s behavior really unintiutive, and just use `source "${BATS_TEST_DIRNAME}/[whatever]"`.

**Comment by dimo414** [comment]
I actually just sent PR #282; hopefully that will help you.

**Comment by sublimino** [comment]
FYI @dimo414 and @rico-chet there is another extension to this proposal in #27 — your thoughts welcome on the implementation and/or any impact to your test suite in https://github.com/bats-core/bats-core/compare/master...rico-chet:test-load-declared-var?expand=1, I'll look to get that PR merged in the next few weeks.

**Comment by rico-chet** [comment]
Well, I took a look but failed to see how it addresses the fact that one cannot declare integers or constants to DRY when using `load`. It still `source`s in context of a separate function and documentation still doesn't reflect this.

**Comment by sublimino** [comment]
OK thanks for checking it out : ] If you can suggest a proposed solution or have the time to submit a docs update, I'll prioritise merging it :pray:
