### ISSUE TITLE
Agregate other bats libs under the bats-core org

### ISSUE THREAD

**Issue by luisdavim** [bats-core/bats-core#269]
It wuld make it easier to find bats libraries like https://github.com/vincent-zurczak/detik if they where all under the same org, we should reach out to the developers of those libraries and propose that they migrate them to the bats-core github org.

**Comment by luisdavim** [comment]
this might be a duplicate of https://github.com/bats-core/bats-core/issues/44 but what I'm proposing here is to move the repos all under the same org os the scope is a bit different.

**Comment by sublimino** [comment]
That project looks great, and I wouldn't be averse to it changing orgs if that was desirable for @vincent-zurczak 

We are also going to be looking for maintainers here if developers of any bats libs wished to join.

/cc @bats-core/bats-core

**Comment by luisdavim** [comment]
Yeah, there are other projects like https://github.com/jasonkarns/bats-mock that I think add great value to bats and would make sense to host under the same org for better visibility.

**Comment by vincent-zurczak** [comment]
Hi,

I am not closed to moving the project in this organization.
However, if this is just a matter of visibility, we could also create a section in the README file listing libraries and projects, or even companies, using BATS.

Moving the project to an organization increases its chances of being maintained for a longer period. On the other hand, I do not think I will be able to contribute to BATS directly, unless I find a bug that affects my work. I will try to maintain the DETIK project but cannot promise I will be able to do more.

We use the same license.
If it is OK for you, I agree to move the project here and join the organization. I will update the (c) owners and I suggest we rename the project into **bats-detik**. I'd rather keep the "detik" part as there are predefined variables that include it in their names. Keeping them will avoid users to update the tests. What do you think?

**Comment by sublimino** [comment]
> If it is OK for you, I agree to move the project here and join the organization

That sounds awesome, yes please :pray: 

> I will update the (c) owners and I suggest we rename the project into bats-detik. I'd rather keep the "detik" part as there are predefined variables that include it in their names. Keeping them will avoid users to update the tests. What do you think?

Totally sensible to keep the same name, and you're still the owner of that project so the name's your choice. 

1. We'll add you to the org (cc @btamayo)
2. We migrate `bats-detik` into `bats-core`
3. Once you're in, we'll add an "other projects" section to the README with any other projects:
	- @jasonkarns's https://github.com/jasonkarns/bats-assert-1 and https://github.com/jasonkarns/bats-support
	- https://github.com/ztombol/bats-file (still compatible? Requires review)
	- https://github.com/ztombol/bats-docs (still relevant? Requires review)
	- https://github.com/grayhemp/bats-mock (as per https://github.com/bats-core/bats-core/issues/147)
4. The discussion on loading libraries etc will continue in https://github.com/jasonkarns/bats-assert-1/issues/28

**Comment by jasonkarns** [comment]
@sublimino I had planned to do some quick cleanups around the bats helpers that @ztombol and I had been collaborating on. That clearly hasn't happened, so I'm 👍 to just transition them into the org and work can continue here.

**Comment by jasonkarns** [comment]
bats-support and bats-assert-1 have been moved:

https://github.com/bats-core/bats-assert-1
https://github.com/bats-core/bats-support

but bats-assert-1 needs renamed. the -1 suffix needs dropped

**Comment by vincent-zurczak** [comment]
Hi,

You have forked the project into the organization.
Wouldn't it be better to transfer the original project here. There is an option **Transfer ownership** in the repository's settings. You can do that as soon as you are a member of the target organization.

**Comment by vincent-zurczak** [comment]
Please, forget my previous message.
I though you were the original owner of the forked projects.

I will wait to be added in the organization before moving and renaming the project. Thanks.

**Comment by sublimino** [comment]
That's correct @vincent-zurczak — we've got a funny permissions set up on the org that we're fixing, as soon as that's done I'll add you in, hopefully today. Then a "transfer ownership" is the best route as you identified.

Thanks for bearing with me : ]

**Comment by vincent-zurczak** [comment]
Project moved. :+1:   
Thank you for welcoming me in the organization.

**Comment by sublimino** [comment]
Thanks @vincent-zurczak, welcome! I've raised the README.md update PR here in case anybody has further libraries to suggest for addition?

https://github.com/bats-core/bats-core/pull/270/files#diff-04c6e90faac2675aa89e2176d2eec7d8R473

**Comment by jasonkarns** [comment]
@sublimino I also have https://github.com/jasonkarns/bats-mock but I haven't done a comparison yet between it and @grayhemp's

**Comment by sublimino** [comment]
@jasonkarns integrated your change :pray: — if anybody wants to compare the two `bats-mock` libraries and add any wording please do : ]

**Comment by sublimino** [comment]
Thanks all, merged in #270
