### ISSUE TITLE
Commenting out test cases via here-doc confuses bats-core

### ISSUE THREAD

**Issue by Vampire** [bats-core/bats-core#277]
If you comment out test cases with a here-doc like
```bash
: <<EOC
@test 'to be ignored for now' {
}
EOC
```
this greatly confuses bats-core.
As far as I have seen from a very quick look, you pre-process the test file line-wise.
So every line that looks like a test, even if just part of a multi-line string or here-doc will be considered a test case and confuse bats-core later on.

**Comment by dimo414** [comment]
What's the motivation for this unusual syntax? If you're trying to constrain which tests run use the `--filter` argument. Heredocs don't _really_ comment code out, and this pattern could easily trigger side effects or (as in this case) break things.

**Comment by Vampire** [comment]
It's not really unusual to comment out a block of code in a bash script
How do you define "really comment out code"?
A comment in some code changes the commented lines from being code to being only text
And that is exactly what this construct does.
It is so-to-say a block comment in bash scripting.

This pattern only triggers side effects if something is not treating the file correctly.
For example as in bats case where the file is parsed line by line instead of by a parser.

Actually I was not aware of the `--filter` parameter which would probably have worked in my case too.
I simply used line comments instead as work-around.

**Comment by dimo414** [comment]
A heredoc isn't a comment though. The contents will be evaluated like a `"`-ed string, and can trigger side-effects.

```
: <<EOC
@test 'to be ignored for now' {
  dir=$(mkdir foo)
}
EOC
```

This would still create a `foo` directory, even though it's "commented out".

**Comment by Vampire** [comment]
Sure, but I simply knew my code has no such side effects.
If it could have or to slightly improve performance, you can simply disable parameter substitution using
```
​: <<'EOC'
@test 'to be ignored for now' {
  dir=$(mkdir foo)
}
EOC
```

**Comment by dimo414** [comment]
Yep, but it's still not a comment :) I'm sure there are improvements that could be made to the pre-processor, but short of actually implementing a custom grammar and parser it's hard to imagine supporting syntax like this.

**Comment by martin-schulze-vireso** [comment]
@Vampire What is it you are actually trying to achieve here? Do you want to disable specific tests in a file?

**Comment by Vampire** [comment]
Yes, my actual use-case was disabling a test temporarily and yes as said before, `--filter` would have worked for me if I would have been aware of it.

But that's not the point.
A line that is part of a multi-line string or here-doc that looks like the start of a test majorly confused bats.
That is the point here. :-)

**Comment by martin-schulze-vireso** [comment]
@Vampire #349 relies on bash itself to do test registration, so it would work with your usecase. However, I'd be interested in what kind of filtering you want to apply? Commenting out a test seems to work more like: run all tests except this. Why doesn't `skip` work for you in this case?
