### ISSUE TITLE
Arithmetic expression causes early exit of function under bats, fine under bash

### ISSUE THREAD

**Issue by Ian2020** [bats-core/bats-core#299]
I'm running latest bats built from source today. Minimal test case:

```bats
#!/usr/bin/env bats

hello() {
  i=0
  echo "one"
  ((i++))    # <--- this causes early exit of function with mapfile test below, but only under bats
  echo "two"
}

@test "works" {
  result=($(hello))
  [ "${#result[@]}" = "2" ]
}

@test "using mapfile fails" {
  mapfile -t result < <(hello)
  [ "${#result[@]}" = "2" ]
}
```

As the comment above shows the arithmetic expression seems to cause the early exit of `hello`, leading to just "one" showing up in result - but only when using mapfile to read results into an array and only under bats. Running the exact same code under bash it all works:

```bash
#!/usr/bin/env bash

hello() {
  i=0
  echo "one"
  ((i++))    # <--- this causes early exit of function with mapfile, only under bats
  echo "two"
}

echo "works"
result=($(hello))
[ "${#result[@]}" = "2" ] || echo "fail"

echo "using mapfile works too"
mapfile -t result < <(hello)
[ "${#result[@]}" = "2" ] || echo "fail"
```

Using mapfile instead of `result=($(hello))` is recommended by shellcheck which is how I came across this situation in the first place. Is this a bats bug or have I missed something?

**Comment by dimo414** [comment]
`(( ... ))` fails if the result is `0`, this is typically used for conditionals, as in `if (( i )); then ...`. Since bats runs under `set -e` this will cause the run to fail.

Try `: $(( i++ ))` or `(( i++ )) || true` to suppress `set -e`'s behavior.

**Comment by Ian2020** [comment]
Ah thank you for the explanation and link, makes sense now. So all scripts tested by bats must behave themselves under `set -e` I guess, even if they don't explicitly set this option themselves.

**Comment by dimo414** [comment]
Yep, the README mentions this:

> Bats makes use of Bash's errexit (set -e) option when running test cases. If every command in the test case exits with a 0 status code (success), the test passes. In this way, each line is an assertion of truth.

but it's easy to miss :)
