### ISSUE TITLE
Get Travis running on PRs

### ISSUE THREAD

**Issue by dimo414** [bats-core/bats-core#3]
PR https://github.com/bats-core/bats-core/pull/2 (duplicated from https://github.com/sstephenson/bats/pull/231, which [passes on Travis](https://travis-ci.org/sstephenson/bats/builds/274590933)) didn't trigger a Travis build. Presumably Travis just needs to be pointed at this repo, since the [config](https://github.com/bats-core/bats-core/blob/master/.travis.yml) is already in place.

**Comment by btamayo** [comment]
Thanks for this @dimo414! I did create a note here: https://github.com/bats-core/bats-core/projects/2#card-4761498, but good to know to prioritize this.

**Comment by btamayo** [comment]
@dimo414 I updated travis so that it should pick up new PRs. I'll close this for now. :)
