### ISSUE TITLE
Write up Docker usage guide

### ISSUE THREAD

**Issue by sublimino** [bats-core/bats-core#30]
Placeholder - I intend to work on this in the coming weeks. 

- Basic usage
- Docker-y gotchas
- Extending from the base image
- `slim` vs `full` images
- Examples of running in various CIs

Any further topics?

**Comment by ntnn** [comment]
Rather than the generic `slim` and `full` image tags I'd rather see `posixly` (just bash and coreutils) and the default (based on posixly) with common tools. Stuff like `openssl` etc.pp. should be their own tags again.

**Comment by sublimino** [comment]
@ntnn OK, I'd venture that `slim` should `posixly` are the same, but that `slim` is the standard in the official Docker Hub images. We could well tag the same image with both, although that could be confusing messaging.

What common tools would you suggest for `default`? Personally after `coreutils` I usually need TLS so I'd be inclined to add `cacerts` to `full`.

Possibly:

| image name | contents | 
|--|--|
|`slim`/`posixly`| `bash`, `coreutils` |
|`default`| `slim` + some extras? |
|`full`| `default` + network tools (`cacerts`, `openssl` etc) |

**Comment by mbland** [comment]
I can't remember offhand...is `diff` automatically available or do you need to install `diffutils` as well? I know you have to install it explicitly on raw MSYS2, and don't have an Alpine image handy at the immediate moment.

**Comment by sublimino** [comment]
Alpine uses Busybox so there's a diff version there. This is a long list, so hidden behind `details`:

<details>
<pre>
bash-4.3# ls -l /usr/bin/                                                                     
total 176                                                                                     
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 [ -> /bin/busybox                    
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 [[ -> /bin/busybox                   
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 awk -> /bin/busybox                  
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 basename -> /bin/busybox             
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 beep -> /bin/busybox                 
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 blkdiscard -> /bin/busybox           
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 bunzip2 -> /bin/busybox              
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 bzcat -> /bin/busybox                
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 bzip2 -> /bin/busybox                
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 cal -> /bin/busybox                  
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 chvt -> /bin/busybox                 
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 cksum -> /bin/busybox                
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 clear -> /bin/busybox                
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 cmp -> /bin/busybox                  
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 comm -> /bin/busybox                 
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 cpio -> /bin/busybox                 
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 crontab -> /bin/busybox              
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 cryptpw -> /bin/busybox              
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 cut -> /bin/busybox                  
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 dc -> /bin/busybox                   
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 deallocvt -> /bin/busybox            
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 diff -> /bin/busybox                 
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 dirname -> /bin/busybox              
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 dos2unix -> /bin/busybox             
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 du -> /bin/busybox                   
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 dumpleases -> /bin/busybox           
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 eject -> /bin/busybox                
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 env -> /bin/busybox                  
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 expand -> /bin/busybox               
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 expr -> /bin/busybox                 
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 find -> /bin/busybox                 
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 flock -> /bin/busybox                
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 fold -> /bin/busybox                 
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 free -> /bin/busybox                 
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 ftpget -> /bin/busybox               
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 ftpput -> /bin/busybox               
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 fuser -> /bin/busybox                
-rwxr-xr-x   24 root     root         31480 Jun 22 23:25 getconf                              
-rwxr-xr-x   24 root     root         44792 Jun 22 23:25 getent                               
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 groups -> /bin/busybox               
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 hd -> /bin/busybox                   
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 head -> /bin/busybox                 
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 hexdump -> /bin/busybox              
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 hostid -> /bin/busybox               
-rwxr-xr-x   24 root     root         20552 Jun 22 23:25 iconv                                
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 id -> /bin/busybox                   
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 install -> /bin/busybox              
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 ipcrm -> /bin/busybox                
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 ipcs -> /bin/busybox                 
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 killall -> /bin/busybox              
lrwxrwxrwx    1 root     root            29 Jun 25 17:52 ldd -> ../../lib/ld-musl-x86_64.so.1 
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 less -> /bin/busybox                 
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 logger -> /bin/busybox               
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 lsof -> /bin/busybox                 
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 lsusb -> /bin/busybox                
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 lzcat -> /bin/busybox                
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 lzma -> /bin/busybox                 
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 lzopcat -> /bin/busybox              
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 md5sum -> /bin/busybox               
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 mesg -> /bin/busybox                 
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 microcom -> /bin/busybox             
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 mkfifo -> /bin/busybox               
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 mkpasswd -> /bin/busybox             
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 nc -> /bin/busybox                   
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 nmeter -> /bin/busybox               
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 nohup -> /bin/busybox                
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 nsenter -> /bin/busybox              
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 nslookup -> /bin/busybox             
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 od -> /bin/busybox                   
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 od -> /bin/busybox                            
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 openvt -> /bin/busybox                        
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 passwd -> /bin/busybox                        
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 patch -> /bin/busybox                         
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 pgrep -> /bin/busybox                         
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 pkill -> /bin/busybox                         
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 pmap -> /bin/busybox                          
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 printf -> /bin/busybox                        
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 pscan -> /bin/busybox                         
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 pstree -> /bin/busybox                        
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 pwdx -> /bin/busybox                          
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 readlink -> /bin/busybox                      
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 realpath -> /bin/busybox                      
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 renice -> /bin/busybox                        
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 reset -> /bin/busybox                         
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 resize -> /bin/busybox                        
-rwxr-xr-x  108 root     root         75528 Apr 20 12:23 scanelf                                       
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 seq -> /bin/busybox                           
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 setkeycodes -> /bin/busybox                   
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 setsid -> /bin/busybox                        
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 sha1sum -> /bin/busybox                       
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 sha256sum -> /bin/busybox                     
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 sha3sum -> /bin/busybox                       
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 sha512sum -> /bin/busybox                     
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 showkey -> /bin/busybox                       
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 shuf -> /bin/busybox                          
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 smemcap -> /bin/busybox                       
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 sort -> /bin/busybox                          
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 split -> /bin/busybox                         
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 strings -> /bin/busybox                       
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 sum -> /bin/busybox                           
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 tac -> /bin/busybox                           
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 tail -> /bin/busybox                          
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 tee -> /bin/busybox                           
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 telnet -> /bin/busybox                        
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 test -> /bin/busybox                          
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 tftp -> /bin/busybox                          
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 time -> /bin/busybox                          
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 timeout -> /bin/busybox                       
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 top -> /bin/busybox                           
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 tr -> /bin/busybox                            
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 traceroute -> /bin/busybox                    
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 traceroute6 -> /bin/busybox                   
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 truncate -> /bin/busybox                      
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 tty -> /bin/busybox                           
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 ttysize -> /bin/busybox                       
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 udhcpc6 -> /bin/busybox                       
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 unexpand -> /bin/busybox                      
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 uniq -> /bin/busybox                          
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 unix2dos -> /bin/busybox                      
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 unlink -> /bin/busybox                        
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 unlzma -> /bin/busybox                        
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 unlzop -> /bin/busybox                        
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 unshare -> /bin/busybox                       
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 unxz -> /bin/busybox                          
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 unzip -> /bin/busybox                         
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 uptime -> /bin/busybox                        
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 uudecode -> /bin/busybox                      
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 uuencode -> /bin/busybox                      
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 vi -> /bin/busybox                            
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 vlock -> /bin/busybox                         
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 volname -> /bin/busybox                       
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 wc -> /bin/busybox                            
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 wget -> /bin/busybox                          
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 which -> /bin/busybox                         
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 whoami -> /bin/busybox                        
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 whois -> /bin/busybox                         
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 xargs -> /bin/busybox                         
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 xzcat -> /bin/busybox                         
lrwxrwxrwx    1 root     root            12 Jun 25 17:52 yes -> /bin/busybox                           

</pre>
</details>

**Comment by btamayo** [comment]
@sublimino As you intend to work on this, I added you as the assignee. That alright? :)

**Comment by sublimino** [comment]
@btamayo very much so, thanks :smile:

**Comment by jasonkarns** [comment]
@sublimino I wouldn't mind adding git-crypt to this repo so the docker credentials could be versioned in the repo

https://github.com/AGWA/git-crypt

**Comment by sublimino** [comment]
@jasonkarns I use it in private repos but haven't done so in Open Source. Worth noting for all:

> Although git-crypt protects individual file contents with a SHA-1 HMAC, git-crypt cannot be used securely unless the entire repository is protected against tampering (an attacker who can mutate your repository can alter your .gitattributes file to disable encryption). If necessary, use git features such as signed tags instead of relying solely on git-crypt for integrity.

This basically means we have to ensure PRs don't alter the `.gitattributes` file.

Happy to use it here if others agree :)

**Comment by jasonkarns** [comment]
True. Though if the attributes file were tampered, it would still require someone with credentials to commit the decrypted version of the sensitive file(s) after the gitattributes tampering.

**Comment by jasonkarns** [comment]
FWIW, we may not have enough sensitive info to warrant git-crypt. Since what we're talking about so far is just a one-time addition of creds to travis env, yes?

Perhaps I jumped the gun on the git-crypt suggestion :D It's my go-to when I hear "pass sensitive creds out of repo".

**Comment by sublimino** [comment]
@jasonkarns I don't think it's jumping the gun - I agree these creds are better stored. So far the credentials we have (if @btamayo agrees):

- travis
- appveyor
- docker hub

There may be more CI infrastructure (packet.net for BSDs, for example).

Perhaps we could have a dedicated repo for secrets, minimising the risk of contributor PRs changing `.gitattributes`?

**Comment by btamayo** [comment]
@sublimino @jasonkarns git-crypt LGTM, although it does depend on git filters (which may or may not interfere with your git setup depending on how customized you have git).

For the entire-repo suggestion, keybase did release encrypted repos which kind of makes the PGP aspect somewhat more straightforward, although that depends on how comfortable you are with going through kb: https://keybase.io/blog/encrypted-git-for-everyone

**Comment by sublimino** [comment]
@btamayo I think the security guarantees of keybase repo sound good, but it's difficult to appraise with a hosted service. Happy enough with either.

If we need to take longer to decide on a solution I'd be happy to take the credentials via GPG so we can push 0.5.0 and dev to the Docker Hub from Travis builds :D

**Comment by btamayo** [comment]
@sublimino: In that case, would you mind passing me the creds (via keybase) to the docker hub user for `bats`? I want to try the encrypted Travis variable configs and how they would work against PRs :) 

https://keybase.io/btamayo

**Comment by sublimino** [comment]
@btamayo sure thing! Credentials sent via keybase chat from my phone. LMK if they need emailing instead and I'll do so when I get to my laptop

**Comment by schmunk42** [comment]
Simple builds can be done with "automated builds" on Docker Hub, it'll build a new image for every push and can be configured to build tagged images.

**Comment by mbland** [comment]
@sublimino Any thoughts about next steps on this?

**Comment by sublimino** [comment]
Usage guide updated and PR'd in #94 

I'd like to progress automating the push of an image to the Docker Hub. @btamayo did you get any further with the Travis configuration? I can progress that otherwise, and will manually push 1.0.1 for now

**Comment by mbland** [comment]
@sublimino Use https://cloud.docker.com/ instead; it's the new hotness. I used it for another project a few weeks ago; the images are available via https://hub.docker.com/ as well.

**Comment by mbland** [comment]
@sublimino Oh, and mind making us collaborators on the https://cloud.docker.com/ project once you do? 🙂

**Comment by schmunk42** [comment]
I won't recommand `cloud.docker.com`.

1. I wasn't able to tag images properly with a version, never got a response from support
2. Docker Cloud (orchestration) was abandoned with only a few weeks notice beforehand

DockerHub is not very flexible, but at least it works. But if you are already on Travis I'd recommend building images there, you can move it to another CI system more easily, if required some day.

**Comment by sublimino** [comment]
Added collaborators @btamayo and @mbland - could I have your Docker hub username please @jasonkarns?

Pushed v1.0.1 image to cloud.docker.com at https://cloud.docker.com/swarm/bats/repository/docker/bats/bats/tags

Demo: 

```
docker run bats/bats /opt/bats/test
```

Tags available: `:latest :1 :1.0 :1.0.1`

Congrats one and all, and thanks to everybody that contributed to get v1 over the line!

**Comment by sublimino** [comment]
@schmunk42 this is not an automated build, so we can still push images to wherever we need. Although it's also not in travis yet, so I pushed these images manually - which will change based on https://github.com/bats-core/bats-core/issues/30#issuecomment-396239735

Agreed the Docker Cloud deprecation wasn't well notified in advance, but if they deprecate the Docker hub... :boom:!

**Comment by jasonkarns** [comment]
@sublimino https://hub.docker.com/u/jasonkarns/

**Comment by jasonkarns** [comment]
@sublimino also, to carry on the conversation from before about sensitive messages, we can now create a team on keybase for this kind of thing.

**Comment by mbland** [comment]
I'm so confused. ☹️All's I know is that it was really easy to set up automated builds Docker Cloud. Here's the editing view for https://cloud.docker.com/swarm/mbland/repository/docker/mbland/custom-links/builds:

![docker-cloud-custom-links-automated-build-config](https://user-images.githubusercontent.com/301547/41235118-673de28a-6d64-11e8-99e9-324697d63268.png)

**Comment by sublimino** [comment]
@jasonkarns added to the project. Agreed on Keybase

@mbland automated builds require a linked github account, and mine is already linked to my personal account. We could create a new user to do this, but preference is probably to only push passing/tagged builds from Travis

**Comment by mbland** [comment]
Ah, I see, thanks.

**Comment by jasonkarns** [comment]
`bats` or `bats-core` for keybase team name? (I'm partial to bats, if picking one.)

@mbland @btamayo keybase usernames? https://keybase.io/jasonkarns (Got you, @sublimino )

**Comment by sublimino** [comment]
`bats` is my preference. Thanks @jasonkarns

**Comment by mbland** [comment]
I'm not on Keybase yet. Will have to look into it later. (Prepping a presentation a couple hours from now.) But FWIW, I'm down with `bats`.

**Comment by jasonkarns** [comment]
Keybase team `bats` created. @sublimino and @btamayo both added. Will add you, @mbland once you've joined. (We'll get a notice once you join and track/follow us, and we can add you at that point.)
