### ISSUE TITLE
update wikipedia "Unit Testing Frameworks: Shell" page to point to bats-core

### ISSUE THREAD

**Issue by joshrabinowitz** [bats-core/bats-core#303]
This looks like a useful list of unit testing frameworks.

Seems like the link for "bats-core" should replace the one for "bats" at

https://en.wikipedia.org/wiki/List_of_unit_testing_frameworks#Shell

**Comment by sublimino** [comment]
Would welcome this change from any established Wikipedia editor : ]

**Comment by joshrabinowitz** [comment]
updated: https://en.wikipedia.org/wiki/List_of_unit_testing_frameworks#Bash
Lets see what happens

**Comment by sublimino** [comment]
It's been accepted! Good job, thank you @joshrabinowitz  : ]

![image](https://user-images.githubusercontent.com/134117/82150656-cc437500-9850-11ea-940a-e0861b738093.png)
