### ISSUE TITLE
[wishlist] dynamic test registration

### ISSUE THREAD

**Issue by dimo414** [bats-core/bats-core#306]
It would be nice to be able to register test functions at runtime, in addition to the `@test` preprocessor behavior. Something like:

```shell
bats::register_test is_prime 2 true
bats::register_test is_prime 3 true
bats::register_test is_prime 4 false

is_prime() { .... }
```

#241 is closely related; it's possible implementing that would address this need. Alternatively, implementing this could be sufficient for users to construct their own parameterization on top. I'm not sure we need both features or not, but I can see them both being useful.

**Comment by aakropotkin** [comment]
Do you have an in progress branch for this, or are you open to contributions?
I'd like to take a crack at this but won't if you'd prefer to tackle it yourself.

**Comment by martin-schulze-vireso** [comment]
#349 is slowly coming along. It is the last blocker for the next release.

**Comment by aakropotkin** [comment]
Radical. No rush I just wanted to avoid stepping on any toes ✌️
