### ISSUE TITLE
Unpublished rpm .spec file

### ISSUE THREAD

**Issue by HarryMichal** [bats-core/bats-core#313]
Hi! First of all, thank you for working on this project!

Some time ago I was looking for a simple test framework for [Toolbox](https://github.com/containers/toolbox) and noticed that [Podman](https://github.com/containers/libpod) is using Bats. I tried it out and I knew it was what I was looking for!

Recently I realized that what I've been using is the original framework from which this fork was created. But the only package that is available on Fedora is version 0.4 which released in 2014.

I see you have a .spec file already. What's keeping you from publishing it? I'd like to help!

There is a new tool for closing the gap between upstream repositories and fedora's "dist-git" called [Packit](https://packit.dev/). They make it possible to maintain the .spec file in a GitHub repository and make Fedora updates from there using a GitHub app.

**Comment by sublimino** [comment]
It's only a lack of understanding TBH, I haven't packaged anything for RHEL etc before. We're looking to automate more of the release so your input is greatly appreciated!

The 1.2.0 release has some fixes coming for 1.2.1 which is why it's not released more widely yet, tracked in https://github.com/bats-core/bats-core/issues/266#issuecomment-626673821

**Comment by HarryMichal** [comment]
Ok. As I said, I'd like to help. I can setup an entry in fedora's [dist-git](https://src.fedoraproject.org) and try to automate it.

**Comment by sublimino** [comment]
`1.2.1` is released : ]  Please LMK what I can do to help the RPM release.

**Comment by HarryMichal** [comment]
I apologize for not following up on this. I was kinda overwhelmed by other things.

I wrote an email to the [maintainer](https://src.fedoraproject.org/user/piotrp) of the [bats package](https://src.fedoraproject.org/rpms/bats) in Fedora where I asked him if he would make me the maintainer of the package. When that is taken care of, I'd like to rename the package from `bats` to `bats-core` which will require going through Fedora's New Package [review process](https://fedoraproject.org/wiki/Package_Review_Process).

After that change is done, I'd like to package other repositories in this organization.

Ultimately, I'd like to set up some automatization with Packit, as mentioned in the original comment, and hand over the maintenance to you. But until that automatization is in place and working, I have no problem being the maintainer.

**Comment by martin-schulze-vireso** [comment]
@HarryMichal It has been a while. Can you share any progress report with us? Since this issue has become stale, I will close it for now. Please reopen it when you intend to continue work on it.
