### ISSUE TITLE
bats-exec-test: binary operator expected

### ISSUE THREAD

**Issue by Dentrax** [bats-core/bats-core#314]
Hey!

I just created simple `test.bats` file:

```
#!/usr/bin/env bats

CMD=test

@test "project should build" {
  run go build -o "$CMD" ../.
  echo "$output"
  [ "$status" -eq 0 ]
}

@test "verify should be fail for bad yaml" {
  run ${CMD} verify -s ../testdata/yaml/search.yaml
  echo "$output"
  [ "$status" -eq 2 ]
  [[ $output = *"err: \"path required\"" ]]
}
```

When I run `bats test`, it says:

```
 ✗ verify should be fail for bad yaml
   (in test file test.bats, line 27)
     `[ "$status" -eq 2 ]' failed with status 2
   /usr/local/Cellar/bats-core/1.2.0/libexec/bats-core/bats-exec-test: line 69: test: -s: binary operator expected
```

I don't understand exactly what is that mean actually. I think something is bad at this line:
`run ${CMD} verify -s ../testdata/yaml/search.yaml` but it looks good to me.

Any ideas?

**Comment by martin-schulze-vireso** [comment]
What should `test verify -s ../testdata/yaml/search.yml` do? AFAIK `test` has no `verify` option, did you mean to run `test -s ../testdata/yaml/search.yml` to check if the file exists?

**Comment by martin-schulze-vireso** [comment]
@sublimino @Dentrax I think this can be closed.
