### ISSUE TITLE
bats dockerfile

### ISSUE THREAD

**Issue by dhoer** [bats-core/bats-core#315]
I know the readme has info on building dockerfile, but can the be automated to release to docker hub?

The last version release there was 1.1.0: https://hub.docker.com/r/bats/bats/tags

**Comment by sublimino** [comment]
Yes, apologies for the latency on this. There's a lot of release automation required : ]

Until it's automated 1.2.0 has a [couple of bugs](https://github.com/bats-core/bats-core/issues/266#issuecomment-626673821), when 1.2.1 lands I'll make sure it's on the Docker Hub

**Comment by sublimino** [comment]
`1.2.1` has been released to https://hub.docker.com/r/bats/bats/tags

As per #266 I'll push all the Docker tags next week, in the meantime `v1.2.1` and `1.2.1` are pushed. Please LMK how you get on @dhoer :pray:

**Comment by marshallford** [comment]
Is there a historical reason for publishing both `v1.2.1` and `1.2.1`? Should I be using one or the other?

**Comment by sublimino** [comment]
> Is there a historical reason for publishing both `v1.2.1` and `1.2.1`? Should I be using one or the other?

A mixup between git tags and docker tags, and I'm in "better safe than sorry" mode! They will both persist, although the latter is more idiomatic for Docker and should be preferred : ]

**Comment by dhoer** [comment]
Looks good either way, thanks for all of your hard work!
