### ISSUE TITLE
Release documentation discussion

### ISSUE THREAD

**Issue by Pinjasaur** [bats-core/bats-core#318]
Creating this as a discrete issue as requested here: https://github.com/bats-core/bats-core/issues/39#issuecomment-633000552 (cc @martin-schulze-vireso)

I'm on macOS 10.15.x running Bash 4.4.x and BATS 1.2 (installed through Homebrew):

```
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.15.4
BuildVersion:   19E287
$ bash --version
GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin17.5.0)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
$ bats --version
Bats 1.2.0
```

With the following minimal `example.bats`:

```
#!/usr/bin/env bats

setup_file() {
  echo "# setup_file" >&3
}

teardown_file() {
  echo "# teardown_file" >&3
}

setup() {
  echo "# setup: $BATS_TEST_NAME" >&3
}

teardown() {
  echo "# teardown: $BATS_TEST_NAME" >&3
}

@test "example test" {
  skip "this is skipped"
}
```

The `setup_file` and `teardown_file` hooks aren't executing:

```
$ bats -t example.bats
1..1
# setup: test_example_test
# teardown: test_example_test
ok 1 example test # skip this is skipped
```

Insights appreciated. Cheers.

**Comment by martin-schulze-vireso** [comment]
Hm, I mistakenly thought the setup_file code was already on v1.2.0 but that is not the case. It is only on master. You probably read the README.md from master?

**Comment by Pinjasaur** [comment]
Yeah, I was referencing `README.md` @ `master`.

Having some solid way to view the docs at a specific release would obviously be a great addition. Either a) a dedicated docs site, b) each release gets a branch that has the snapshot of the README at that time or c) something else. It might be worth changing the development pattern so the default GitHub branch is the one that contains only "production" (read: released) code so when someone views the project e.g., the README&mdash;it's accurate.

I'd be willing to put some time into help making that happen, FWIW. It's something that would be beneficial to the project, as this issue I created demonstrates.

**Comment by martin-schulze-vireso** [comment]
> https://github.com/bats-core/bats-core/tree/v1.2.0

Releases are tags, so you can see their respective state via e.g. https://github.com/bats-core/bats-core/tree/v1.2.0 If you don't want to guess those links, you can find them in the [releases page](https://github.com/bats-core/bats-core/releases) on the left, where the tag name is listed behind the little tag symbol.

**Comment by Pinjasaur** [comment]
Sorry, I do understand that releases are just tags and they can be viewed like any other object in Git.

It just wasn't intuitive to me that what was on `master` wasn't what was cut from the most recent release. I've never viewed a release/tag as a snapshot, only to do diffs between releases.

I still think it would be valuable to ship the documentation so it is coupled with the release in some way. Tags/branches aren't immutable. Even hyperlinking to a permalink (<kbd>y</kbd> is the UI shortcut) of the README/docs in the release would be worthwhile in the short term, IMHO.

If this is something that is deemed worthy to be contributed on I'm willing to help out. I'll leave that decision up to the maintainers.

Going close this issue now, too, since the core issue has solved. Will watch for the next release where I'm assuming the functionality will exist.

If you wanna chat about the documentation further, I'm happy to discuss in a discrete issue.

**Comment by jasonkarns** [comment]
> It just wasn't intuitive to me that what was on `master` wasn't what was cut from the most recent release.

We follow the conventional "github" flow (a variant on trunk-based development, if you like) where master is edge and releases are tagged from it. So the docs in master contain what will _become_ a future release (and tag).


> Tags/branches aren't immutable.

It's true that you can force push a tag, but by community convention and recommended practice, tags are indeed expected to be immutable. And we conform to that expectation; tags should never ever be force pushed. So you can feel comfortable sharing tag-anchored links for docs, etc.

**Comment by kaysond** [comment]
I just got caught by the same thing. Having the master's README contain not-yet-released features is very confusing. Could you perhaps keep master at the latest release and use a `develop` branch for the latest work?

**Comment by martin-schulze-vireso** [comment]
I would concur that it can be confusing that the "landing page" of this repo shows a different state. than the latest release. However, it is the defacto standard on github to have master there. How do other projects deal with this issue?

Maybe the header of the README.md should begin with a note that informs that reader. E.g:

> **WARNING**: This is the current development state. If you want to see the documentation for the latest version (1.2.0), please look [here](https://github.com/bats-core/bats-core/tree/v1.2.0).

**Comment by martin-schulze-vireso** [comment]
Okay, issue #319 is just another instance of someone having version 1.2.0 but reading the master documentation.

**Comment by Pinjasaur** [comment]
All I can really offer is my $0.02. Updated the issue title for better visibility.

@jasonkarns 

> conventional "github" flow [...] tags are indeed expected to be immutable

Cheers, I do appreciate the clarification on the development flow style and the ideal world of tags/branches being immutable. A scenario to ponder: what if I wanted to contribute docs on the _latest_ release? That's something I've done on projects before: small grammar fixes, maybe a typo here or there. Unless it's documentation that is "baked" into the app e.g., `bats --help` then there shouldn't be a need for a new semver release since the docs are viewed in a decoupled way e.g., here on GitHub. That's the idea that I'm trying to poke at and hopefully help solve here.

---

@martin-schulze-vireso

> Maybe the header of the README.md should begin with a note that informs the reader. E.g:
> 
> > **WARNING**: This is the current development state. If you want to see the documentation for the latest version (1.2.0), please look [here](https://github.com/bats-core/bats-core/tree/v1.2.0?rgh-link-date=2020-05-29T07%3A11%3A06Z).

I don't think that header is a bad idea. I don't think it would harm, at least. You'd still be stuck with the scenario I mentioned above where any docs updates would require a new semver tag (release) but it would at least help point people like myself, @kaysond, or #319, in a better direction.

> I skimmed a bit through some github projects and most of them have general information in the README.md and only link to a documentation page that aggregates the different versions. Maybe we should split the documentation into its own markdown file and have a github page that aggerates the released versions' documentation.md?

I do agree with the patterns you describe as being common. The docs don't need to leave GitHub in the sense they can still live in this repo—or another one, like `bats-core/docs`, if desired. Since this project follows semver there's a reasonable chance that all docs could live in a single place since the `v1.x.y` should, ideally, all be backwards compatible.

> It would be nice if we could automatically generate all targets (man page, --help text, github page) from the same source, having to edit only one source file.

I'm not familiar enough with this project but I could certainly see the value in that automation.

**Comment by martin-schulze-vireso** [comment]
As you can see above, I tried to whip up some stop gap solution for now. You can see it at https://github.com/martin-schulze-vireso/bats-core/tree/link_to_version_specific_documentation

**Comment by martin-schulze-vireso** [comment]
Although #321 is merged now, I would propose to get this fixed for the next release, because we might "leak" the warning header when we don't remove it on the tag.

**Comment by sublimino** [comment]
Something I've mused over is the Java-ish `-dev` version suffix, so (once `1.2.1` is released ofc)  code in master would be `1.3.0-dev`, which might make things more obvious. 

Separately, full "git flow" for a project of this velocity would be an overhead IMHO, but arguably as we deal with infrastructure veractity this is an important enough reason to keep master extra-obvious and clear. 

`-dev` suffix and git flow: WDYT @martin-schulze-vireso @jasonkarns @Pinjasaur @kaysond?

**Comment by martin-schulze-vireso** [comment]
I don't think the -dev suffix would solve the problem. People navigate to the project page and just read the documentation without paying much attention to the actual branch. After all, they could even pick the specific tag there.

I'd find fullblown git flow a bit overkill, especially to solve only this documentation problem. The simplest branch based solution would be to have something like a release/latest branch as the main branch and updating it when a new release has been made. This is similar to git flow's master but omits the more elaborate hotfix and release branch handling.

I'd prefer another solution:
From my quick survey of some larger projects I gathered that most use some explicit documentation site like a wiki or https://readthedocs.org/. That decouples the documentation issue from the development workflow and improves documentation structure, including the versioning.

Additionally, we have the issue that shipped documentation seems not to be used:
> I still think it would be valuable to ship the documentation so it is coupled with the release in some way.

@Pinjasaur you installed via Homebrew, is the man page not available? Why did you come here to view the documentation?

**Comment by sublimino** [comment]
@martin-schulze-vireso readthedocs is a good idea, and would help this problem. 

The downside of having a "releases-only" master is that code between releases doesn't get tested by drive-by users (who then effectively install "tags", as HEAD is always tagged), and we only have general testing/bug-finding post-release. That's enough to deter me at the moment.

Currently an install from `master` only shows the correct version in `bats --version` if `HEAD` happens to be tagged/a release commit too. 

So possibly with readthedocs and `-dev` tags we would gain:
1. stable docs 
1. correct `bats --version` version numbers when installing non-tagged versions
1. users still test non-release ("dev" or "dirty") versions

**Comment by martin-schulze-vireso** [comment]
I gather from that following requirements:

1. make documentation available from read the docs (at least for 1.3.0 onwards)
2. mark master `bats --version` as dev version
3. don't mark releases as dev

I think this entails a bigger CI script that updates read the docs and changes some internals to replace the dev version with the release number when packaging the release.

**Comment by sublimino** [comment]
Agreed @martin-schulze-vireso. FWIW there may be a few other things we could do in an auto-release script (running https://github.com/bats-core/bats-core/blob/master/contrib/release.sh, pushing Docker images, releasing to npm, etc.). 

There's a useful "is this commit a git tag (i.e. release)" in https://github.com/bats-core/bats-core/issues/144#issuecomment-416444075

**Comment by martin-schulze-vireso** [comment]
I gather from #327 that we now got v1.2.1 with the development version warning banner in the documentation. That is really unfortunate. I think this situation should be fixed ASAP before any more releases get this, or we should at least take the banner down and indicate the versions where features were introduced.

**Comment by martin-schulze-vireso** [comment]
Since we have moved the bulk of documentation over to read the docs, I am closing this now.
