### ISSUE TITLE
--formatter not recognized format 

### ISSUE THREAD

**Issue by ikhader** [bats-core/bats-core#319]
OSType:
MacOS Mojave
version: 10.14.6 (18G5033)

$ bats --version
Bats 1.2.0 --> latest version of bats
$ cat add.bats --> test file details
@test "addition using bc" {
result="$(echo 2+2 | bc)"
[ "$result" -eq 4 ]
}
@test "addition using dc" {
result="$(echo 2 2+p | dc)"
[ "$result" -eq 4 ]
}
$ bats add.bats --> Run test case
✓ addition using bc
✓ addition using dc

2 tests, 0 failures

$ bats -c add.bats --> count number of test cases
2
$ bats --formatter junit -T add.bats --> FAILURE/ERROR JUNIT XML output
Error: Bad command line option '--formatter'
-- bats helper menu is displayed
========
--Note: If I run the same test case of CentOS with same version it passes
[centos]$ cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
---
[centos]$ bats --version
Bats 1.2.0
[centos]$ ls
add.bats
[centos]$ bats --formatter junit -T add.bats   --> same command used as earlier.
1..2
ok 1 addition using bc in 0sec
ok 2 addition using dc in 0sec
[centos]$ ls
add.bats  TestReport-add.bats.xml --> New file gets created successfully

**Comment by martin-schulze-vireso** [comment]
The formatter option is not available on 1.2.0, only on master. The help text/man page for bats should list that according to your version.

**Comment by martin-schulze-vireso** [comment]
@ikhader @sublimino I think this can be closed.
