### ISSUE TITLE
Does `bats` have a way to time out tests that hang?

### ISSUE THREAD

**Issue by stefanlasiewski** [bats-core/bats-core#320]
I have a test that runs a remote command on a Kubernetes cluster, but that command sometimes waits forever (literally) due to a problem on the cluster.

Does BATS have an easy way to time out tests when they take too long?

I did ask this question in Gitter, but I never heard back so I'm trying to get some help here.

https://gitter.im/bats-core/bats-core?at=5eb35dde3d58de7a38fc44c7

**Comment by sublimino** [comment]
Personally I use the `timeout` command in my assertion helpers as per https://linux.die.net/man/1/timeout

Bats has no internal mechanism for this.

**Comment by stefanlasiewski** [comment]
Thanks for the reminder about `timeout`. I'll use that moving forward.
