### ISSUE TITLE
How to make 'set -x' work?

### ISSUE THREAD

**Issue by dantesun** [bats-core/bats-core#325]
One of my bat test is hanged . And I can't find a way to make 'set -x' work. I followed the instructions from this old issue (https://github.com/sstephenson/bats/issues/270 ) but have no luck.  The failed bat test is here.(https://github.com/gdubw/gdub/blob/gng-merge/tests/failed_test.bats)

**Comment by martin-schulze-vireso** [comment]
Can you give your test run command as well? Is it just `bats failed_test.bats`? Also, which version of bats are you using?

One thing I noticed on a quick glance: The test transitively sources `lib/load.sh` (via `load test_support`) which changes the ERR trap. This might interfere with bats' own ERR trap handler. You should try to avoid sourcing your own helper libraries into the bats environment.

I don't see where you applied the `BASH_XTRACEFD=3` part from https://github.com/sstephenson/bats/issues/270?

**Comment by martin-schulze-vireso** [comment]
While trying to reproduce this locally I encountered following issues:

1. when using the pretty formatter and BASH_XTRACEFD=3, no output would be given
2. when using the tap formatter and BASH_XTRACEFD=3, the `set -x` output is visible but not prefixed with `#`
3. using `BASH_XTRACEFD=2` or no `BASH_XTRACEFD=3` gives correctly `#` prefixed output, however it is barely usable as there is too much going on. You get to see each debug_trap call and too many bats internals to really make out the test code in between.

I think this method is not usable (anymore?) without turning the `set -x` output off on each transition into bats.

@sublimino Do you think this should be a supported workflow? If not, should we close this issue as won't fix?

**Comment by martin-schulze-vireso** [comment]
Closed, as I think `set -x` is unusable. Seeing that there is #137, we should work in that as a replacement.
