### ISSUE TITLE
development version warning

### ISSUE THREAD

**Issue by Vampire** [bats-core/bats-core#327]
The readme now has a big fat "development version" warning.
If you have a "release checklist" you should add to remove that and re-add it with the new version.
Currently the 1.2.1 tag readme says that it is the development version
and the master readme still points to the 1.2.0 version.

Alternatives would be to remove the warning and instead have the latest released version on `master`, developing on some other branch like `develop` or to not modify the readme until release, having some in-progress copy that is copied to the real readme on release or similar.

**Comment by martin-schulze-vireso** [comment]
> Alternatives would be to remove the warning and instead have the latest released version on master

There is already a discussion about this in #318.

**Comment by sublimino** [comment]
Argh, this is my fault.

> If you have a "release checklist" you should add to remove that and re-add it with the new version.
Yes, it's in https://github.com/bats-core/bats-core/issues/266, I have added this retrospectively to that checklist.

This, and the fact that npm hasn't been updated, seems reason enough to cut a 1.2.2 perhaps.

**Comment by martin-schulze-vireso** [comment]
Closing this since it has become obsolete with the move to read the docs.
