### ISSUE TITLE
Wrong advice about -T for junit formatter

### ISSUE THREAD

**Issue by Vampire** [bats-core/bats-core#328]
The readme says
> By combining -T and --formatter junit, it is possible to output junit-compatible report files.

and also uses it in the examples.

But here: https://github.com/bats-core/bats-core/blob/master/libexec/bats-core/bats#L192-L195
the effect of `-T` is automatically done if the `junit` formatter is used, so `-T` is actually superfluous.

**Comment by martin-schulze-vireso** [comment]
I believe this carried over from the original PR where this was mandatory.
