### ISSUE TITLE
Spurious tests executed when specifying test directory multiple times

### ISSUE THREAD

**Issue by Vampire** [bats-core/bats-core#329]
When I do `bats test/ -f specifying\ version` all is fine, one test is executed:
```
 ✓ specifying version parameter should output version and exit with 0 no matter what

1 test, 0 failures
```
I accidentally did `bats test/ test/ -f specifying\ version` which resulted in this:
```
 ✓ specifying version parameter should output version and exit with 0 no matter what
 ✓ specifying version parameter should output version and exit with 0 no matter what
 ✓ begin 1 specifying version parameter should output version and exit with 0 no matter what
 ✓ begin 2 specifying version parameter should output version and exit with 0 no matter what
   bats warning: Executed 4 instead of expected 2 tests

2 tests, 0 failures
```
Then I just tried what happens with 3 times `test/`, whether there will be 6 or 9 and it was 9:
```
 ✓ specifying version parameter should output version and exit with 0 no matter what
 ✓ specifying version parameter should output version and exit with 0 no matter what
 ✓ specifying version parameter should output version and exit with 0 no matter what
 ✓ begin 1 specifying version parameter should output version and exit with 0 no matter what
 ✓ begin 2 specifying version parameter should output version and exit with 0 no matter what
 ✓ begin 3 specifying version parameter should output version and exit with 0 no matter what
 ✓ begin 1 specifying version parameter should output version and exit with 0 no matter what
 ✓ begin 2 specifying version parameter should output version and exit with 0 no matter what
 ✓ begin 3 specifying version parameter should output version and exit with 0 no matter what
   bats warning: Executed 9 instead of expected 3 tests

3 tests, 0 failures
```

**Comment by martin-schulze-vireso** [comment]
The same thing happens when specifying a file multiple times.

What would be your expectation? Should each test be run only once or should there be an error message?

**Comment by Vampire** [comment]
I would probably be fine with running a test 3 times if it was requested 3 times.
But I think those additional "tests" that are no real tests shouldn't be there, the "begin ..." lines that also cause the warning.

**Comment by martin-schulze-vireso** [comment]
I see, I did not notice these were not yours. That is indeed strange and looks like some sort of extended syntax mishap.

**Comment by Vampire** [comment]
That's why I showed you the good example where only one line is printed and no warning. ;-)

**Comment by martin-schulze-vireso** [comment]
Okay, the problem was that exec-suite would setup a tests list with the files test beeing duplicated as wanted. However, we also ran exec-file as many times. The latter did not know about the duplication in the tests list and executed it faithfully, thus creating nxn runs for each test (where n is the duplication factor).

The internal checks correctly summed up the tests from all consecutive files as expected count and the resulting mismatch produced the error message that you saw.

I don't know where the `begin x` problems come from but they vanished with the fix now.
