### ISSUE TITLE
Variables defined in setup_file not visible in test

### ISSUE THREAD

**Issue by EwaMarek** [bats-core/bats-core#330]
Hi,

Congrats on the v.1.2.1 release!
I have a question about the setup_file. After reading in the README.md _"Variables that are defined in setup_file will be visible to all following functions (setup, the test itself, teardown, teardown_file)."_ it was my understanding that the test in the below script will work:

```
#!/usr/bin/env bats

setup_file() {

    var_set_in_setup_file="4"
}

@test "check numbers" {

    echo "Test: Variable set in setup_file: ${var_set_in_setup_file}"
    [ "${var_set_in_setup_file}" -eq "4" ] 
}
```
However it returns:
```
 ✗ check numbers
   (in test file run_setup_file.bats, line 11)
     `[ "${var_set_in_setup_file}" -eq "4" ] ' failed with status 2
   Test: Variable set in setup_file: 
   /tmp/bats-run-25633/bats.25654.src: line 11: [: : integer expression expected

1 test, 1 failure

```
So the _var_set_in_setup_file_ isn't really visible in the test. As a workaround I used export:
```
#!/usr/bin/env bats

setup_file() {

    export var_set_in_setup_file="4"
}

@test "check numbers" {

    echo "Test: Variable set in setup_file: ${var_set_in_setup_file}"
    [ "${var_set_in_setup_file}" -eq "4" ] 
}
```
Which gave me expected result:
```
 ✓ check numbers 

1 test, 0 failures
```
However I am wondering if this is the expected behaviour? 

Thanks,
Ewa

-------------------------------------------------------------------------------------------------------------------------------------
1. State the version of Bash you're using bash --version:
Bats 1.2.1

2. State your operating system and its version
Ubuntu 18.04.4 LTS (Bionic Beaver)

3. Command line steps or code snippets that reproduce the issue
I ran the above script using bats without any parameters: `bats test_setup_file.bats`

**Comment by martin-schulze-vireso** [comment]
I think the documentation wording should be 

> Variables that are ~defined~ exported in setup_file will be visible to all following functions (setup, the test itself, teardown, teardown_file).

There is even a test case ("variables exported in setup_file are visible in tests").
