### ISSUE TITLE
pretty output with junit formatter

### ISSUE THREAD

**Issue by jeff-cook** [bats-core/bats-core#342]
I plan on running bats inside a CI pipeline. It would be great to be able to run bats with both the pretty console output while also saving the junit report. 

I tried and only got the junit output, or the pretty output.

```
bats --recursive --pretty --formatter junit .
bats --recursive --formatter junit --pretty .
```

Is there anyway to be able to get both without running the command twice?

**Comment by martin-schulze-vireso** [comment]
Unfortunately, no. They are both formatters and there can only be one formatter. However, during implementation the discussion already came up, whether junit should be considered a formatter at all.

**Comment by jeff-cook** [comment]
I could see not having junit being a formatter and have it a new `--report` output. That would be the best of both worlds to me.

**Comment by martin-schulze-vireso** [comment]
> I could see not having junit being a formatter and have it a new --report output.

I was thinking along the same lines. @sublimino What do you think about this?

**Comment by martin-schulze-vireso** [comment]
After having thought about this for a while I want to get into a more detailed discussion. The basic question is: What is the purpose of `--formatter` when we have `--report`?

Until the JUnit formatter, we only had the output on stdout in formats pretty and tap. Where tap is basically the internal output stream. Additionally, we have the lava (#300), CppUnit (#54) , and tap13 (#337) formats in PRs.

As far as I can see, bats has two basic usage modes: Interactive, when developing locally in a terminal and batch when started within a CI script.

The consumption of bats output is also dependent on this: In interactive mode, the developer looks at the stdout and might sometimes use the return code. In batch mode, the return code is probably the most important feature, if the CI pipeline does not support report parsing, the user will look at the stdout. If report parsing is supported, then the report will be reprocessed for human consumption.

The current `--formatter` option sets the format of stdout, the `--report` option sets the format of the report file. I see the following matrix:

  Format  | `--formatter` | `--report`
------------ | -------------------- | --------------------------
TAP[13] | reduced readability | yes 
pretty | yes | no
junit | no | yes
CppUnit | no | yes
lava | no | yes

From this table I gather that we really need just one stdout format, which is `pretty` and all other formats are more or less for report mode. The only exception is TAP, which is still human readable enough. We might need to provide at least TAP for backwards compatibility and some tests might become easier if we just can work with the format on stdout but other than that I don't see compelling reasons for the other formatters to ever be printed on stdout.

What do you think about all this @sublimino ? Should we just default to pretty output (maybe with a non-interactive version for CI logs)?

**Comment by martin-schulze-vireso** [comment]
@jeff-cook Could you try whether the PR #345 results in output that is compatible with your consumer?

**Comment by martin-schulze-vireso** [comment]
Yes, I'd say we should remain compatible to the older interfaces. I think it would even be useful to output other formats directly to stdout for tests but I would not advertise this as a feature to users.

I think it is obvious that we should support the `--pretty` and `--tap` flags as before. I also don't see any problem with combining `--pretty` and`--report`. The only thing I am not sure about is the default case which currently switches between tap and pretty when an interactiev terminal is detected.

**Comment by sublimino** [comment]
> I think it would even be useful to output other formats directly to stdout for tests but I would not advertise this as a feature to users.

The thought had crossed my mind too — that would be useful.

> The only thing I am not sure about is the default case which currently switches between tap and pretty when an interactiev terminal is detected.

This was the behaviour I suggest we keep, do we have a reason to change it? I know it's slightly slower than TAP, but am not concerned by that as users have control over those flags.

**Comment by martin-schulze-vireso** [comment]
> This was the behaviour I suggest we keep, do we have a reason to change it?

I am not sure we are on the same page here. My proposal is to change it in the following way: If not requested otherwise we always print in pretty mode. However, the terminal detection could turn off the color control sequences.

**Comment by martin-schulze-vireso** [comment]
The rewrite of the extended interface is not yet completed.

- [ ] this is a reminder that I have local changes pending
