### ISSUE TITLE
Minor problem: `apk info` shows warnings in docker container

### ISSUE THREAD

**Issue by tsubasaogawa** [bats-core/bats-core#347]
Hi.

I built Dockerfile (master branch) using docker-compose.
I ran `apk info` in the container. Then I got the following two warnings.
```bash
$ docker run --entrypoint=sh --rm -it bats-core_bats
/code # apk info
WARNING: Ignoring APKINDEX.2c4ac24e.tar.gz: No such file or directory
WARNING: Ignoring APKINDEX.40a3604f.tar.gz: No such file or directory
busybox
alpine-baselayout
alpine-keys
libcrypto1.1
   :
```

It can be fixed by adding `apk update` before `apk add` in Dockerfile.

```bash
$ docker run --entrypoint=sh --rm -it bats-core_bats
/code # apk info
busybox
alpine-baselayout
alpine-keys
libcrypto1.1
   :
```

It's not a serious problem, but it bothers me a bit and I want to fix it.
How about?

**Comment by martin-schulze-vireso** [comment]
Cannot reproduce this with bats/bats:1.4.1 container.
