### ISSUE TITLE
BATS_TEST_START_TIME: unbound variable

### ISSUE THREAD

**Issue by MatthiasScholzTW** [bats-core/bats-core#351]
In the script [bats-exec-test:85](https://github.com/bats-core/bats-core/blob/5f171044ac91ddb54bd1c6c3e7b0e6f541ef80b8/libexec/bats-core/bats-exec-test#L85) an unbound variable is used: `BATS_TEST_START_TIME`.

For some bats test I source scripts. These scripts are using `set -o nounset` to help me finding mistakes in my scripts more easily. Since in the mentioned file an unbound variable exists the test execution fails.

**Comment by martin-schulze-vireso** [comment]
Thanks for reporting this. Please add an example file and bats call that reproduces the behavior: I believe this issued might already be solved in #337 but a reproducer would be good for test coverage.

**Comment by MatthiasScholzTW** [comment]
After checking the changes I agree it should be solved with #337. Looking for the next release.

Will try to create a reproduction sample it should not be that complicated.

**Comment by martin-schulze-vireso** [comment]
Closed because #337 has been merged.
