### ISSUE TITLE
BATS not cooperating with expect scripts

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [bats-core/bats-core#355]
I am running an `expect` script using BATS.

The expect script in its turn invokes an interactive sequence of a cli tool I am working on.

Although when I perform the steps defined within the particular BATS test manually everything works as expected and yields exit code `0`:

```
cd test_expect

./basic_interactive.exp
.
.
.
▶ echo $?
0
```

the following test suite fails with exit code `2`

```
@test "Running interactive test - providing clone directory parameter" {
    cd test_expect
    ./basic_interactive.exp
    [[ "$status" == 0 ]]
}


▶ ./bats_testing.sh      
 ✗ Running interactive test - providing clone directory parameter
   (in test file bats_testing.sh, line 40)
     `[ "$status" -eq 0 ]' failed with status 2
```

**Comment by martin-schulze-vireso** [comment]
The status variable is only available when using the `run` command. However, non zero exit codes will result in a failure anyways when you don't use `run`.

**Comment by pantelis-karamolegkos** [comment]
Thank you very much for the feedback.
Closing this.
