### ISSUE TITLE
Docker multiarch image with ARM support

### ISSUE THREAD

**Issue by elmariofredo** [bats-core/bats-core#356]
It would be great to have ARM docker images as projects like https://github.com/grafana/helm-charts use bats for smoke tests and without ARM support we are unable to run it on Raspberry Pi clusters. Base image https://hub.docker.com/layers/bash/library/bash/5.0.18/images/sha256-e9bf26294532fe6cceb0a1b1129f8136ddad129b16ed85544d7450f71c6f13b5?context=explore have multiarch support so it should not be that hard to make bats as well. Thanks

**Comment by martin-schulze-vireso** [comment]
@elmariofredo FYI, 1.4.1 is now on available on docker hub with arm architectures.
