### ISSUE TITLE
command line parameters

### ISSUE THREAD

**Issue by norricorp** [bats-core/bats-core#357]
Hi 
is it possible to have command line arguments eg
./fred.sh arg1 arg2

If I echo $# (to stderr) then it will be zero, whether there are no arguments or several.
Also the various args eg $2 is empty.
Am I doing something wrong?

**Comment by martin-schulze-vireso** [comment]
I don't see any bats code in your post and am not sure what exactly you are asking. Could you provide a more complete example with a bats file, the invocation, and possibly the intended behavior.

**Comment by norricorp** [comment]
That was quick - many thanks.
So I had this file - just a simple paly file to try something.
#!/usr/bin/env bats

# if [[ $# -ne 2 ]] 
# then
    # echo "curlTest.sh version host" >&2
    # exit
# fi

echo "number of args is $#" >&2
echo "the second arg is $2" >&2
echo hello john >&2
java -version >&2

Which results in 
$ ./fred.sh uiguh iuiuhuih
number of args is 0
the second arg is 
hello john
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

So $2 is not being found.

If I remove the comments on the argument test then
$ ./fred.sh uiguh iuiuhuih
curlTest.sh version host
/usr/lib/bats/bats-exec-suite: line 20: let: count+=: syntax error: operand expected (error token is "+=")

**Comment by martin-schulze-vireso** [comment]
Okay, in short: bats does not forward its cli parameters to the test file, so that won't work as you intend. Usually you would have a test Like this:
```
@test "Test name" {
  # Call the commands to test here
}
```
So the parameters are specified in the file, not via cli arguments.

**Comment by norricorp** [comment]
Thanks for this Martin.
As an aside (and whilst I have your attention) is there a outputContains test?

**Comment by martin-schulze-vireso** [comment]
Not in vanilla bats-core, but there is the  bats-assert library, see https://github.com/bats-core/bats-core#libraries-and-add-ons

**Comment by norricorp** [comment]
That is very useful. Many thanks. Great to see the project is still actively and enthusiastically supported.

**Comment by sublimino** [comment]
> I think these questions should be part of a beginner tutorial. Do we already have one?

Nope, and I agree this would be useful content.

Closet we have is some README entries and https://github.com/bats-core/bats-core/wiki/Bats-Evaluation-Process
