### ISSUE TITLE
skipped test takes minutes to be skipped

### ISSUE THREAD

**Issue by norricorp** [bats-core/bats-core#359]
Hello,
I am running a test file that starts a few server proceses as setup and then runs a series of curl commands as tests, checking output.
There are 15 tests and all bar the first two are skipped. And yet each skipped test is taking about two minutes to "run". Output to the screen is eg "- get OWNERS AGAIN (skipped)" - so BATS knows it is being skipped.

When I have used BATS within exercism.io code (easily the area that I have most experience with), skipped tests run "instantly".

If I run the bats file as a shell script with no ref to BATS (and hence no skipped tests) the curl calls are all run within 5 seconds.

Here is the main part of the code

```
#!/usr/bin/env bats

get_output(){
  curl -s -H "Authorization: Bearer $TOKEN" -k -w "\n" https://$HOST:8453/api/v1/$1 | sed 's/\r//g'
}

get_length(){
  curl -s -H "Authorization: Bearer $TOKEN" -k -w "\n" https://$HOST:8453/api/v1/$1 | sed 's/\r//g' | jq '. | length'
}

VERSION=0.0.1
HOST=yyyyyy

java -jar target/bikes-$VERSION-SNAPSHOT.jar --server.port=8453 > /dev/null 2>&1 &
TOMCAT_PID=$!
sleep 30

~/SpringBoot/keycloak/keycloak-6.0.1/bin/standalone.sh -b 0.0.0.0 > /dev/null 2>&1 &
KEYCLOAK_PID=$!
sleep 30

RESULT=`curl -s -X POST -H 'Content-Type: application/x-www-form-urlencoded' -d 'username=xxxxx&grant_type=password&client_id=xxxxxxx&password=xxxxxxx' http://192.168.1.79:8080/auth/realms/SpringBootKeycloak/protocol/openid-connect/token`
TOKEN=`echo $RESULT | sed 's/.*access_token":"//g' | sed 's/".*//g'`
RTOKEN=`echo $RESULT | sed 's/.*refresh_token":"//g' | sed 's/".*//g'`

@test "get OWNERS" {
#  skip
run get_length owners
  [ "$status" -eq 0 ]
  [ "$output" -eq 3 ]
}

@test "get BICYCLES" {
# skip
run get_output bicycles
  [ "$status" -eq 0 ]
  [ "$output" = '[json output]' ]
}


@test "get OWNER ONE" {
skip
run  get_output owners/1
  [ "$status" -eq 0 ]
  [ "$output" = 'json output' ]
}

# rest of tests continue 
```
I think what is happening is that it is running the intial code for every test (starting the server processes) yet I am not running this as setup code. As that initial code contains a minute of sleep, that makes each test quite lengthy. 

output is 
$ bats curlTestBats.bats
   get OWNERS                                                                                        1/15
 ✓ get OWNERS
 ✓ get BICYCLES
 - get OWNER ONE (skipped)
 - post OWNER (skipped)
more tests
 - delete BIKE (skipped)
   delete OWNER                                                                                     15/15
 - delete OWNER (skipped)

What am I doing wrong?

**Comment by martin-schulze-vireso** [comment]
Each test requires a full evaluation of the whole file. So the `sleep 30` parts will be executed with each test, regardless of them being skipped. If you have to do setup per test then you should put that into `function setup {}`, which will be called before each test of the file (likewise there is `teardown` for cleanup). You can even skip from setup to avoid costly operations there as well.

Aside from that: If you have an unconditional (or commented out) skip in every test function you seem to be running tests selectively. Theres the `--filter` flag for that.

**Comment by norricorp** [comment]
Thanks for this.
I discovered a few problems with my setup. 
I installed on to ubuntu via the repo and that gave me the stephenson version at 0.4 and hence when running a test script with setup_file(0 , it ignored that.
So uninstalled, used the npm approach to install. Restarted the shell and bats now gives me 1.2.1.
Changed the script to use setup_file() and teardown_file() functions (the latter killing the servers so export the PID values from the former).
And that side of things now works - starts servers once, kills servers once, skipped tests are immediate. But the tests that passed, now fail. For example
```
 ✗ get OWNERS
   (in test file curlTestBats.bats, line 52)
     `[ "$output" -eq 3 ]' failed with status 2
   /tmp/bats-run-7315/bats.7612.src: line 52: [: : integer expression expected
```
In moving from 0.4 to 1.2.1 are there things I have not taken into account? (Spoiler alert: I am sure there are many)

**Comment by martin-schulze-vireso** [comment]
Most likely `$output` is empty, which is not an integer, hence the error. You should be using the asserts library to improve the error outputs.

**Comment by norricorp** [comment]
Looking at page for bats-assert. "See the shared documentation to learn how to install and load this library." Which takes me to ztombol docs. Is this documentation correct. Eg the use of github.com/ztombol for bats-support / bats-assert links. Presumably I should be using npm install github.com/bats-core/bats-support (and bats-assert)?
Doing that, I am getting unmet peer dependency for bats-support - it requires bats0.4 and I have bats 1.2.1 and the same for bats-assert (it requires bats0.4 and bats-support 0.3 and I have just installed 3.0)

So just a tad confused.

**Comment by martin-schulze-vireso** [comment]
Yes, that is a bit confusing since the documentation has not been moved/updated. The support and assert library have been moved under the bats-core organization. However, I don't know if the npm recipes have been updated for that as well. Your best bet is probably the git submodule approach.

**Comment by martin-schulze-vireso** [comment]
Further input like this should go into #358.
