### ISSUE TITLE
Junit formatter incorrectly outputs an extra `<testcase>` with a `<failure>` if writing to FD 3

### ISSUE THREAD

**Issue by bioball** [bats-core/bats-core#360]
If a test writes to FD 3 with a `#` prefix, it causes the resulting Junit to include a `<failure>` tag for this test case, which causes parsers to interpret the testcase as failing. It's also outputting two `<testcase>` elements rather than one.

Given this test:

```bats
@test "say hello to Biblo" {
    echo "# hello Bilbo" >&3
}
```

I see this Junit output (with properties redacted)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test.bats" tests="1" failures="0" errors="0" skipped="0" time="0" timestamp="2020-09-30T18:46:33" hostname="my-hostname">
    <testcase classname="test.bats" name="say hello to Biblo" time="0"/>
    <testcase classname="test.bats" name="say hello to Biblo" time="0">
        <failure type="failure"><![CDATA[
hello Bilbo]]></failure>
    </testcase>
  <system-out></system-out>
  <system-err></system-err>
</testsuite>
```

I'm thinking that the correct xml should look something like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test.bats" tests="1" failures="0" errors="0" skipped="0" time="0" timestamp="2020-09-30T18:46:33" hostname="my-hostname">
    <testcase classname="test.bats" name="say hello to Biblo" time="0">
      <system-out><![CDATA[
hello Bilbo]]></system-out>
    </testcase>
  <system-out></system-out>
  <system-err></system-err>
</testsuite>
```

Sidenote, I'm also seeing that log lines without a `#` prefix simply don't show up in the junit output

**Comment by martin-schulze-vireso** [comment]
Thanks for the report. I hope we can incorporate this into #345

**Comment by martin-schulze-vireso** [comment]
@bioball Does this represent your expectation: https://github.com/martin-schulze-vireso/bats-core/commit/9739981a697540a08ff1e434e421a6a686e8d4f9#diff-ebe0a9c6d5737b23edc89686ae385309R130

**Comment by bioball** [comment]
That looks pretty good! The one thing that I'm confused about is: writing to FD3 will write to `<failure>` if the test fails, but `<system-out>` if it passes? If so, I think it would be better if it was consistent and always wrote to `<system-out>`

**Comment by martin-schulze-vireso** [comment]
Okay, I split that out as well in https://github.com/bats-core/bats-core/pull/345/commits/d0a4231a2871468fa6f844d7b5929375ebafa03b I think the output handling got a lot cleaner now, thanks for that.

**Comment by bioball** [comment]
Nice! 🙌
