### ISSUE TITLE
Call for Maintainers 2020

### ISSUE THREAD

**Issue by sublimino** [bats-core/bats-core#362]
## Call for Maintainers 2020

`bats-core` was forked from `bats` 3 years ago, and in that time contributors have tidied up the codebase, built out cross-platform CI, added parallel test execution (and junit, report output, filtering, and more!), and fixed a long list of bugs.

Thanks to the original `bats-core` maintainer team for their substantial efforts in getting us here! @btamayo @mbland @jasonkarns 

But I am now mostly solo in reviewing and merging PRs. Many thoughtful contributors reply to PRs and issues, help newcomers, and suggest features, and responding to this work requires a better maintainer team than just me. Restoring the team to three or four active participants will increase velocity and ultimately the quality of the project.

So I'd like to invite people to join the `bats-core` organisation. What needs to be done:

- triage issues and PRs with helpful kindness
- technical review of issues and PRs
- debugging, contributing, and merging code
- finish CI (mostly done) and release process (still manual)

Ideas for the future:

- release a `bats-core` github action
- more output formats 
- beginner-friendly documentation
- better contributor documentation
- unification of code styles
- easier debugging and debugger integration
- releases to distributions
- performance test suite

Please register your interest with a comment below and I'll reach out to discuss moving forward together : ]

Kind regards,

<br/>

Andy

p.s. if you'd like to help amplify the signal, [tweet here](https://mobile.twitter.com/sublimino/status/1312387326568431616)

---

/cc recent contributors and names from previous CFMs @martin-schulze-vireso @waterkip @dimo414 @ko1nksm @ztombol  @juanibiapina @cinterloper @nstrug @colourmeamused @jubianchi @fearphage @scontini76 @harschware @cdevinesr @nkakouros @Flamefire

**Comment by martin-schulze-vireso** [comment]
Count me in. I am willing to do some issue cleanup and reviews and continue PRs, especially in the directions mentioned above.

**Comment by denhamparry** [comment]
:wave: I'd be interested in helping out

**Comment by fourdollars** [comment]
I would like to make an official Ubuntu snap package for bats.

**Comment by sublimino** [comment]
I'm very pleased to welcome @martin-schulze-vireso and @denhamparry on board, to help steward the growth of `bats-core` and shape its future :tada: 

@fourdollars that would be awesome, there's also an open [rpm issue](https://github.com/bats-core/bats-core/issues/313) I'm not sure what we have to do to help the maintainers though, so please let us know!

**Comment by martin-schulze-vireso** [comment]
Thanks for the invitation, I am looking forward to working with you and the community in my new role.

**Comment by reshadat** [comment]
I am willing to contribute as well, especially because I have started using bats extensively.

**Comment by denhamparry** [comment]
Thank you for welcoming me on board, looking forward to helping out :smile:

**Comment by cyphar** [comment]
I'm also up for helping out with maintenance.
