### ISSUE TITLE
latest master stdout with junit is not tap anymore

### ISSUE THREAD

**Issue by henning-schild** [bats-core/bats-core#373]
I run bats to generate tap and junit in one run like this

```
bats -t test.bats --formatter junit -T --output "${TEST_RESULT_DIR}" >> "${TEST_RESULT_DIR}/test.bats.tap"
```
That gives me junit and tap, with recent master stdout seems to be xml as well. Not sure whether this is intended, it for sure is an interface change.

good: dcaec03e32e0b152f8ef9cf14b75296cf5caeaff
affected: 8fb853a6cbc0169958707381985f3cd59789ccb1

It is probably coming from the "report" changes, did not dig ... @martin-schulze-vireso

**Comment by martin-schulze-vireso** [comment]
Yes, that is intended. There now is a `--report-formatter` option which changes the format the `--output` files, while `--formatter` changes the output on stdout. This is done to enable e.g. `--report-formatter junit --formatter pretty`.

**Comment by henning-schild** [comment]
Thanks, i will change my code accordingly when switching to the new version. Just wanted to point out the interface breakage which i did not find anything about in the CHANGELOG ... #374

**Comment by henning-schild** [comment]
In fact the correct transition is `--formatter junit` -> `--report-formatter junit`, adding `--formatter pretty` as well is a noop and breaks fallback to "tap" when there is no term

**Comment by martin-schulze-vireso** [comment]
We could add an override that maps `--formatter junit` to `--report-formatter junit` to not break previous users. That would require an additional notation like `--formatter junit-stdout` for users that actually want junit output on stdout (like the tests).
