### ISSUE TITLE
v1.2.1 fails to locate test files on Windows

### ISSUE THREAD

**Issue by kevinhankens** [bats-core/bats-core#375]
We are hitting the following error when running bats with any test file on our Windows test server using v1.2.1:
```
1..1
Input file specified two times.

-nThe system cannot find the file specified.
# bats warning: Executed 0 instead of expected 1 tests
```
v1.2.0 works fine with the same input files. 

This is `Microsoft Windows [Version 10.0.17763.1518]` and bash:
```
# bash --version
GNU bash, version 4.4.23(2)-release (x86_64-pc-msys)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

Thanks in advance for any assistance here!

**Comment by martin-schulze-vireso** [comment]
Thank you for the report. Please provide a reproducible example, so we can debug this.

**Comment by kevinhankens** [comment]
Sorry for the slow response. This should be reproducible on any comparable Windows machine with that version of bash. Would it be helpful to provide a CloudFormation template to launch an environment to work with? I don't have any real Windows experience, so I won't likely be much help here, but this seems related to https://stackoverflow.com/questions/55032127/error-the-system-cannot-find-the-file-specified-when-using-r-flag and likely triggered when sorting the test files to run.

**Comment by martin-schulze-vireso** [comment]
> This should be reproducible on any comparable Windows machine with that version of bash.

Thanks for clarifying the environment. However, it would also be helpful to have an example test file and the bats call that trigger the error or does that happy for any call on any file?

**Comment by kevinhankens** [comment]
For me, it happened on all tests, perhaps when there is more than one bats file in the directory. I will reproduce it shortly and provide as much info as possible here. Thanks for being patient! BTW, I absolutely LOVE the framework, thanks a million for all of the help 😄

**Comment by martin-schulze-vireso** [comment]
I am closing this until further feedback. Please reopen once you have a reproducer ready @kevinhankens
