### ISSUE TITLE
dc: command not found for additions.bats

### ISSUE THREAD

**Issue by aymanapatel** [bats-core/bats-core#380]
I am trying to run the `additions.bats` from README. 

1 out of 2 test is failing

```
 ✓ PASS - Addition using bc
 ✗ addition using dc
   (in test file addition.bats, line 11)
     `result="$(echo 2 2+p | dc)"' failed with status 127
   /tmp/bats-run-479/bats.503.src: line 8: dc: command not found
```

My `additions.bats` : 

```bash
 #!/usr/bin/env

@test "PASS - Addition using bc" {
  result="$(echo 2+2 | bc)"
  [ "$result" -eq 4 ]
}
@test "addition using dc" {
  result="$(echo 2 2+p | dc)"
  [ "$result" -eq 4 ]
}
```

Is dc some component that needs to be installed?

I am using Ubuntu 20.04 on WSL2 and I installed `bash-core` in two lines:

1. `sudo git clone https://github.com/bats-core/bats-core.git`

2.  `sudo ./install.sh /usr/local`

**Comment by martin-schulze-vireso** [comment]
Yes, `dc` is an additional program: http://manpages.ubuntu.com/manpages/trusty/man1/dc.1plan9.html

**Comment by martin-schulze-vireso** [comment]
I am closing this now, since the question seems to be answered and no further feedback was given.

**Comment by vukanac** [comment]
```
docker run -it -v "${PWD}:/code" -w /code bats/bats:latest test
1..2
not ok 1 addition using bc
# (in test file test/addition-test.bats, line 4)
#   `result="$(echo 2+2 | bc)"' failed with status 127
# /tmp/bats.10.src: line 4: bc: command not found
ok 2 addition using dc
```
