### ISSUE TITLE
publish the bats-core on https://open-vsx.org/

### ISSUE THREAD

**Issue by silent-mobius** [bats-core/bats-core#381]
I would like to ask you to publish the extention for vscodim, at https://open-vsx.org

Thanks in advance.

**Comment by martin-schulze-vireso** [comment]
By "the extension" do you mean https://github.com/jetmartin/bats? If so, this is a third party project. @sublimino Do we want to reach out to the author to bring this project into the org? I am a user but no extension developer.

**Comment by silent-mobius** [comment]
Thanks

**Comment by sublimino** [comment]
We could bring this in, but it would need a maintainer — I am not a VSCode
user.
