### ISSUE TITLE
How to know if test has failed/succeeded from teardown

### ISSUE THREAD

**Issue by boscharun** [bats-core/bats-core#383]
How can we know if test has failed/succeeded from teardown function at the end of a test?

**Comment by martin-schulze-vireso** [comment]
It is not documented and may be subject to change but you can check for `BATS_TEST_COMPLETED` which should be 1 if the test was completed without error. If it was skipped this will also be set to 1 but then `BATS_TEST_SKIPPED` should also be non empty.

**Comment by martin-schulze-vireso** [comment]
@boscharun Could you elaborate why you need this? Does your teardown need to do something different when the test succeeded/failed? 

If so, wouldn't it be safer to react to the change itself, instead of relying on the "out-of-band" communication via the test result?

**Comment by boscharun** [comment]
@martin-schulze-vireso , in our company's test environment, we create success/failure files for every test which indicate a success or failure. This is the way our in-house testing infrastructures expect results which further use them for reporting and CI activities. Am using the BATS_TEST_COMPLETED value to create them so BATS testing can be integrated easily into our infra.
P.S. Thanks again for the quick reply :)

**Comment by jandubois** [comment]
> Could you elaborate why you need this? Does your teardown need to do something different when the test succeeded/failed?

I realize this is a very old issue, but I had the same need today: I'm running BATS in Github Actions, and part of the process involves a GUI app.

In case a test fails I want to take a screenshot that will be uploaded with the test logs, so I can later check if maybe the GUI app was displaying a modal dialog and waiting for user input (which is obviously not expected, but this is CI after all).

**Comment by martin-schulze-vireso** [comment]
I think it would be better to separate teardown and reaching to test failures. This is not yet a feature but I am toying with the idea of an `bats_on_test_failed` callback, which would fit nicely for your use case.

**Comment by decentral1se** [comment]
Just wanna chime in that I am using https://github.com/bats-core/bats-core/issues/383#issuecomment-738628888 because I have a teardown specific command which is very costly which I only want to run if the test failed. Thanks for the work!
