### ISSUE TITLE
Function return value

### ISSUE THREAD

**Issue by wvdvegt** [bats-core/bats-core#390]
I'm trying to implements some in essence parameterized test using load (testing presence of HTTP headers0). However when i code functions and try to have them return of the test (pass/fail) I run into all kind of bash issues.

Question: is/has anyone there a workingexample of a function having parameters and returning a result (true/false would do)?

**Comment by martin-schulze-vireso** [comment]
Could you give an example of what exactly goes wrong? Most tests rely on the return value of a program, so I don't understand what is not working for you.

If you are using `run` and return the value via a variable, be aware that `run` creates a subshell to run the command in, so changes to variables will not be visible to the `run` calling shell.

**Comment by wvdvegt** [comment]
I'm working on a test suite that checks if a webserver has been configured as desired.

It had lots of tests as:

```
@test "check PHP ini (opcache.revalidate_freq)" {
  result=($(php -r "echo ini_get('opcache.revalidate_freq');"))
  
  echo "Detected:  '$result'"
  echo "Expecting: '60'" 
  
  [ "$result" == "60" ]
}
```
or
```
@test "check PHP iconv extension enabled" {
  result=$(php -m)
  
  mod="iconv"
  
  echo "Expecting:  '$mod'" 
  
  return=false
  
  for i in "${result[@]}"
    do
      #echo "'$i'"
      if [[ "$i" =~ "$mod" ]]; then
        return=true
      fi
  done
  
  [ "$return" == "true" ]
}
```
or
```
@test "Check http://github.com/" {
  run wget -q --spider https://github.com/
  
  echo $status
  
  [ "$status" -eq 0 ]
}
```
where i would like to use a function with the the varying part in the tests as parameters and the result of the function returning the test result. So remove lots of dulicate code and simplify maintenance.

So i would need functions that i can load & use with signatures as

I tried code as:

```
# parameter: php module name to check.
checkphpext() { 
  local mods=$(php -m)
  local modsarray=($mods)

  myresult=0
  for i in "${modsarray[@]}"
  do
    if [[ "$i" == *"$1"* ]]; then
      myresult=1
    fi
  done

  return $myresult
}
```
but it keeps failing to return the result value properly to the tests itself.

**Comment by martin-schulze-vireso** [comment]
Please provide the call to checkphpext as well. So far it looks like it should work.

**Comment by wvdvegt** [comment]
Hi

I use bats code as shown below.

```
#!/usr/bin/env bats

#######################################
# Setup and TearDown.
#######################################

load testmethods.bash

setup() {
  # Nothing yet

  true
}

teardown() {
  # Nothing yet
  
  true
}

#######################################
# PHP Modules
#######################################

@test "CHECK PHP filter extension enabled" {
  # date fileinfo
  result="$(checkphpext "filter")"
  
  echo "Detected:  '$result'"

  $myresult
}
```

The output is 

```
 ✗ CHECK PHP filter extension enabled
   (in test file mintest.bats, line 45)
     `result="$(checkphpext "filter")"' failed
```

**Comment by martin-schulze-vireso** [comment]
Okay, the function `checkphpext` uses `return 1` when it has found the extension.

Your calling code wants to assign the result to `result` via `$()` which actually gives you the stdout, not the return code.

Furthermore, the return code 1 is considered as an error in bash while 0 is a success.

So the command `result="$(checkphpext "filter")"` assigns the empty stdout to `result` and also checks the return code of checkphpext which is 1. By default, bats fails all lines that return non-zero.

I'd recommend following changes:

1. use return code 0 to signify a success and 1 to signify an error, to avoid friction with expected bash default behavoir
2. if you just want to ensure that the command did not fail, it is enough to simply run it: `checkphpext "filter"`

If you want to check the output of a command, I'd recommend you load the bats-assert library, which includes `assert_output` that will give you better diagnostics on test failures.

**Comment by wvdvegt** [comment]
Still confused (must be my lack of bash knowledge), if i removed the **result=** things fail.

The 2nd codesnippet is however the kind of minimal code i was hoping for.

```
@test "CHECK PHP filter extension enabled" {
  result="$(checkphpext "filter")"
  
  echo "Detected:  '$result'"

  # returns a correct result
  $myresult
}
```
```
@test "CHECK PHP filter2 extension enabled" {
  result="$(checkphpext "filter")"

  # returns a correct result
}
```
```
@test "CHECK PHP filter3 extension enabled" {
  "$(checkphpext "filter")"
  
  # fails to return a correct result
  $myresult
}
```

**Comment by martin-schulze-vireso** [comment]
```
 # fails to return a correct result
  $myresult

What are you trying to achieve here? The code as it stands would try to execute the command named by `$myresult` (so the intended programs would be 1 or 0 in your case). However, as I said above:

> If you are using run and return the value via a variable, be aware that run creates a subshell to run the command in, so changes to variables will not be visible to the run calling shell.

Now, you are not using run but `$()` which nevertheless creates its own subshell and does not feed back the value of myresult into the current shell.

As I understand your test, you simply need:

```
@test "CHECK PHP filter3 extension enabled" {
  checkphpext "filter"
}
```

With checkphpext returning 0 when the extension was found. If you omit the `$()`, you can also try to access `myresult` as it will be set in the same shell in this case, but since you seem to be interested only in the return code check, the above code is sufficient.

**Comment by wvdvegt** [comment]
Thanks a lot! 

Turned out had to remove some more characters (and that did the job).
