### ISSUE TITLE
Bad 'examples' link in docs

### ISSUE THREAD

**Issue by Infinoid** [bats-core/bats-core#393]
The [Writing tests](https://bats-core.readthedocs.io/en/latest/writing-tests.html) page links to [examples](https://bats-core.readthedocs.io/docs/examples), but that link produces a 404 error.

Is it meant to link to the [`docs/examples` folder of the git repo](https://github.com/bats-core/bats-core/tree/master/docs/examples)?

**Comment by martin-schulze-vireso** [comment]
Thanks for the report. The documentation was moved recently to readthedocs, so there might be some stale links.

**Comment by martin-schulze-vireso** [comment]
Crawling the page with wget gave me following broken links:

* https://readthedocs.org/projects/bats-core/search/ -> seems to be a false positive
* https://bats-core.readthedocs.io/en/latest/py-modindex.html -> invalid reference
* https://github.com/bats-core/bats-core/blob/master/docs/source/genindex.rst -> invalid reference
* https://github.com/bats-core/bats-core/blob/master/docs/source/search.rst -> invalid reference
* https://github.com/gliderlabs/docker-alpine/blob/master/docs/usage  -> the source contains .md extension which is stripped by sphinx, I could not find how to solve this except moving to .rst format
* https://bats-core.readthedocs.io/docs/examples -> this is a relative path in source
