### ISSUE TITLE
Founders blessing

### ISSUE THREAD

**Issue by thomas-mc-work** [bats-core/bats-core#402]
Well, this is not quite an issue but more of a discussion. [I just tried to update the reference to the abandoned bats project in the basher readme by bats-core](https://github.com/basherpm/basher/pull/94). But one of the members refused that by referring to the unofficial status of bats-core. He especially focusing in the situation about the project name. As the project is Open Source, how is it with the projects name?

What do you think about that? I guess you've probably tried to get in touch with Sam a couple of times. I've also composed and send him an email today, asking ti give his blessing for bats-core. I wonder whether he'll reply.

**Comment by sublimino** [comment]
Collectively we would love to know Sam's thoughts, there have been a number of issues asking for clarity  https://github.com/sstephenson/bats/issues/275

We're not a hard fork so the project name is derivative for discoverability, and we would also love to merge back upstream if that's ever a possibility. 

`basher` uses the original `bats` and it's fit for that purpose, so I understand his position. But a search for `bats` on https://basher.gitparade.com/search/?q=bats only returns `bats-core` results, so (personal bias aside!) I'm inclined to agree with the thrust of your linked PR to the README.

**Comment by rhwood** [comment]
[sstephenson/bats](https://github.com/sstephenson/bats/wiki) is now archived and its [wiki](https://github.com/sstephenson/bats/wiki) points to this project.
