### ISSUE TITLE
Fix CI Docker hub rate limit

### ISSUE THREAD

**Issue by martin-schulze-vireso** [bats-core/bats-core#404]
The CI builds [started failing](https://travis-ci.org/github/bats-core/bats-core/jobs/756881727) due to [Docker hub's rate limit](https://www.docker.com/increase-rate-limits). This leaves us without bash version testing.

I already tried to add `docker login` to the build but the associated credential variables won't be available in external PRs.

How can we work around this? Even if we had a paid plan for Docker hub, we would need to expose the login credentials to external users for their PRs to work.

The bash images don't seem to be available on alternative registries, yet. I opened an [issue](https://github.com/tianon/docker-bash/issues/23) on their repo.

**Comment by martin-schulze-vireso** [comment]
It looks like Github struck a deal with Docker to exempt  Github actions' runners from the limit. This means we should probably migrate to github actions.

**Comment by kolyshkin** [comment]
> It looks like Github struck a deal with Docker to exempt Github actions' runners from the limit. 

They are actually using proxy (as well as most of other CI systems, _except_ Travis) so they don't hit docker hub too often.

In any case, since travis-ci is being shut down real soon now, it makes sense to switch to GHA

**Comment by martin-schulze-vireso** [comment]
> In any case, since travis-ci is being shut down real soon now, it makes sense to switch to GHA

Thanks for the info. Up to now I thought they would be just be migrating all projects to the .com domain.
