### ISSUE TITLE
Code outside of setup/teardown

### ISSUE THREAD

**Issue by tterranigma** [bats-core/bats-core#41]
Right now I have a test file with some code in the setup function. If I remove the code outside of the setup function it still gets run and, output aside, the result is the same. Is there any essential difference between the two ways? I am asking because I want to print some text in the setup function but I cannot. Outside of the setup I can.

**Comment by mbland** [comment]
I'm not entirely sure if there is or not, but we should figure this out. Can you provide a minimal test file or two exhibiting the behavior you're observing in particular?

**Comment by mbland** [comment]
Thanks for doing my homework for me. (Traveling for work this week, staying pretty busy, but stealing a few minutes each morning to try to inch things forward.)

So do you feel like you have the insight you need to move forward? If you want to print from `setup()`, print to FD 3 prefixed with `#` (per https://testanything.org/tap-specification.html#diagnostics and the implementation of `libexec/bats-format-tap-stream`).

**Comment by tterranigma** [comment]
Yes, I think this issue is done! Before closing, would some notes make sense in the documentation? Maybe a section named "Effects of code outside BATS functions"?

**Comment by mbland** [comment]
Yep! This and #43 should get included, ideally before 0.5.0 if possible.
