### ISSUE TITLE
hardcoded assumption of the PATH in the test

### ISSUE THREAD

**Issue by yarikoptic** [bats-core/bats-core#411]
stems from  https://github.com/bats-core/bats-core/pull/387/files#diff-870c4614c5e0940e0d7208f7d67375d3927f50ea8b87d2ef6d2638593105f78cR708

`[ "${lines[4]}" = "# /usr/local/bin:/usr/bin:/bin" ]`

I have adopted that PR as a patch on top of 1.2.1 to resolve a bug report in debian, but package build failed due to this test failure

```
not ok 65 test works even if PATH is reset
# (in test file test/bats.bats, line 583)
#   `[ "${lines[4]}" = "# /usr/local/bin:/usr/bin:/bin" ]' failed
```
and since no lines were reported I cannot be sure but I think it might related to the fact that PATH in this session is `/usr/lib/ccache:/usr/sbin:/usr/bin:/sbin:/bin` .

**Comment by martin-schulze-vireso** [comment]
I don't think that this is the actual problem. The expected path is set in the test file `test/fixtures/bats/update_path_env.bats`.

**Comment by yarikoptic** [comment]
eh, I guess I will need to recall how to troubleshoot bats fails... I wish there was some magical introspection as of pytest (e.g. if the failing test line has `lines[?]` mentioned, it would print that value)

**Comment by yarikoptic** [comment]
indeed, likely my patch was incomplete since echoing the lines shows

```
# <1..1 /home/yoh/deb/gits/bats/lib/bats-core/preprocessing.bash: line 16: bats-preprocess: command not found # bats warning: Executed 0 instead of expected 1 tests>
```

**Comment by yarikoptic** [comment]
and since changes are quite extensive since the last release, I guess I am just doomed to wait for https://github.com/bats-core/bats-core/pull/403 or in general to release to happen...

**Comment by yarikoptic** [comment]
actually
```
$> git diff lib/bats-core/preprocessing.bash
diff --git a/lib/bats-core/preprocessing.bash b/lib/bats-core/preprocessing.bash
old mode 100644
new mode 100755
index 4bc8ebb..153d562
--- a/lib/bats-core/preprocessing.bash
+++ b/lib/bats-core/preprocessing.bash
@@ -13,7 +13,7 @@ BATS_OUT="${BATS_TMPNAME}.out" # used in bats-exec-file
 
 bats_preprocess_source() {
        BATS_TEST_SOURCE="${BATS_TMPNAME}.src"
-   bats-preprocess "$BATS_TEST_FILENAME" >"$BATS_TEST_SOURCE"
+ $BATS_LIBEXEC/bats-preprocess "$BATS_TEST_FILENAME" >"$BATS_TEST_SOURCE"
        trap 'bats_cleanup_preprocessed_source' ERR EXIT
        trap 'bats_cleanup_preprocessed_source; exit 1' INT
 }
```
seems to resolve it for me, so I will proceed with that one!
