### ISSUE TITLE
Cannot run subprocess in bats

### ISSUE THREAD

**Issue by sergerad** [bats-core/bats-core#419]
`Bats 1.1.0`

The following code hangs. The parallel job is not launched in parallel as expected.

```
@test "Something" {
    sleep 100 &
    echo hi
    kill %1
}
```

**Comment by sergerad** [comment]
Apologies I have the issue in an environment that is difficult to recreate. The example in the original post seems to work but when I try to run a `kubectl port-forward` command in bats as a subprocess, it hangs until I hit `ctrl+c`. It doesn't hang in my shell however.

**Comment by grouville** [comment]
If other people face this issue, here is the fix : 
```
@test "kubectl" {
    kubectl port-forward svc/### -n #### 8080:443 > /dev/null 2> /dev/null &
    pid=$!

    # Wait for the port-forward to exist
    while ! nc -vz localhost 8080 > /dev/null 2>&1 ; do
        # echo sleeping
        sleep 0.1
    done
    
    curl localhost:8080

    # Kill Pid
    pkill kubectl
}
```

**Comment by martin-schulze-vireso** [comment]
@grouville Thanks for the feedback. Could you please compare to what you where doing before to make the fix more obvious?

**Comment by grouville** [comment]
> @grouville Thanks for the feedback. Could you please compare to what you where doing before to make the fix more obvious?

Yes, sure. It's a reply to @sergerad's issue with kubectl. The script applies a port forward, and waits for the service to be ready. It also kills the process to avoid zombies at the end.

`kubectl port-forward` takes control of the tty, even when it's being run in background. This breaks bats. For every process that takes control of the shell, even when launched in background, you'll have to redirect STDOUT and STDERR like that `> /dev/null 2> /dev/null`.

```bash
while ! nc -vz localhost 8080 > /dev/null 2>&1 ; do
        # echo sleeping
        sleep 0.1
    done
```
the above code is a semi-clean way to check when the service is ready

**Comment by meleu** [comment]
Just in case someone came to this thread by googling why bats hangs when your test runs something in background, the solution is explained [here in the official documentation](https://bats-core.readthedocs.io/en/stable/writing-tests.html#file-descriptor-3-read-this-if-bats-hangs).

> To prevent this from happening, close FD 3 explicitly when running any command that may launch long-running child processes, e.g. `command_name 3>&-`.
