### ISSUE TITLE
Timing and writing to fd 3 messes-up pretty output

### ISSUE THREAD

**Issue by jjg-dressipi** [bats-core/bats-core#420]
I'm running 1.3.0 (great release BTW) and have a test which writes to fd 3
```
echo "# meh" >&3
```
Running with timings enabled and the tap formatter I get the expected output
```
ok 34 vfplot --format grd2, explicit in 261ms
ok 35 vfplot --format grd2, implicit in 276ms
# meh
ok 36 vfplot --format sag, explicit in 815ms
```
but with the pretty formatter (where I don't expect to see the `meh`) things seem to get messy
 ```
 ✓ vfplot --format grd2, explicit [263]
 ✓ vfplot --format grd2, implicit [272]
    mehot --format sag, explicit                                   36/40 in 12 sec
 ✓ vfplot --format sag, explicit [818]
```

**Comment by martin-schulze-vireso** [comment]
What is your rationale for writing to FD 3 instead of stdout/err?

**Comment by jjg-dressipi** [comment]
I understood that this was the recommended way to print custom messages, as [documented](https://github.com/bats-core/bats-core/blob/master/docs/source/writing-tests.md#printing-to-the-terminal).  This is output "about the test" rather than "the subject of the test".

**Comment by martin-schulze-vireso** [comment]
Thanks for pointing out the documentation. I think that is a bit outdated and may leave the wrong impression.

As stated there, your output to stdout/err will also be printed, but only if the test fails. If you are only interested in output on failures, stdout/err are sufficient. FD3 is only important for printing "directly" to the executing shell, with all the consequences that might entail.

**Comment by martin-schulze-vireso** [comment]
@jjg-dressipi Please test if the linked PR #426 works as intented for your example above.

**Comment by jjg-dressipi** [comment]
For master

**Comment by jjg-dressipi** [comment]
For master:

**Comment by jjg-dressipi** [comment]
For master
```
 ✓ vfplot --format grd2, explicit [294]
    mehot --format grd2, implicit                                                               37/53 in 12 sec
 ✓ vfplot --format grd2, implicit [202]
 ✓ vfplot --format sag, explicit [519]
```
for this branch
```
 ✓ vfplot --format grd2, explicit [146]
    mehot --format grd2, implicit                                                                37/53 in 8 sec
 ✓ vfplot --format grd2, implicit [155]
 ✓ vfplot --format sag, explicit [421]
```
so just the same I'm afraid

**Comment by martin-schulze-vireso** [comment]
Could you reduce it to a minimal example that I can run locally/in GHA?

**Comment by jjg-dressipi** [comment]
Ah sorry, I forgot to switch from your master to your bugfix branch ... in fact yes, is fixed
```
 ✓ vfplot --format list [12]
 ✓ vfplot --format grd2, explicit [163]
 ✓ vfplot --format grd2, implicit [152]
   meh
 ✓ vfplot --format sag, explicit [449]
 ✓ vfplot --format sag, implicit [439]
```
and indeed, does the pretty colouring of the output too:

![Screenshot from 2021-04-09 13-09-37](https://user-images.githubusercontent.com/20063975/114177898-db358900-9934-11eb-8d3f-3dda4fe7273b.png)

which is great -- many thanks.
