### ISSUE TITLE
The correctness of the naming of variables

### ISSUE THREAD

**Issue by piotrminkina** [bats-core/bats-core#421]
Hello, I have a comment on the documentation in the [writing-tests.md](../blob/master/docs/source/writing-tests.md), especially on the following part:

```quote
$BATS_TEST_FILENAME is the fully expanded path to the Bats test file.
$BATS_TEST_DIRNAME is the directory in which the Bats test file is located.
```

In my opinion, the description of a variable is inconsistent with its name. look at the picture below, which explains the correct names for the path elements:

![naming drawio](https://user-images.githubusercontent.com/2574153/113143760-d2ee9700-922c-11eb-8112-3f952927c974.png)

Best regards
Piotr Minkina

**Comment by martin-schulze-vireso** [comment]
Is there some official standard for this naming? I'd expect dirname to behave like the result of the command `dirname $filepath`, which would be in line with the current usage.

Regarding filepath vs filename I would concur. However, changing its meaning now would likely break many existing tests. We could duplicate it as filepath but that might be even more confusing.

If we want to change the existing variables, we need to break it very loudly which might not be feasible.

**Comment by martin-schulze-vireso** [comment]
I am closing this, since there has been no further feedback and a transition seems not feasible. Feel free to reopen if further discussion is needed.
