### ISSUE TITLE
bats fails to run on Windows (git bash)

### ISSUE THREAD

**Issue by iva2k** [bats-core/bats-core#424]
Running bats on Windows, installed locally, in git bash:

```bash
bats test
```

fails, output:

```bash
.../node_modules/bats/libexec/bats-core/bats: line 234: exec: bats-exec-suite: not found
.../node_modules/bats/libexec/bats-core/bats: line 234: bats-format-pretty: command not found
```

Environment:

Windows 10
bash for git: GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)

**Comment by iva2k** [comment]
I figured out what is happening.

I peeked into value of BATS_LIBEXEC set in bats script and added to PATH:

```bash
BATS_LIBEXEC="$(dirname "$(bats_readlinkf "${BASH_SOURCE[0]}")")"
export BATS_LIBEXEC
...
export PATH="$BATS_LIBEXEC;$PATH;."
...
# Added for debug of https://github.com/plasticrake/tplink-smarthome-api/issues/127
echo "BATS_LEBEXEC=$BATS_LIBEXEC"
```

```bash
BATS_LIBEXEC=C:/.../node_modules/bats/libexec/bats-core
```

When I run in bash:

```bash
export BATS_LIBEXEC=C:/.../node_modules/bats/libexec/bats-core
which bats-exec-suite
```

It gets an error:

```bash
which: no bats-exec-suite in (C:/.../node_modules/bats/libexec/bats-core:
```

Changing Windows-specific "C:/..." to bash-accepted form "/c/...":

```bash
export BATS_LIBEXEC=/c/.../node_modules/bats/libexec/bats-core
which bats-exec-suite
```

It gets no error:

```bash
/c/.../node_modules/bats/libexec/bats-core:
```

So in summary, bash on windows `dirname` returns "C:/...", but using it in PATH does not work, need to be "/c/...".

**Comment by iva2k** [comment]
The following fix makes bats run ok on Windows:

file node_modules/bats/libexec/bats-core/bats
```bash
- BATS_LIBEXEC="$(dirname "$(bats_readlinkf "${BASH_SOURCE[0]}")")"
+ BATS_LIBEXEC="$(cd "$(dirname "$(bats_readlinkf "${BASH_SOURCE[0]}")")"; pwd)"
```

**Comment by martin-schulze-vireso** [comment]
Thanks for the detective work. I'd like to get this reproduced in GitHub Actions. Do you have any idea on how to enforce a similar environment? The windows bash there seems to work fine in our tests. 

I am wondering why this is not an issue for BATS_ROOT too, since it is populated in a similar manner.

**Comment by iva2k** [comment]
Sorry, I don't know how to enforce same environment in Github Actions.

Besides tied to Windows platform, the issue could be version-specific, as it is a combined behavior of `dirname` returning "C:/" and $PATH working only with "/c/".

So I can only suppose that setting specific version of git bash might reproduce it.

**Comment by martin-schulze-vireso** [comment]
Our Github Actions script seems to run on the same version. e.g. https://github.com/bats-core/bats-core/pull/426/checks?check_run_id=2305418121 has: 

```
Run bash --version
GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)
```

However, this is not Windows 10. Unfortunately, Win10 is not available as platform in GHA.

I'd really like to have an independent reproducer to rule out issues in your local setup. This code has been around for a while so I'd assume someone should have complained already if this is a more widespread issue.

**Comment by jalseth** [comment]
@martin-schulze-vireso I'm running into this in GHA using the Server 2019 runner. See [the GHA run](https://github.com/plexsystems/konstraint/pull/146/checks?check_run_id=2328993594) and [the workflow config](https://github.com/jalseth/konstraint/blob/dccf5c497a8d367c999daa63cd92b7611d088f38/.github/workflows/pull_request.yaml#L33-L38). The issue seems to be that installing bats with `npm install -g bats` doesn't add all of the necessary binaries to $PATH, as @Iva2k discovered.

I was able to work around it by manually updating the path to include `C:\npm\prefix\node_modules\bats\libexec\bats-core`, but it would be good if the install on Windows through NPM updated the path automatically so `bats` can be used more easily.

**Comment by martin-schulze-vireso** [comment]
Ah, I did not notice that this was node related. That should make the reproducer easier. 

However, #430 May be more relevant with regard to your comment @jalseth .

**Comment by martin-schulze-vireso** [comment]
@jalseth I tried to reproduce the failure you linked above within the bats repository but I got no luck so far: https://github.com/martin-schulze-vireso/bats-core/runs/2448601250?check_suite_focus=true

There must be some difference but I can't find it.

**Comment by iva2k** [comment]
With `npm install -g bats` it uses environment $PATH, but I encountered the problem when it is a dependency and is installed locally. Local install amends environment's $PATH with local script path in $BATS_LIBEXEC, and that way is broken due to the requirement to have absolute Windows paths as '/c/...', not 'C:/...'. 

```bash
- BATS_LIBEXEC="$(dirname "$(bats_readlinkf "${BASH_SOURCE[0]}")")"
+ BATS_LIBEXEC="$(cd "$(dirname "$(bats_readlinkf "${BASH_SOURCE[0]}")")"; pwd)"
```

dirname returns "C:/..." and is broken
pwd returns "/c/..." and works

**Comment by martin-schulze-vireso** [comment]
To summarize my findings: `npm install -g bats` installs to C:/... while `npm install -g ./` only links there. In our CI environment the local checkout is on /d/, so the paths would not contain the C:/ part. After reproducing the issue via installing the local version via `.tgz` I found a more deeply nested problem with the stack trace creation that required a similar fix.
