### ISSUE TITLE
Formatter pretty: no support for file descriptor 3

### ISSUE THREAD

**Issue by delgurth** [bats-core/bats-core#428]
When installing bats from homebrew with default settings I'm running into an error on a simple "hello world" test-script:

```
#!/usr/bin/env bats
setup() {
    printf "setup\n" >&3
}

@test "example one" {
  run true
}
```

```
❯ bats -F pretty test
 /usr/local/Cellar/bats-core/1.3.0/lib/bats-core/formatter.bash: line 91: bats_tap_stream_unknown: command not found                                                                                                      1/1

❯ bats -F tap test
1..1
setup
ok 1 example one
```

I'm not sure what I need to put in: /usr/local/Cellar/bats-core/1.3.0/libexec/bats-core/bats-format-pretty . The following makes the error go away, but it doesn't print anything:

```
bats_tap_stream_unknown() {
  : log "$1"
}
```

If I remove the ":" it prints the messages in red, but it doesn't play nice with the test output being written.

**Comment by martin-schulze-vireso** [comment]
This has already been fixed in #412 but not yet released in a new version. As a general rule, you should try to emit valid tap output when printing to FD3, so you should prefix your output with `# `.
