### ISSUE TITLE
Messages are not captured in correct order

### ISSUE THREAD

**Issue by angelofenoglio** [bats-core/bats-core#432]
I have a python application for running jobs that uses the standard logging library to format and display information to stdout.
While testing the execution of some jobs, I found that if the job uses the `print` function to display information, the messages given by the application and such job are captured by bats in incorrect order.

Consider two jobs called `hello`, and `bye` that simply print "Hello" and "Bye" to stdout respectively.
After invoking `run myapp` the expected `$output` is (the lines with <> are the ones produced by the application and not the job) :
```
< Starting job `hello` >
Hello
< Completed job `hello` >
< Starting job `bye` >
Bye
< Completed job `bye` >
```
but I get:
```
< Starting job `hello` >
< Completed job `hello` >
< Starting job `bye` >
< Completed job `bye` >
Hello
Bye
```

Even though the relative order is preserved, is like the messages are treated as two different streams appended one after the other.
Note that if all messages are produced through one or the other channel exclusively, `$output` is as expected.

Is there a way to prevent this behavior?

**Comment by martin-schulze-vireso** [comment]
As you noticed, stdout and stderr are captured separately and printed as blocks. There is no bats flag to change this behavior, but you can redirect one into the other, e.g. via 2>&1, to get interlaced output, if you don't require the separation.

**Comment by angelofenoglio** [comment]
Oh! I'm sorry I was completely certain that the logging library was writing to stdout instead of stderr. Seems that I wasn't reading the documentation with enough attention, my bad.
Thanks for the tip!
