### ISSUE TITLE
bats hangs on cygwin

### ISSUE THREAD

**Issue by jkroepke** [bats-core/bats-core#449]
Hi there!

I'm currently to run bats on windows using cygwin.

All bat tests running under

* MacOS
* Linux
* Windows (using bash from msys2/git)

works well. 

Bats hangs only on windows if the bash.exe from cygwin is used.

I put some `set -x` on the setup files. I could see that bats hangs on the first tests.

Output 
```bash
# 3630 lines above ...
+ /cygdrive/d/a/helm-secrets/helm-secrets/tests/bats/core/libexec/bats-core/bats-exec-test -T /cygdrive/d/a/helm-secrets/helm-secrets/tests/unit/clean.bats test_clean-3a_helm_clean 1 1
# ...
+ test_clean-3a_helm_clean
Error: The operation was canceled.
```
GH actions output for reference: 
https://github.com/jkroepke/helm-secrets/pull/115/checks?check_run_id=2747777117

I'm using the lastet commit from the master branch.

I don't know how I could debug more into this issue. I don't if I'm affected from the fd3 issue, since the test suite works in general.

**Comment by martin-schulze-vireso** [comment]
Which bash version is cygwin using? Also, could reduce the example to a more minimal reproducer?

**Comment by jkroepke** [comment]
> GNU bash, version 4.4.12(3)-release (x86_64-unknown-cygwin)


> Also, could reduce the example to a more minimal reproducer?

I'll try

**Comment by jkroepke** [comment]
I figure out that gpg import command inside the setup function is the root cause here.
