### ISSUE TITLE
Error when trying to assign heredoc to variable within a test

### ISSUE THREAD

**Issue by noel-yap** [bats-core/bats-core#450]
I have the following:
```
@test "happy path" {
  # tabs in this definition must be preserved
  read -r -d '' expected <<-'EOF'
	expected output
	EOF
}
```

It's erroring with:
```
 ✗ happy path

   (in test file test.bats, line 30)
     `read -r -d '' expected <<-'EOF'' failed
```

**Comment by noel-yap** [comment]
The following works around the issue:
```
@test "happy path" {
  # tabs in this definition must be preserved
  expected="$(cat <<-'EOF'
	expected output
	EOF
  )"
}
```

**Comment by martin-schulze-vireso** [comment]
That is neither a problem with bats nor with heredocs. `read -d ''` expects a null terminator that is not found, so `read` will hit the end of file and exit non zero, which is dutifully reported as error by bats. Your second line of code does not use read, so the error does not occur.
