### ISSUE TITLE
Variable BATS_TEST_TMPDIR is empty

### ISSUE THREAD

**Issue by Jasha10** [bats-core/bats-core#453]
With the following in a bats file:
```bats
#!/usr/bin/env bats

@test "fail if passed > 1 arg" {
    [ "$BATS_FILE_TMPDIR" != "" ]
    [ "$BATS_TEST_TMPDIR" != "" ]
}
```
I am getting a failure. It seems that the special variables documented [here](https://bats-core.readthedocs.io/en/latest/writing-tests.html#special-variables) are not being set (though I have not tested them all).
I have installed bats with `npm install -g bats` and am invoking it on files in the present directory using `bats .`. Running Ubuntu 18.04.

**Comment by martin-schulze-vireso** [comment]
They are not yet released. Please select the appropriate documentation for your version (I'd assume 1.3.0)

**Comment by Jasha10** [comment]
Got it, thanks for the clarification :)

**Comment by martin-schulze-vireso** [comment]
Thanks for bringing this up again. I misconfigured readthedocs to default to the version latest instead of stable. This is fixed now.
