### ISSUE TITLE
Feature request: Allow `load` to support files ending in `.sh`

### ISSUE THREAD

**Issue by hyperupcall** [bats-core/bats-core#454]
The load function already sources files that end in `.bash` and files without a file extension. It would be very useful to load files that end in `.sh` for the same reasons as `.bash`

Edit: I went ahead and made a PR for this as it seems relatively simple to implement. Lemmie know if there is interest for merging this or if I should make any other changes

**Comment by martin-schulze-vireso** [comment]
I am not sure how far we should push that. You already can load `.sh` files by explicitly specifying the extension:

```
load 'file.sh`
```

will work as intended and will only give you headaches if you happen to have a `file.sh.bash` lying around, too. Your PR changes that such that you can write

```
load 'file'
```

and `load.sh` will be picked up. This further complicates the precedence rules:

1. ./file.bash
2. ./file
3. ./file.sh <- this is your new part
4. /usr/bin/file

@bats-core/bats-core What do you think about this suggestion?

**Comment by eankeen** [comment]
I see - I suppose now with this explicitly said, it is a bit harder to advocate for this feature.

But, I would still argue that it is quite unlikely that a person has more than one of: `./file.bash`, `./file`, `./file.sh` in any particular directory at any particular time anyways, even more so with multiple extensions. In my view, if this situation ever arises, any issues with order precedence will become immediate as an extensionless file specifier like 'file' is inherently vague

**Comment by hyperupcall** [comment]
Closing this as I have realized the value proposition of this feature seems quite marginal, especially at the expense of clarity
