### ISSUE TITLE
Feature request: support testdata directories

### ISSUE THREAD

**Issue by noel-yap** [bats-core/bats-core#456]
Context and forces:
Tests sometimes need test data.
Placing test data directly in test files makes the test files less readable.
Placing test data in a `testdata` subdirectory makes the test files more readable.
Since `bats` makes a copy of the bats script, it now doesn't know where to find the `testdata` subdirectory.
`${PWD}` could be used but only if `bats` is run in the same directory as the bats script.

One potential solution would be to define an environment variable (eg `BATS_SOURCE_DIR`) that point back to the source directory. There may be other solutions I haven't considered.

**Comment by martin-schulze-vireso** [comment]
I think `$BATS_TEST_DIRNAME` already solves this problem for you.
