### ISSUE TITLE
Feature request: support multiline shebangs

### ISSUE THREAD

**Issue by noel-yap** [bats-core/bats-core#457]
Context and forces:
Tests sometimes need test data.
This test data can be placed in a `testdata` subdirectory.
Since `bats` makes a copy of the bats script, it now doesn't know where to find the `testdata` subdirectory.
`${PWD}` could be used but only if `bats` is run in the same directory as the bats script.
A `SOURCE_DIR` environment variable could be defined within a multiline shebang. For example:
```
#!/bin/bash
tmpdir=$(mktemp -d)
trap 'rm -rf -- "${tmpdir}"' INT TERM HUP EXIT

test_script="${tmpdir}/$(basename "$0")"
# Strip out from the script everything after '!#'
sed -e '1,/^!#$/d' "$0" >"${test_script}"

# Call the new script
SOURCE_DIR="$(dirname "$(realpath "$0")")" \
    TEST_DIR="${tmpdir}" \
    "${GRAIL}/third-party/bash/bats-core/bin/bats" "${test_script}"

exit
!#

# rest of bats script
```

Request:
If bats itself supported multiline shebangs, the above becomes:
```
#!/bin/bash
SOURCE_DIR="$(dirname "$(realpath "$0")")"
!#

# rest of bats script
```

**Comment by martin-schulze-vireso** [comment]
As already discussed in #456, your example can be trivially solved with `$BATS_TEST_DIRNAME`.

In any case I don't see an advantage of using a multiline shebang over putting the same code in `setup`/`setup_file`. `$0` would be available as `$BATS_TEST_FILENAME` there.
