### ISSUE TITLE
Failure in Release action caused 1.3.0 not to deploy to Docker Hub

### ISSUE THREAD

**Issue by colindean** [bats-core/bats-core#458]
The logs are no longer available, but here's the failed run:

https://github.com/bats-core/bats-core/actions/runs/655551923

1.2.1 is the latest version available on Docker Hub:

https://hub.docker.com/r/bats/bats/tags

**Comment by martin-schulze-vireso** [comment]
Thanks for your report. We already have a fix for that in master that should make 1.4.0 available when it is released soon. Hence, we will skip 1.3.0 in docker to spend our available time on other issues.

**Comment by colindean** [comment]
Perfectly understandable. Thanks for your work.

**Comment by martin-schulze-vireso** [comment]
I will leave this issue open as a reminder until 1.4.0 has been released

**Comment by martin-schulze-vireso** [comment]
Wow, 1.4.0 also did not go through as planned because I merged the PR into the wrong branch. Had to release 1.4.1 and do some manual reruns until everything got through. I hope the next release becomes a bit smoother.
