### ISSUE TITLE
`trap` not firing

### ISSUE THREAD

**Issue by noel-yap** [bats-core/bats-core#460]
https://stackoverflow.com/questions/68164747/how-to-trap-in-bats

I have the following in some of my tests:
```
tmpdir=$(mktemp -d)
trap 'echo @@@@@@@@@@@@@@@@@@@ >&3' INT TERM HUP EXIT
```

But the I'm not seeing the expected output (obviously I'm wanting it to cleanup `${tmpdir}`).

I know there's a teardown feature but that `tmpdir` creation is actually in a function that can be called multiple times (and the `trap` will do a `trap -p` so they can be chained).

What needs to be done for this `trap` to work? Is there something else that can be done to accomplish what I would like?

**Comment by martin-schulze-vireso** [comment]
Defining your own traps inside tests can interfere with bats' internals. Please see the suggestions in https://github.com/bats-core/bats-core/issues/364#issuecomment-827773930 for more details.

**Comment by noel-yap** [comment]
In case anyone else runs into this, I found a way to do the cleanup in `teardown`. More detailed answer is in the Stackoverflow post.
