### ISSUE TITLE
$lines and $output polluted with extraneous text

### ISSUE THREAD

**Issue by caponecicero** [bats-core/bats-core#466]
My test is as follows:
```
@test "pathtest sender $MAILBOX" {
	run $pathtest sender $MAILBOX
	echo ${lines[0]}
	echo ${lines[1]}
	echo $output
	[ $status -eq 0 ]
	[ "${lines[0]}" = "/srv/mail/var/domain/bar.com/foo/~mt" ]
}
```
`$pathtest` has the name of the program to run `/srv/mail/lib/tools/tag/test/bin/pathtest`,  `$MAILBOX` is an email address -- `foo@bar.com` in this case.  `$pathtest mailbox foo@bar.com` transforms the string `foo@bar.com` into the following string:
```
/srv/mail/var/domain/bar.com/foo/~mt
```
It does that.  However when I try to test this with **bats**, I get:
```
 ✗ pathtest sender foo@bar.com
   (in test file test/sets/path, line 35)
     `[ "${lines[0]}" = "/srv/mail/var/domain/bar.com/foo/~mt" ]' failed
   Found no changes, using resolution from the lockfile
   /srv/mail/var/domain/bar.com/foo/~mt
   Found no changes, using resolution from the lockfile /srv/mail/var/domain/bar.com/foo/~mt

1 test, 1 failure
```
`${lines[0]`:  **_Found no changes, using resolution from the lockfile_**
`${lines[1]`:  **_/srv/mail/var/domain/bar.com/foo/~mt_**
`$output`:  **_Found no changes, using resolution from the lockfile /srv/mail/var/domain/bar.com/foo/~mt_**

Where did all the pollution come from?  This isn't at all what the docs say I'm supposed to get...  Is there some shell option that's set that's not supposed to be?  I've searched all of the **bats** source code for a message resembling **_Found no changes, using resolution from the lockfile_** and couldn't find it so I'm assuming it's coming from the shell.

This is on FreeBSD 13.0 using bash 5.1.8:
```
GNU bash, version 5.1.8(0)-release (amd64-portbld-freebsd13.0)
```

**Comment by martin-schulze-vireso** [comment]
This is not a bats Message. I'd wager it stems from the command in `run`. A quick websearch ties this exact wording to a Ruby tool: https://www.rubydoc.info/github/bundler/bundler/Bundler/Definition

**Comment by caponecicero** [comment]
Thanks for the tip.  I don't see any references to the message in the link you posted though.  

I don't see this message when I run this program from bash...and I have ruby warnings silenced with
```
#!/usr/bin/env -S ruby -W0
```
at the top of the program.

**Comment by martin-schulze-vireso** [comment]
Ruby is not a language I use regularly. However, the message is a debug message from a dependency manager, so I'd assume it is not silenced by a warning switch.

If the programm runs fine from a bash shell in the same environment, you should have a look at what env  vars have changed.

So far, this does not seem bats related, so I am closing this. Feel free to reopen if you find that the change of behavior is actually  triggered by bats.
