### ISSUE TITLE
Check stderr output

### ISSUE THREAD

**Issue by BraisGabin** [bats-core/bats-core#47]
Right now `run` merges `stdout` and `stderr` in `$output` this can be usefull for some use cases. But I can't assert that some error message was printend in `stderr` instead of `stdout`.

Can I check this ussing `run`?

**Comment by harleypig** [comment]
There are some possible options here: https://github.com/sstephenson/bats/issues/138

**Comment by Potherca** [comment]
Looks like this is being worked on in https://github.com/bats-core/bats-core/pull/2
