### ISSUE TITLE
What's the purpose of the grave accent ` in failure messages?

### ISSUE THREAD

**Issue by NorseGaud** [bats-core/bats-core#470]
Been there from day one: https://github.com/sstephenson/bats/commit/c850527cce7134f4adf4fe6dac07214678deb72b#diff-2285302ec7310b89fd9edfef3694598bebfa056fdbfd7e5d607026f64a68d734R80

It seems to work just fine when changing it to ' instead. I'd like to open this to discuss what potential downfalls there are of removing it.

**Comment by NorseGaud** [comment]
It makes code blocks really ugly:
<img width="681" alt="Screen Shot 2021-07-25 at 3 32 53 PM" src="https://user-images.githubusercontent.com/5896030/126911137-8ebb6ae0-3dce-45fd-92fa-d0aab1b9f7df.png">

**Comment by martin-schulze-vireso** [comment]
I think this is a more or less historc typographic gimmick https://en.wikipedia.org/wiki/Quotation_mark#Typewriters_and_early_computers. With regard to your example it might be better to use \` also for closing the command, which should fix the parsing and maybe enable syntax highlighting.

**Comment by NorseGaud** [comment]
@martin-schulze-vireso , so would you favor a PR for ending with ` or simply removing ` altogether?

**Comment by martin-schulze-vireso** [comment]
It really depends on the context. Could you try what the fully \`\` wrapped version looks like in the environment you showed above?

**Comment by NorseGaud** [comment]
```
❯ bin/bats --filter "^extended syntax" test/bats.bats
 ✓ extended syntax

1 test, 0 failures

❯ BATS_TRACE_LEVEL=1 bin/bats --filter "^extended syntax" test/bats.bats
 ✗ extended syntax
   (in test file test/bats.bats, line 329)
     `[ "${lines[7]}" = 'ok 2 a passing test' ]` failed
   + bats-exec-suite -x /Users/norsegaud/bats-core/test/fixtures/bats/failing_and_passing.bats

❯ BATS_TRACE_LEVEL=2 bin/bats --filter "^extended syntax" test/bats.bats
 ✗ extended syntax
   (in test file test/bats.bats, line 329)
     `[ "${lines[7]}" = 'ok 2 a passing test' ]` failed
   + bats-exec-suite -x /Users/norsegaud/bats-core/test/fixtures/bats/failing_and_passing.bats
   1..2
   suite /Users/norsegaud/bats-core/test/fixtures/bats/failing_and_passing.bats
   begin 1 a failing test
   not ok 1 a failing test
   # (in test file test/fixtures/bats/failing_and_passing.bats, line 2)
   #   `false' failed
   begin 2 a passing test
      
   ok 2 a passing test

1 test, 1 failure
```

Is this what you mean? So we'd instead potentially change it to end in \` too?

**Comment by martin-schulze-vireso** [comment]
No, I meant the environment from the screenshot above. I'd like to see if it fixes the  highlighting.

**Comment by jasonkarns** [comment]
I'd like to dig more into the rationale for it existing in the first place, before we change it. I've seen this pattern frequently enough in other heavily used shell scripts and tools that I don't believe it was accidental.

**Comment by NorseGaud** [comment]
https://pubs.opengroup.org/onlinepubs/9699919799/xrat/V4_xcu_chap02.html#tag_23_02_06_03

> Some implementations have allowed the end of the word to terminate the backquoted command substitution, such as in:
> "`echo hello"

**Comment by NorseGaud** [comment]
https://unix.stackexchange.com/questions/121927/why-bash-encapsulates-syntax-error-both-with-grave-accent-and-with-an-apostrophe

**Comment by martin-schulze-vireso** [comment]
> I'd like to dig more into the rationale for it existing in the first place, before we change it. I've seen this pattern frequently enough in other heavily used shell scripts and tools that I don't believe it was accidental.

I think this thread established well enough that it is a typographic hack for older, non utf systems. Maybe we can offer configuration variables that allow users to decide on the delimiters?

**Comment by shadowspawn** [comment]
For interest, Commander had a similar request to change the quotes used in error messages. After some research we accepted the change. My conclusion was it was a dated convention, and I referenced one of same links as https://github.com/bats-core/bats-core/issues/470#issuecomment-887803374

https://github.com/tj/commander.js/pull/915
