### ISSUE TITLE
ls X*.m after a run command fails incorrectly even though X.m exists

### ISSUE THREAD

**Issue by nars1** [bats-core/bats-core#471]
I noticed a failure in our nightly pipelines from a day ago. In that project, we use bats for automated tests. After some investigation, I have narrowed it down to a `bats` issue. Below is a simple test case that demonstrates the problem.

```sh
$ cat test.bats
@test "ls fails even though file exists" {
  run cat /dev/null
  touch X.m
  ls X*.m
}

$ bats test.bats
 ✗ ls fails even though file exists
   (in test file test.bats, line 4)
     `ls X*.m' failed
   ls: cannot access 'X*.m': No such file or directory

1 test, 1 failure
```
I do a `touch X.m` so I expect a `ls X*.m` to return `X.m`. But it fails with a `No such file or directory` error.

If I replace the `run cat /dev/null` in the above test with a `cat /dev/null`, the test passes. So the `run` somehow confuses the later `ls`.

I also verified that commit 2e2e5df (in the `git log` output below) works fine but commit 14e8b32 (and in turn 5218bbc) does not so that seems to be the cause of the regression. And that commit does mention `glob output` so does seem related to this issue.

```sh
$ git log --graph --oneline --all --pretty=format:'%h%d; %ai; %an; %s'
*   5218bbc; 2021-07-24 14:49:47 +0200; Martin Schulze; Merge pull request #158 from vonbrand/dont-glob-output
|\  
| * 14e8b32; 2018-11-06 10:17:28 -0300; Horst H. von Brand; Don't glob output
|/  
* 2e2e5df; 2021-07-24 01:09:23 +0200; Martin Schulze; Fix dockerhub export version
```

**Comment by martin-schulze-vireso** [comment]
I assume you are running from current master? The commit you fingered actually tries to solve an issue related to globbing by disabling it. In theory it should reenable it later in, but it seems that is not the case.

**Comment by nars1** [comment]
Yes I am running from current master.

**Comment by martin-schulze-vireso** [comment]
Could you please give #472 a spin on your system and see whether it fixes the issue?

**Comment by nars1** [comment]
Yes it does fix the issue. Thanks.
