### ISSUE TITLE
Check exit code and make TAP compliant output

### ISSUE THREAD

**Issue by lskatz** [bats-core/bats-core#486]
Hi, I want to run a command and see its stdout in realtime, but I also want to check its error code.  Something like

    run command | sed 's/^/# /' >&3
    if [[ "$status" == 1 ]]; then
      echo foo
    fi

Will the exit code be the sed command?  How can I check both the exit code and have real time output?  Thank you!

**Comment by martin-schulze-vireso** [comment]
`run` stores the output in `$output`, so you won't be able to pipe it and print it in realtime.
If you don't want to check the output yourself, you could do this:

```
(set -o pipefail; command | sed 's/^/# /' >&3)
if [[ $? == 1 ]]; then
```

May I ask why you want to see the output in realtime?

**Comment by lskatz** [comment]
Pipefail! Great idea, thanks! And the subshell parentheses will stop it from exiting right away? 

My program takes about an hour and so it is agonizing to wait and fix things incrementally. I just want to know right away what's happening.

**Comment by martin-schulze-vireso** [comment]
I am not sure whether bats should be used for developing command in this case. Bats will be useful for writing a pin down test but getting to a working state first via iterative development sounds very prohibitive with this turnaround time.

Anyways, I think this issue is solved.
