### ISSUE TITLE
Feature Request: Run a single test by name

### ISSUE THREAD

**Issue by theoretick** [bats-core/bats-core#489]
Hello, thanks for maintaining this important tool! 

I'd like to make a feature request for the ability to run a single test. This is essentially a port of the issue https://github.com/sstephenson/bats/issues/36 and that thread can be visited for some background and workarounds, but it would be great to have a native way of doing this.

**Comment by theoretick** [comment]
There's also a WIP PR on the original repo but I haven't dug into whether it can be directly ported over. If this is desirable I can try to finding some time to do so but was hoping to first get confirmation I'm not missing anything https://github.com/sstephenson/bats/pull/117/files

**Comment by martin-schulze-vireso** [comment]
Sounds a lot like the `-f` filter that is already in bats-core?

**Comment by theoretick** [comment]
@martin-schulze-vireso ah, lovely. I completely missed that when searching for single test. That works, thanks for the quick reply!
