### ISSUE TITLE
Add diffing support when a test fails

### ISSUE THREAD

**Issue by MichaelDimmitt** [bats-core/bats-core#490]
Are there current best practices for showing a diff when your test fails?

Is there a way we can build diffing it into bats-core?

## example of what I do currently:
hardcoded output just for readability and so people could run locally.

```bash
printDiff(){
  echo ;
  echo output;
  echo "$output";
  echo ;
  echo expected;
  echo "$expected";
  echo ;
  cmp <(echo "$output") <(echo "$expected") | cut -c 23-;
  echo ;
}

@test "a failure on line 1" {
  run bash two_fer.sh Alice
  expected=$(cat <<-END
test should fail
this is some text
END
  )
  output=$(cat <<-END
test should pass
this is some text
END
  )
  printDiff
  [[ "$output" == "$expected" ]]
}
@test "a failure on line 2" {
  run bash two_fer.sh Alice
  expected=$(cat <<-END
this is some text
test should fail
END
  )
  output=$(cat <<-END
this is some text
test should pass
END
  )
  printDiff
  [[ "$output" == "$expected" ]]
}
@test "a bad diff occurs if expected is 2 lines but output is 1 line" {
  run bash two_fer.sh Alice
  expected=$(cat <<-END
this is some text
test should fail
END
  )
  output=$(cat <<-END
this is some text
END
  )
  printDiff
  [[ "$output" == "$expected" ]]
}
```
<img width="700" alt="Screen Shot 2021-08-22 at 11 11 45 AM" src="https://user-images.githubusercontent.com/11463275/130360281-a6c657e5-8f18-441e-a6e0-3255651d0388.png">

**Comment by MichaelDimmitt** [comment]
## Why does this work ? 
If the test passes the terminal does not output the results of `echo` from printDiff

So the output only shows when the bash test fails.

**Comment by martin-schulze-vireso** [comment]
I think this would be a nice addition to [assert_output](https://github.com/bats-core/bats-assert#assert_output).

**Comment by MichaelDimmitt** [comment]
thanks for posting, I will play around with assert_output to see how best I can use it in my personal test suites

**Comment by martin-schulze-vireso** [comment]
Closing this since the feature would have to be implemented in https://github.com/bats-core/bats-assert and should be requested over there.
