### ISSUE TITLE
homebrew tap repo - for bats-core plugins

### ISSUE THREAD

**Issue by MichaelDimmitt** [bats-core/bats-core#492]
@martin-schulze-vireso , suggested I look into assert_output which is part of bats-assert

It was hard to understand how to install assert_output using homebrew

Has there been talk of creating a homebrew formula?

https://github.com/ztombol/bats-docs#homebrew

> OS X users can use Homebrew to install libraries system-wide (see note below for alternatives).

> The forumlae are in a tap for various shell utilities by @kaos, so enable the tap kaos/shell first.
```
$ brew tap kaos/shell
```
> Then install the desired libraries.
```
$ brew install bats-assert
$ brew install bats-file
```

### If a repo was created called homebrew-bats-core:
It is easy to create a formula, 
I could submit a pr with the correct information to add homebrew taps

1) bats-assert
2) bats-detik
3) bats-support
4) bats-file

### essentially install would look like the following:

```
$ brew install bats-core
```
Then install the desired libraries.
``` 
$ brew tap bats-core/bats-core
$ brew install bats-assert
$ brew install bats-file
$ brew install bats-detik
$ brew install bats-support
```

Homebrew recipes are easy to check because they use a url pointed to the github repo release.

**Comment by MichaelDimmitt** [comment]
yes,
just create a repo with a readme

https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap
> If hosted on GitHub, we recommend that the repository’s name start with homebrew- so the short brew tap command can be used.

once the repo is added it is easy to add the homebrew formulas in a pr 👍

**Comment by martin-schulze-vireso** [comment]
There you go https://github.com/bats-core/homebrew-bats-core. I am unsure who maintains the current bats-core on homebrew. I did nothing to update it to 1.4.1, but there is a release script...

**Comment by MichaelDimmitt** [comment]
Hi @martin-schulze-vireso , 

can you add a file, a readme or anything

it turns out I cant open a pr on an empty repo or fork an empty repo 😲

<img width="559" alt="Screen Shot 2021-08-30 at 11 16 12 PM" src="https://user-images.githubusercontent.com/11463275/131436095-27ad47e7-8b36-451e-b2b2-d33ec6e2b862.png">

**Comment by martin-schulze-vireso** [comment]
I am sorry, I wanted a clean repository but it was too clean... I added a README.md now, so you should be able to add a PR.

**Comment by MichaelDimmitt** [comment]
Thank you ! I will add the taps this weekend

**Comment by martin-schulze-vireso** [comment]
Since the repo has been opened I think this issue can be closed now.
