### ISSUE TITLE
Strange behavior from valgrind and bats on Rocky Linux (CentOS 8 clone)

### ISSUE THREAD

**Issue by shabiel** [bats-core/bats-core#494]
When you run bats, the executable gets converted to `/usr/bin/env`.

I tried coming up with the smallest test case.

```
docker run -it --rm rockylinux/rockylinux
yum install -y valgrind git
git clone https://github.com/bats-core/bats-core
cd bats-core/
./install.sh /usr/local/
valgrind bats
```

Output:
```
[root@93910245fc27 bats-core]# valgrind bats
==98== Memcheck, a memory error detector
==98== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==98== Using Valgrind-3.16.0 and LibVEX; rerun with -h for copyright info
==98== Command: /usr/bin/env
==98==
LANG=en_US.UTF-8
HOSTNAME=93910245fc27
PWD=/bats-core
HOME=/root
TERM=xterm
SHLVL=1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LESSOPEN=||/usr/bin/lesspipe.sh %s
_=/usr/bin/valgrind
OLDPWD=/
LD_PRELOAD=/usr/libexec/valgrind/vgpreload_core-amd64-linux.so:/usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so
==98==
==98== HEAP SUMMARY:
==98==     in use at exit: 0 bytes in 0 blocks
==98==   total heap usage: 42 allocs, 42 frees, 13,377 bytes allocated
==98==
==98== All heap blocks were freed -- no leaks are possible
==98==
==98== For lists of detected and suppressed errors, rerun with: -s
==98== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

I thought that this is a problem with perhaps an older version of Valgrind. I downloaded the latest stable (3.17.0) and compiled from source. Same problem.

**Comment by martin-schulze-vireso** [comment]
Bats is only a bash script. Therefore, it dies a shebang to be executed via bash. See https://github.com/bats-core/bats-core/blob/8e9f35aa794e38cef6cc9da21003730cce00c3bb/bin/bats#L1

I think valgrind can only run on the interpreter, not the interpreted source.

**Comment by shabiel** [comment]
@martin-schulze-vireso Thank you for the answer.

**Comment by shabiel** [comment]
For posterity:

We discovered on Centos 8 and Rocky Linux that running valgrind against BATS really executes /usr/bin/env. Centos 7 and RHEL 8 do run BATS.

Not sure what the issue is, but it's a deeper Linux issue.

**Comment by martin-schulze-vireso** [comment]
Thanks for the followup. You could force valgrind to executed `bash bats` but I don't know how it will deal with subshells for executables from libexec/

What are you trying to achieve?

**Comment by shabiel** [comment]
At this point, it's a moot issue since we are re-working the code so that bats calls valgrind rather than the other way around. Thank you anyways. We are very happy BATS users at YottaDB (https://gitlab.com/YottaDB/DBMS/YDBOcto).
