### ISSUE TITLE
tracing.bash: line 30: BASH_SOURCE[$i + 1]: unbound variable

### ISSUE THREAD

**Issue by jkroepke** [bats-core/bats-core#500]
Hi,

it's a follow from #497. I'm running bats (sha commit a34fc9d) now - https://github.com/jkroepke/helm-secrets/tree/update-bats/tests/bats

I'm still getting unbound variable issues, now each test:

```
not ok 2 clean: helm clean --help
# (from function `teardown' in file tests/unit/../lib/helper.bash, line 183,
#  from function `bats_teardown_trap' in file tests/bats/core/libexec/bats-core/bats-exec-test, line 88,
#  from function `bats_perform_test' in file tests/bats/core/libexec/bats-core/bats-exec-test, line 206,
#  from function `main' in test file tests/bats/core/libexec/bats-core/bats-exec-test, line 234)
#   `bats_perform_test' failed
# /home/runner/work/helm-secrets/helm-secrets/tests/bats/core/lib/bats-core/tracing.bash: line 30: BASH_SOURCE[$i + 1]: unbound variable
not ok 3 clean: Directory not exits
# (from function `teardown' in file tests/unit/../lib/helper.bash, line 183,
#  from function `bats_teardown_trap' in file tests/bats/core/libexec/bats-core/bats-exec-test, line 88,
#  from function `bats_perform_test' in file tests/bats/core/libexec/bats-core/bats-exec-test, line 206,
#  from function `main' in test file tests/bats/core/libexec/bats-core/bats-exec-test, line 234)
#   `bats_perform_test' failed
# /home/runner/work/helm-secrets/helm-secrets/tests/bats/core/lib/bats-core/tracing.bash: line 30: BASH_SOURCE[$i + 1]: unbound variable
not ok 4 clean: Cleanup
# (from function `teardown' in file tests/unit/../lib/helper.bash, line 183,
#  from function `bats_teardown_trap' in file tests/bats/core/libexec/bats-core/bats-exec-test, line 88,
#  from function `bats_perform_test' in file tests/bats/core/libexec/bats-core/bats-exec-test, line 206,
#  from function `main' in test file tests/bats/core/libexec/bats-core/bats-exec-test, line 234)
#   `bats_perform_test' failed
# /home/runner/work/helm-secrets/helm-secrets/tests/bats/core/lib/bats-core/tracing.bash: line 30: BASH_SOURCE[$i + 1]: unbound variable
```

Source: https://github.com/jkroepke/helm-secrets/pull/151/checks?check_run_id=3918290100

> (from function `teardown' in file tests/unit/../lib/helper.bash, line 183,

In this line, there is the function itself defined. 

Source: https://github.com/jkroepke/helm-secrets/blob/7479627372afc54572f46ee905a608881752d34b/tests/lib/helper.bash#L183.

I created a new issue, since the old is close. Let me know if this is fine

**Comment by jkroepke** [comment]
I can confirm that. move teardown from helper to testfile resolve this issue.

**Comment by martin-schulze-vireso** [comment]
Btw. during skimming I noticed some code in setup/teardown that might profit from `setup_file`/`teardown_file` and the new temporary directories per suite/file/test.

**Comment by jkroepke** [comment]
Exactly! 

But upgrade bats in combination with bashcov never worked. But now I gain the time to look deeper into this and created issues here. 

Lots of own logic can be replaced by bats logic now.

Thanks for the quick fixes.
