### ISSUE TITLE
Include all support libraries in the Docker image

### ISSUE THREAD

**Issue by rombert** [bats-core/bats-core#518]
**Is your feature request related to a problem? Please describe.**
I am trying to setup a Docker-based validation process using `bats`. Our tests make use of `bats-assert` and `bast-support`, and those are not included in the `bats/bats` Docker image.

**Describe the solution you'd like**
Include all optional libraries in the Docker image. Alternatively, provide an additional image with those included, if adding more libraries to the base one is not desirable.

**Describe alternatives you've considered**
We considered building our own image, but having all libraries in the official Docker image is cleaner and has less potential of becoming stale.

**Additional context**
Thanks for an awesome tool!

**Comment by martin-schulze-vireso** [comment]
I think this is a good idea. Obviously, we can't embed all plugins. However, we can pull in all under the bats-core namespace. It is probably best to wait for #27 for easier integration.

**Comment by rombert** [comment]
Thanks for considering this. In the meantime, we built our own simplistic image, but it would be good to not need it:

```
FROM bats/bats:latest as bats

RUN apk add --no-cache git
RUN cd /opt/bats/lib && git clone https://github.com/bats-core/bats-assert.git
RUN cd /opt/bats/lib && git clone https://github.com/bats-core/bats-support.git
```

**Comment by martin-schulze-vireso** [comment]
Waiting for #27 to ease usage.

**Comment by martin-schulze-vireso** [comment]
Since #27 has been merged, this is now unblocked.

**Comment by martin-schulze-vireso** [comment]
bats-assert#33

**Comment by brokenpip3** [comment]
Do you need help with this PR? Considering I created this action: https://github.com/brokenpip3/setup-bats-libs it could be great if we can use the same path for the bats libraries.

**Comment by martin-schulze-vireso** [comment]
You are welcome to send PRs. 

Maybe we can even migrate the action repo under bats-core to make it more official. @bats-core/bats-core what is your opinion in this?

**Comment by brokenpip3** [comment]
>Maybe we can even migrate the action repo under bats-core to make it more official.

Sure, will be great from my pov :)

>You are welcome to send PRs.

Cool will prepare something this week

**Comment by brokenpip3** [comment]
@martin-schulze-vireso I created a draft PR: https://github.com/bats-core/bats-core/pull/674 let me know if the way of installing the libs look ok to you, I added only bats-support for the moment so you can review it.
I also took the chance to do a couples of other improvements, let me know, thanks!
