### ISSUE TITLE
Allow setting a context or suite name

### ISSUE THREAD

**Issue by docwhat** [bats-core/bats-core#521]
**Is your feature request related to a problem? Please describe.**

I find myself writing lots of prefixes in my test descriptions. example:

```bats
@test "foo(): accepts negative numbers" {
	run foo -20
	assert_success
}

@test "foo(): accepts positive numbers" {
	run foo 20
	assert_success
}
```

I do this so I can more easily identify which file a test is from and to make
using the `--formatter` flag easier to use.

**Describe the solution you'd like**

I would like to be able to set the prefix once-per-subject instead of once-per-test.

Some ideas:

- Auto-prefix based on filename. e.g., `foo.bats` would prepend "`foo: `" to each test in the file.
- Allow setting a file wide title in the `setup`:

    ```bats
    setup() {
        load test_helper
        bats-set-suite-name "foo()"
    }
    ```

- Add a wrapping method (like rpsec's `context` and `describe`):

    ```bats
    # bats syntax
    @context "foo()" {
        @test "accepts negative numbers" {
            run foo -20
            assert_success
        }

        @test "accepts positive numbers" {
            run foo 20
            assert_success
        }
    }

    ```

    ```sh
    # comment syntax
    context_foo() { # @context
        accepts_negative_numbers() { # @test
            run foo -20
            assert_success
        }

        accepts_positive_numbers() { # @test
            run foo 20 
            assert_success
        }
    }
    ```

**Describe alternatives you've considered**

Using variables, but you still need to remember to add the variable to the test name.

**Additional context**

This is a common feature in other testing frameworks though how easy it is to use varies.

**Comment by martin-schulze-vireso** [comment]
Sounds a lot like #97

**Comment by martin-schulze-vireso** [comment]
As a quick hack, try this:

```
setup() {
        BATS_TEST_DESCRIPTION="$(basename "$BATS_TEST_FILENAME"): $BATS_TEST_DESCRIPTION"
}
```

**Comment by docwhat** [comment]
It works... but as you say, only for the tap formatter.

**Comment by martin-schulze-vireso** [comment]
With #561 being landed, this should be possible now, via specifying BATS_TEST_NAME_PREFIX.
