### ISSUE TITLE
Exit test on error despite background processes

### ISSUE THREAD

**Issue by jbriales** [bats-core/bats-core#524]
Currently a test case run will be blocked until all underlying background processes are done, regardless of the test output.

I.e. e.g.
```sh
@test "foo" {
  sleep 100s &
  false
}
```
will take 100s to complete, even if it's clear that the test failed in a few ms.

A potential workaround is to kill bg processes, with e.g. `kill $(jops -p)`
BUT this does not always work, depending on how complex and nested the jobs are within the main command,
PLUS it feels right that the test framework is able to optimize for the early exit here.

Would it be possible for `bats` to finish the test on error regardless of bg processes?

**Comment by martin-schulze-vireso** [comment]
Please see #205. This is being worked on.
