### ISSUE TITLE
Junit formatter: incorrect failure when writing to FD 3 in teardown_file

### ISSUE THREAD

**Issue by vreynolds** [bats-core/bats-core#531]
**Describe the bug**
Writing to FD 3 in `teardown_file` always reports a `<failure>` in the Junit report. This doesn't happen when writing to FD 3 in `@test`, `setup_file` or `teardown`. Seems to be related to #360 .

**To Reproduce**
Test file:
```
#!/usr/bin/env bats

teardown_file() {
    echo "# foobar" >&3
}

@test "My test" {
	[ 0 -eq 0 ]
}
```

Junit report file:

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites time="0">
<testsuite name="my-test.bats" tests="1" failures="0" errors="0" skipped="0" time="0" timestamp="2021-12-29T19:56:01" hostname="blah">
    <testcase classname="my-test.bats" name="My test" time="0">
        <failure type="failure">foobar</failure>
    </testcase>

</testsuite>
</testsuites>
```

**Expected behavior**
Junit report does not contain a `<failure>` tag.

**Environment (please complete the following information):**
 - Bats Version 1.5.0
 - OS: MacOS
 - Bash version: 3.2.57

**Additional context**

**Comment by martin-schulze-vireso** [comment]
Thanks for the report. May I ask why `teardown_file` is writing to FD3 instead of stdout/stderr?

**Comment by vreynolds** [comment]
> May I ask why `teardown_file` is writing to FD3 instead of stdout/stderr?
> 

We're writing a status update along the lines of "cleaning up filesystem..." that we want to unconditionally show in the test output.
