### ISSUE TITLE
bats does not recognize stderr output

### ISSUE THREAD

**Issue by davehouser1** [bats-core/bats-core#542]
**Describe the bug**
When testing $stderr output, $stderr is blank when its obviously not.

**To Reproduce**

1. Copy this script into its own empty directory

```bash
#!/bin/bash

test_dir=./test_dir

function1(){
    if [[ ! -d "$test_dir" ]]; then 
        >&2 echo "error"
        exit 1
    fi 
}

main(){
    function1
    echo "[+] Done."
}


if [[ "${BASH_SOURCE[0]}" == "${0}" ]];then
  main
fi
```
2. `chmod +x thisscript.sh; ./thisscript.sh 1>/dev/null`
3. `error` should appear

```
$./thisscript.sh 1>/dev/null
error
```

4. Now copy this bats tests file into the same directory

```
#!/usr/bin/env bats

setup() {
  source "./thisscript.sh"
  cd "$BATS_TEST_TMPDIR"
}

@test "Test if directory not created" {
  run function1
  echo "Status received: $status"
  echo "stderr output: $stderr"
  [ "$stderr" == "error" ]
  [ "$status" -eq 1 ]
}
```

5. `chmod +x thisscript.bats;./thisscript.bats`
6. bats shows nothing for stderr when there obviously is stderr output

```
$./thisscript.bats
x Test if directory not created
   (in test file thisscript.bats, line 11)
       '[ "$stderr" == "error" ]' failed
    Status received: 1
    stderr output:
````
 
**Expected behavior**
Bats should not fail on this test `[ "$stderr" == "error" ]' failed`.
The test should pass as output is "error" and status is "1"
Also bats should show `stderr output: error` as "error" is sent to stderr

**Environment (please complete the following information):**
 - Bats Version: 1.5.0
 - OS: Ubuntu 18.04.06
 - Bash version: 4.4.20(1)-release x86_64

**Additional context**
This test passes if I remove `[ "$stderr" == "error" ]` from the test. So the status code is being recognized, but stderr is not.

**Comment by martin-schulze-vireso** [comment]
By default `run` captures stderr and stdout interleaved in `$output`. You have to specify 
`--separate-stderr` to use `$stderr`. See https://bats-core.readthedocs.io/en/stable/writing-tests.html#run-test-other-commands

**Comment by martin-schulze-vireso** [comment]
You obviously found out about `$stderr` but not about the flag. it seems the documentation is lacking. Could you describe how you found this feature?

**Comment by davehouser1** [comment]
> By default run captures stderr and stdout interleaved in $output. You have to specify
> run --separate-stderr function1 to use $stderr. See https://bats-core.readthedocs.io/en/stable/writing-tests.html#run-test-other-commands

Forgive me I am new to using bats. The above worked , thank you. 

> Could you describe how you found this feature?

I found someone was using it in a tutorial on a website. Unfortunately I am unable to find the website I found it on right now. I obviously was using the feature incorrectly.

**Comment by martin-schulze-vireso** [comment]
Thanks for the feedback. Please leave a link to the tutorial if you find it again.
