### ISSUE TITLE
Run tests on sub functions inside of a function

### ISSUE THREAD

**Issue by davehouser1** [bats-core/bats-core#543]
**Is your feature request related to a problem? Please describe.**
I am looking for a way I can tests sub functions inside of a function with using `run` in my bats test. I am not sure if there is a way to accomplish this, if there is I could not find it. I will describe what is failing for me.

1. Copy this script into test-subfunction.sh

```bash
#!/usr/bin/env bash

main(){

    main2(){
        echo "You are inside main2"
    }

    echo "You are inside inside main"
    main2
}


if [[ "${BASH_SOURCE[0]}" == "${0}" ]];then
  main
fi
```

2. Copy this bats test into test-subfunction.bats in the same directory of test-subfunction.sh

```
#!/usr/bin/env bats

setup() {
    source ./test-subfunction.sh
}

@test "Can I access this sub function and test it?" {
    run main2
    echo "Output: $output"
    [[ "$output" =~ "main2" ]]
    [ "$status" -eq 0 ]
}
```

3. run `bats ./test-subfunction.bats` I get this output

```
$ bats ./test-subfunction.bats
x Can I access this sub function and test it?
   (in test file test-subfunction.bats, line 10)
     `[[ "$output" =~ "main2" ]]' failed
   Output: /usr/local/lib/bats-core/test_functions.bash: line 37: main2: command not found

1 test, 1 failure
```

**Describe the solution you'd like**
I want a way I can test sub functions in my scripts (A function in a function) is there a way to do this? Would be nice if I can just call the sub function directly, like this:

```
@test "Method to call sub function" {
    run main2
}
```

Although without logic to identify if that function name is not somewhere else in the main code that maybe difficult to implement. Maybe a way to `run` the main function, but specify a subfuction, that way it can be parsed though and utilized like so:

```
@test "Method to call sub function" {
    run main{main2}
}
```

**Describe alternatives you've considered**
The only way I found to be able to tests sub functions, is dont test sub functions. What I mean is, I literally need to pull my sub functions out of their function and make them global functions. I dont like doing this though as it makes a mess of functions outside of the context of where they would be called in the code. 

**Additional context**
Again, if there is a way to test sub functions I am not aware of, please share how to. However I combed through the [documentation ](https://bats-core.readthedocs.io/en/stable/writing-tests.html) and did not find a way to accomplish what I am trying to do.

**Comment by martin-schulze-vireso** [comment]
That is a bash Iimitation. The function main2 will be defined when main is executed. If you want to test it, you should pull it out of main to declare it unconditionally.

**Comment by martin-schulze-vireso** [comment]
That is a bash Iimitation. The function main2 will be defined when main is executed. If you want to test it, you should pull it out of main to declare it unconditionally.

**Comment by davehouser1** [comment]
Ah ok. So testing subfunctions is not supported in bats-core at this time?

**Comment by martin-schulze-vireso** [comment]
Not without running the declaring function itself. See for example https://stackoverflow.com/a/31166245

**Comment by davehouser1** [comment]
@martin-schulze-vireso makes sense. Def do not want to have to call the primary function first as then it will run all operations inside that function first each time its called. This could cause errors in my codes logic as other sub functions may need to be run before a sub function I am testing also it looks inefficient.
I plan to convert all my subductions to standard global functions, this will support testing with bats. Thanks! Will close this issue out as bash does not support my requirement.
