### ISSUE TITLE
support a way to test variables values inside of functions

### ISSUE THREAD

**Issue by davehouser1** [bats-core/bats-core#544]
**Is your feature request related to a problem? Please describe.**
Is there a way to test a variables value if it was changed in the function? I tried to do the following but it does not work:

```
#!/usr/bin/env bash

var1=""
var2="dog"
var3="2"

func2(){
    echo "You are inside func2"
    var1="100"
    var2="cat"
    var3="1"

}


func1(){
    echo "You are inside func1"
}

main(){
    func1
    func2
}


if [[ "${BASH_SOURCE[0]}" == "${0}" ]];then
  main
fi

```

My bats tests
```
#!/usr/bin/env bats

setup() {
    source ./test-vars.sh
}

@test "func1 var test" {
    run func1
    echo "Output: $output"
    [ "$var2" == "dog" ]
    [ "$status" -eq 0 ]
}


@test "func2 var test" {
    run func2
    echo "Output: $output"
    [ "$status" -eq 0 ]
    [ "$var2" == "cat" ]
}

```

But when I run my tests I get the following: 

```
$ bats ./test-vars.bats

* func1 var test
x func2 var test
   (in test file test-vars.bats, line 19)
     `[ "$var2" == "cat" ]' failed
   Output: You are inside func2
   var1: 100
   var2: cat
   var3: 1
```

It seems that bats is unable to see variable changes after the function completes even though the variables are being changed. I would like to find a way to check variables if they are changed by the function. 

**Describe the solution you'd like**
I would like bats to recognize when variables change inside of a function and be able to access those variables values in my tests.

**Describe alternatives you've considered**
The only way I was able to get this to work was to literally echo the output of the variable in the function like this, then I could test its output, but that means all my scripts would need to echo the output, not willing to do that.

Adjusted function:
```
func2(){

    var1="100"
    var2="cat"
    var3="1"
 
    echo "var1: $var1"
    echo "var2: $var2"
    echo "var3: $var3"

}
```
Adjusted test:
```
@test "func2 var test" {
    run func2
    [[ "$output" =~ "cat" ]]
    [ "$status" -eq 0 ]
}
```

**Additional context**
I tried changing the variables with functions like this, but it did not help:

```
changevar1(){ var1="100" ; }
changevar2(){ var2="cat"; }
changevar3(){ var3="1"; }

func2(){

    changevar1
    changevar2
    changevar3

}
```
I tried to echo the output of the variables like the following. This showed that the output from the script showed the variables changed. But bats refuses to see that output. 

```
@test "func2 var test" {
    run func2
    echo "Output: $output"
    echo $var1
    echo $var2
    echo $var3
    [ "$var2" == "cat" ]
    [ "$status" -eq 0 ]
}
```

Is there anyway to gather the variable new values after a run statement in bats outside of echoing them in the script and reading the output? Or is this just another limitation of bash?

**Comment by martin-schulze-vireso** [comment]
`run` uses a subshell to captures the output of the command, so the variable Changes are lost. However, you can call the function without run to observe its non-local variables.

**Comment by davehouser1** [comment]
Just got around to testing this. Calling the function works without run. I am closing this.
