### ISSUE TITLE
bats 1.5.0 does not write an output file

### ISSUE THREAD

**Issue by HarryWeppner** [bats-core/bats-core#549]
**Describe the bug**

No output file is written.

**To Reproduce**
1. `bats -F junit math.bats`

**Expected behavior**

An XML test result file `math.bats.xml` is written to the current working directory.

**Environment (please complete the following information):**
 - Bats Version 1.5.0
 - OS: Linux or macOS
 - Bash version: GNU bash, version 4.2.46(2)-release

**Additional context**

Appears to be a regression and reproduces also when using an `--output <dir>`. Used example `math.bats` from the docs

```
#!/usr/bin/env bats

@test "addition using bc" {
  result="$(echo 2+2 | bc)"
  [ "$result" -eq 4 ]
}

@test "addition using dc" {
  result="$(echo 2 2+p | dc)"
  [ "$result" -eq 4 ]
}
```

**Comment by martin-schulze-vireso** [comment]
There was a breaking change in 1.3.0: formatters(`-F`) only change the stdout output. If you want a report, you need to use `--report-formatter` now.

**Comment by HarryWeppner** [comment]
Argh - I missed that completely. In the future, would recommend to adhere to semantic versioning and bump the major version number when breaking changes are introduced.
Thank you for clarifying!

**Comment by martin-schulze-vireso** [comment]
Yes, we actually use semantic versioning and I was really torn on that. This was intended as a bugfix, since it was a mistake to make the junit formatter behave in this way in the first place.

**Comment by andrejpan** [comment]
From my point of view documentation currently states that both flags are doing the same. An additional sentence that the `--report-formatter` actually writes a report to file would be appreciated. 

```
 -F, --formatter <type>    Switch between formatters: pretty (default),
                              tap (default w/o term), tap13, junit
 --report-formatter <type> Switch between reporters (same options as --formatter)
```

**Comment by martin-schulze-vireso** [comment]
@andrejpan can you provide a PR for that?
