### ISSUE TITLE
docker execution error bash: bats: No such file or directory

### ISSUE THREAD

**Issue by johnqa** [bats-core/bats-core#551]
**Describe the bug**
I have an error when I try to execute my tests with bats using the docker approach. My tests are in a file in `/home/user/tests` folder

**To Reproduce**
`docker run --rm -it -v "/home/user/tests:/code" bats/bats:latest /code`
Error:
`bash: bats: No such file or directory`

**Environment (please complete the following information):**
 - Bats Version latest
 - OS: RHEL7

**Additional context**

**Comment by martin-schulze-vireso** [comment]
I cannot reproduce the problem as described. When I run your code (using 1.5.0 as latest), I get:
```
Error: Test file "/code/code" does not exist
```

Are you using the official image or are you working with an image derived from that?

**Comment by cbandy** [comment]
I've just run into the same thing.

```
● docker inspect --format '{{.RepoDigests}}' docker.io/bats/bats:1.7.0
[bats/bats@sha256:c707c5b7f9afd49da3e8a94248b03832e8b427f1b8f1ae9ec3cfdc5596d9c9f4]

● docker run --rm docker.io/bats/bats:1.7.0
bash: bats: No such file or directory

● docker run --rm docker.io/bats/bats:1.7.0 --help
bash: bats: No such file or directory

● docker run --rm --entrypoint=bash docker.io/bats/bats:1.7.0 -c 'command -v bats'
/usr/local/bin/bats
```

**Comment by martin-schulze-vireso** [comment]
Can you give more details about your environment? I still can't reproduce this in my Linux system.

**Comment by cbandy** [comment]
This is on the Linux that comes with a Chromebook, [Crostini](https://chromeos.dev/en/linux). It's a Debian bullseye, but it's a container itself. Something akin to docker-in-docker. That said, I don't recall this happening with any other images.

```
● docker system info
Client:                                                                    
 Debug Mode: false               
 Plugins:         
  buildx: Docker Buildx (Docker Inc., v0.8.2)
                                     
Server:             
 Containers: 2       
  Running: 0 
  Paused: 0                 
  Stopped: 2
 Images: 67                   
 Server Version: 19.03.15                                                  
 Storage Driver: btrfs                                                     
  Build Version: Btrfs v4.7.3  
  Library Version: 101
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.114-16024-gbdf1547bd4f4
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 6.469GiB
 Name: penguin
 ID: AUML:XMC2:SP7W:Y2YW:2TO2:QN42:GCFC:3IZG:LITK:Z5BS:EII4:ZFYK
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

I tried the same image on a different machine, using podman inside an AlmaLinux VM, and experienced no issues.

**Comment by chilversc** [comment]
I ran into this issue. It appears to be caused by the current version of bash https://github.com/bats-core/bats-core/issues/564

## Testing the current 1.7.0 docker image with `bashvar=latest`

```
bash-5.1# test -w /tmp; echo $?
1
bash-5.1# bash bats
bash: bats: No such file or directory
bash-5.1# bash -c bats
Error: BATS_TMPDIR (/tmp) is not writable
```

In this test I confirm the `test -w` bug is present. I then try to run bats using `bash bats` to replicate the standard entrypoint of `tini -- bash bats`. Repeating the command with the `-c` flag will execte `bats`, but then produces the `test -w` issue.

## Testing the current 1.7.0 docker image with `bashver=5.1.4`

```
bash-5.1# test -w /tmp; echo $?
0
bash-5.1# bash bats
Error: Must specify at least one <test>
```

Run `test -w` to confirm that the bug is not present in bash `5.1.4`. This time the `bash bats` command runs correctly, the error expected as no tests were provided.

**Comment by chilversc** [comment]
To follow up I've done some deeper digging and added a comment to the related issue, https://github.com/bats-core/bats-core/issues/564#issuecomment-1193011159

Check the runc and docker versions you're using. If it's docker in docker then you likely need the correct versions of runc and docker for both the host and dind container to ensure that neither seccomp layers block the call with `EPERM` and correctly return `ENOSYS` (or for newer kernels permit the syscall).

**Comment by martin-schulze-vireso** [comment]
I just created the new tag [latest-no-faccessat2]([latest-no-faccessat2](https://hub.docker.com/layers/bats/bats/bats/latest-no-faccessat2/images/sha256-1ea5b50f3dbcc3ef53f93f4308fc4796dd88eb8ceef17863a085a9629d81adfc?context=explore)) could you have a try?

**Comment by cbandy** [comment]
Looking good so far:

```
● docker run --rm docker.io/bats/bats:latest-no-faccessat2 --help   
Bats 1.7.0
Usage: bats [OPTIONS] <tests>
       bats [-h | -v]
…
```
