### ISSUE TITLE
Missing name of the test at tap13 format output when timing is required

### ISSUE THREAD

**Issue by wenscarl** [bats-core/bats-core#555]
**Describe the bug**
When the output format is selected to be tap13 and timing option is selected by -T, the names of failed tests will not be shown.

**To Reproduce**
A test.bats looks like
-----------------------------------------------------
```
load $HOME/test/'test_helper/batsassert/load.bash'
load $HOME/test/'test_helper/batscore/load.bash'

@test "TestToFail" {
  assert_output "None"
}
```
bats -T -F tap13 test.bats gives the following output,
```
TAP version 13
1..1

  ---
  duration_ms: 6
  message: |
     (from function `assert_output' in file /root/test/test_helper/batsassert/src/assert.bash, line 239,"
      in test file ./script.bats, line 35)"
       `assert_output "dd"' failed"
     -- output differs --"
     expected : None"
     actual   :"
     --"
  ...
```

------------------------------------------------------

**Expected behavior**
Expect to see `not ok 1 TestToFail` in the output.

**Comment by martin-schulze-vireso** [comment]
I tried to reproduce this but the code works as expected on my system. Can you provide the following information:

- Bats version
- Bash version
- operating system
- version/url of the helper libraries

Also, you are `load`ing a library called batscore. I assume this is bats-support?

**Comment by wenscarl** [comment]
I found that the issue appears as long as timing option(-T) is turned on even without loading other library.  Updated.
Bats-core version: v1.6.0
Bash version: 5.0.17(1)
OS: Ubuntu 20.04.3 LTS x86_64

**Comment by martin-schulze-vireso** [comment]
I could reproduce this locally. This shows that #443 is necessary.
