### ISSUE TITLE
Bats 1.4 alongside bats 1.5

### ISSUE THREAD

**Issue by javierspn** [bats-core/bats-core#577]
Hi Team!

I need to have bats 1.5 plus 1.4 in my dev Mac.  Currently I have both bash5 and the default bash 3.2.57 on it (I call for bash 5 with an alias).

How can I achieve the same with bats? Is there a "clean" method? I don't want to overwrite bats 1.5 links and stuff, I installed it with home-brew..

Thanks!

**Comment by martin-schulze-vireso** [comment]
It should be possible if you install each of them in their own prefix (e.g. /opt/bats1.5) and symlink the bin/bats executable e.g. to /usr/bin/bats1.5

However, I'd really like to know why you would want two bats instances of the same major version installed at the same time instead of just the more recent one.

**Comment by javierspn** [comment]
Hi Martin! 

Turns out that our Jenkins pipe uses bats 1.4 and locally we use 1.5...while we migrate the former I have to test it with 1.4 version.

Currently all symlinks to bats point to home-brew paths, installing bats from the source (1.4) will overwrite those? Also, I can't find where to download the 1.4 version source, call me an idiot...

**Comment by javierspn** [comment]
Forget about the download link, temporary blindness XD

**Comment by martin-schulze-vireso** [comment]
Once you got your local copy of bats unpacked, you can run it as is using the binary in the bin folder. You can also use the install.sh to install it into a desired prefix. However, you should not usw the prefix / to avoid messing with other installations.

**Comment by martin-schulze-vireso** [comment]
I closed this since it seems to be settle. Feel free to reopen if there are remaining issues.
