### ISSUE TITLE
Calling run in teardown_file overrides Bats' exit code

### ISSUE THREAD

**Issue by oyvsi** [bats-core/bats-core#588]
**Describe the bug**
It seems that if we call a function from teardown_file bats always uses exit code 0, regardless if tests fail.

**To Reproduce**
```
bash-5.1# cat smoketest.bats
function c() {
echo "hello"
}
teardown_file() {
echo "goodbye"
run c
}
@test "mytest" {
/bin/false
}

bash-5.1# bats smoketest.bats
1..1
not ok 1 mytest
# (in test file smoketest.bats, line 11)
# `/bin/false' failed

bash-5.1# echo $?
0
```
**Expected behavior**
bats to exit with exit code 1

**Environment (please complete the following information):**
 - Bats Version 1.6.0
 - OS: Alpine 3.15
 - Bash version: 5.1.16

**Comment by martin-schulze-vireso** [comment]
I'll keep this open as a reminder. Seeing that run in teardown_file seems more common than I thought, I'll fast track a 1.6.1.
