### ISSUE TITLE
Add link to documentation in GitHub About section

### ISSUE THREAD

**Issue by hwittenborn** [bats-core/bats-core#591]
Right here:

![image](https://user-images.githubusercontent.com/74838472/168506787-1718d99e-9fa1-45d1-af70-380b65a32ac7.png)

It'd be nice if there was a link to the documentation here for quicker access, as it's a bit of a pain to find it in the README if I don't know the link off the top of my head.

**Comment by martin-schulze-vireso** [comment]
I will have to Look into that. In the meantime you can click on the Docs badge in top of the readme.

**Comment by martin-schulze-vireso** [comment]
I found no way to make the Readme link point to readthedocs so I added it as website link. I think that is good enough for now.
