### ISSUE TITLE
Set a default value for `BATS_LIB_PATH`

### ISSUE THREAD

**Issue by hwittenborn** [bats-core/bats-core#600]
**Is your feature request related to a problem? Please describe.**
I'm wanting to run some Bats helper libraries in my unit tests, but I have to install Bats on every run as they're run isolated in Docker containers.

I don't know how to get `BATS_LIB_PATH` exposed to Bats though. The only way I've found to add environment variables available to all programs globally is to place them in `/etc/profile.d/`, but this is only read on the login shell, and not when a new Bash shell process is created.

**Describe the solution you'd like**
If Bats had a default value for `BATS_LIB_PATH` already defined, including `/usr/lib/bats` at the minimum, this would solve my issue.

**Describe alternatives you've considered**
None considered.

**Additional context**
N/A

**Comment by martin-schulze-vireso** [comment]
Please give more detail on the way in which you are running the tests:

- Is it on a CI system or locally?
- How are you invoking bats?
- How are the libs installed?

The way I envisioned the usage of `BATS_LIB_PATH` was either in a CI system, where you usually set the environment variables via the CI manifest or on a local system, where you have control over your user's defined variables or at the very least over the environment of commands you execute. Hence, I don't see where you are running into problems.

**Comment by hwittenborn** [comment]
> The way I envisioned the usage of BATS_LIB_PATH was either in a CI system, where you usually set the environment variables via the CI manifest

That's where I'll be using Bats, but I'll be installing Bats through a Debian package I've created. In the current system I have that variable set in etc/profile.d as stated before, where my environment variable change doesn't take effect until reboot, so I can't rely on that in a CI setup. I also would like to avoid adding any hacky workarounds as this Debian package will be installable by others.

Also with that, I don't want to have to set a custom environment variable just because of my inability to reboot. Bats including a default search path seems to be the only elegant way to solve this from what I've researched.

**Comment by martin-schulze-vireso** [comment]
Well, if we want to have a default value, we need to deal with following issues:

1. Which is it? E.g. /usr/lib is not available in some 64 Bit systems. The original PR User `~/.bats:/var/lib/bats-libs`
2. What happens with the default if users set their own value? I'd prefer it working like PATH, where you can decided if you want to replace, prepend or append. However, this necessitates the value being set before the user gets to see it.

Where would you put the libraries?

**Comment by hwittenborn** [comment]
> Which is it? E.g. /usr/lib is not available in some 64 Bit systems.

What systems do you know of are affected like that? All I really know about is the file system layout on Debian/Ubuntu, so I wouldn't know if anything else is affected.

> The original PR had ~/.bats:/var/lib/bats-libs.

I don't mind too much where the lib files go honestly, the [docs](https://bats-core.readthedocs.io/en/stable/writing-tests.html#bats-load-library-load-system-wide-libraries) did mentioned the `/usr/lib/bats` path though.

> What happens with the default if users set their own value?

I think Bats should have the default BATS_LIB_PATH, and then anything the user has should just come before that. Something like this:

```sh
BATS_LIB_PATH="${BATS_LIB_PATH}":~/.bats:/var/lib/bats-libs # Or whatever Bats makes the default path.
```

> Where would you put the libraries?

I'm not sure what Debian has for packaging requirements, but I feel like `/usr/lib` would be a more appropriate place, at the least personally.

**Comment by hwittenborn** [comment]
@martin-schulze-vireso any update on this? If we can settle on an implementation I'd be more than happy to make a PR for it

**Comment by martin-schulze-vireso** [comment]
Honestly, I did not look into this again, since I was occupied with the current milestone. Go ahead and make a PR for /usr/bats/lib, we'll hash out the details over there.

**Comment by hwittenborn** [comment]
I've got some stuff I've got to finish first, but I should have a PR going within the next two days.
