### ISSUE TITLE
Is there anyway to output the results from a command?

### ISSUE THREAD

**Issue by HiepTLe** [bats-core/bats-core#601]
**Is your feature request related to a problem? Please describe.**
Right now, when tests run, we get a check mark and test name returned along with pass or fail depending on test params. I want to also get the output of the script that ran though, and have it returned as well. 

**Describe the solution you'd like**
For example when running $ping -c 3 1.1.1.1, I would like to get the actual output.
`PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_seq=1 ttl=128 time=54.10 ms
64 bytes from 1.1.1.1: icmp_seq=2 ttl=128 time=72.9 ms
64 bytes from 1.1.1.1: icmp_seq=3 ttl=128 time=56.2 ms

--- 1.1.1.1 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 54.950/61.366/72.912/8.185 ms`

**Describe alternatives you've considered**
I'd have to get the output through another method instead of bats like running the script directly.

**Additional context**
I've tried using all flags --trace --verbose-run --show-output-of-passing-tests but the only thing it prints out is the code from the test itself, which is almost pointless.

**Comment by martin-schulze-vireso** [comment]
Can you give a code example and the output you would like? As far as I understand, you want to Print the output regardless of the test state (failed/passed).

If you are using run, you would need to combine --show-output-of-passing-tests with --verbose-run.

**Comment by HiepTLe** [comment]
> --show-output-of-passing-tests with --verbose-run
Running those together causes the output to print nothing.

```
$bats --verbose-run --show-output-of-passing-tests pingtest.sh 
pingtest.sh
 ✓ Ping 1
 ✓ Ping 2

2 tests, 0 failures
```

**Comment by martin-schulze-vireso** [comment]
You should use `.bats` as the extension for test files. Please show the contents of your test file. When I run this `test.bats` file 

```
@test test {
    ping -c 3 1.1.1.1
}
```

I get the following output:

```
$ ./bin/bats --show-output-of-passing-tests test.bats
test.bats
 ✓ test
   PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
   64 bytes from 1.1.1.1: icmp_seq=1 ttl=53 time=17.2 ms
   64 bytes from 1.1.1.1: icmp_seq=2 ttl=53 time=18.2 ms
   64 bytes from 1.1.1.1: icmp_seq=3 ttl=53 time=23.9 ms
   
   --- 1.1.1.1 ping statistics ---
   3 packets transmitted, 3 received, 0% packet loss, time 2003ms
   rtt min/avg/max/mdev = 17.165/19.738/23.859/2.943 ms

1 test, 0 failures
```

Which looks exactly like you want.

**Comment by HiepTLe** [comment]
Thank you! Let me try that now.

**Comment by HiepTLe** [comment]
Hey Martin,
That worked. Thank you! I was running it inside of a result to match other tests instead of how you did it.

**Comment by martin-schulze-vireso** [comment]
@HiepTLe Maybe you can add the actual code here as an example for others who might run into the same problem.

**Comment by HiepTLe** [comment]
> @test test {
>     ping -c 3 1.1.1.1
> }

Oh sorry. The code is exactly as you put.
```
@test test {
    ping -c 3 1.1.1.1
}
```
However before when I had the issue, the code was:
```
@test test {
   result="$( ping -c 3 1.1.1.1 )"
}
```

**Comment by martin-schulze-vireso** [comment]
The main problem with your previous code was not the extensions but that you captured `ping`'s output into `result`. There was no way for Bats to see that.

Just for completeness sake: If you would have the following code (note the extra `run`!):

```
@test test {
    run ping -c 3 1.1.1.1
}
````

Then you would also need the `--verbose-run` flag to see the output, since run captures but does not print the output of its command by default.
