### ISSUE TITLE
Issue with using `load` in `teardown`

### ISSUE THREAD

**Issue by colleeneb** [bats-core/bats-core#609]
**Describe the bug**
If we use `load` in the `teardown`, bats dies in the run and does not complete.

**To Reproduce**

Given this .bats file:
```
> cat t.bats 
teardown() {
      load ./common_functions.bash
 }

@test test2 {
     g++ test.cpp
    ./a.out
}
```
and this test.cpp:
```
> cat test.cpp 
int main() {
      return 1;
}
```
and this common_functions.bash:
```
> cat common_functions.bash 
function test_exit
{
        echo "Hi"
}

```
And then run bats. What I'm seeing is that it dies before printing what passed or failed:
```
> ./bin/bats -t t.bats 
1..1
# bats warning: Executed 0 instead of expected 1 tests
```

**Expected behavior**
Since test.cpp just returns 1, I expect bats to say that the test failed and exit cleanly. If we remove the teardown() function from t.bats it does work as expected:

```
> ./bin/bats -t t.bats 
1..1
not ok 1 test2
# (in test file t.bats, line 5)
#   `./a.out' failed
```

**Environment (please complete the following information):**
 - Bats Version: 61abd097ba592a1c44a649af16d7e0171631eaf5
 - OS: Linux
 - Bash version: GNU bash, version 4.4.23(1)-release (x86_64-suse-linux-gnu)

**Additional context**
If I'm doing something wrong in the code, let me know! But I thought it should be ok.

**Comment by martin-schulze-vireso** [comment]
Sounds similar to bats-core/bats-file#40

**Comment by colleeneb** [comment]
Thanks a lot for responding!

It happens without `-t` as well: 
``` 
> ./bin/bats t.bats 
t.bats
   test2                                                                                                                                                                                                      1/1
   bats warning: Executed 0 instead of expected 1 tests

1 test, 0 failures, 1 not run
```

It did work for a previous version, and I just ran git bisect to find the commit. The result was:

``` 
2469ef2cd5b957eb57d1891952352182db2b2277 is the first bad commit
commit 2469ef2cd5b957eb57d1891952352182db2b2277
Author: Nelo-T. Wallus <nelo@wallus.de>
Date:   Mon Jan 10 15:48:57 2022 +0100

    Rewrite BATS_LIB_PATH approach with clearer helper functions

 lib/bats-core/test_functions.bash               | 216 +++++++++++++++++-------
 test/bats.bats                                  | 108 +++++++++++-
 test/fixtures/bats/find_library_helper.bats     |   5 +
 test/fixtures/bats/find_library_helper_err.bats |   4 +
 4 files changed, 269 insertions(+), 64 deletions(-)
 create mode 100644 test/fixtures/bats/find_library_helper.bats
 create mode 100644 test/fixtures/bats/find_library_helper_err.bats
```

I'll try to look through to see if anything about that commit pops out, but I'm not a bash expert so it will take time. :)

**Comment by martin-schulze-vireso** [comment]
Okay, I think this reproducer neatly sums up the problem:

```
#!/usr/bin/env bash

fun() {
    true
    return
}

print() {
    fun
    echo "$1: $?"
}

print FREE
trap 'print EXIT' EXIT

false # uncomment to get exit without error
```

executing this prints:

```
FREE: 0
EXIT: 1
```

Swapping the two occurrences of false and true will flip around the result too:

```
FREE: 1
EXIT: 0
```

This shows that `return` without parameter in an `exit` trap will always return the value the trap was entered with. The commit you bisected introduced the first `return` without parameter which leads to an explicit `exit` in `load` because `bats_load_safe`'s return code got overwritten.

**Comment by colleeneb** [comment]
Thank you so much! For this fix and also generally thanks for bats, we use it in our test set.
