### ISSUE TITLE
Variables used in the "Setting up a multifile test suite" section of the Tutorial

### ISSUE THREAD

**Issue by hrishikesh-kadam** [bats-core/bats-core#614]
**Describe the bug**
In the [Setting up a multifile test suite][1] section of the [Tutotial][2], 
I am unable to understand the use of `$NON_EXISTANT_FIRST_RUN_FILE` and `$EXISTING_FIRST_RUN_FILE` variables.
I feel something is wrong here.

[1]: https://bats-core.readthedocs.io/en/stable/tutorial.html#setting-up-a-multifile-test-suite
[2]: https://bats-core.readthedocs.io/en/stable/tutorial.html#tutorial

**Comment by martin-schulze-vireso** [comment]
Yes, this is an oversight. The test as is will pass accidentally, but switching the Order would have exposed the problem. Later changes add the file as parameter, which is necessary for this test.

**Comment by Victoremepunto** [comment]
> Yes, this is an oversight. The test passes accidentally, but switching the order would have exposed the problem. Later changes add the file as parameter, which is necessary for this test. You can also follow the repository at [martin-schulze-vireso/bats-tutorial](https://github.com/martin-schulze-vireso/bats-tutorial)

I've checked the repository at [martin-schulze-vireso/bats-tutorial](https://github.com/martin-schulze-vireso/bats-tutorial) and this still has the same issue where the `helper` test keeps failing on the first assertion. The following is an excerpt of the output as of today:

```
./test/bats/bin/bats test
 ✗ Check first run
   (from function `assert' in file test/test_helper/bats-assert/src/assert.bash, line 40,
    in test file test/helper.bats, line 16)
     `assert _is_first_run' failed
   
   -- assertion failed --
   expression : _is_first_run
   --
   
 ✓ server is reachable
 - Show welcome message on first invocation (skipped: The FIRST_RUN_FILE already exists)

3 tests, 1 failure, 1 skipped

```

I tried to "fix it" with https://github.com/martin-schulze-vireso/bats-tutorial/pull/1 but I'm not sure if that was the intention anyways.
