### ISSUE TITLE
[feature request] Default run parameters

### ISSUE THREAD

**Issue by rbairwell** [bats-core/bats-core#624]
For quite a number of my tests, I want/need the separated stdout/stderr lines and to keep empty lines.

This means that my `run` command looks like:
`run --separate-stderr --keep-empty-lines --  ...`
every time which is long and ugly.

**Describe the solution you'd like**
To be able to set the defaults for `run` so that I don't have to repeat myself every single run command.

I think something like
```
bats_set_run_default separate-stderr exit_code=1
bats_unset_run_default all
```
(each one accepts a space separated list of the parameters/options you want to set/unset with the `unset` command also accepting the shortcode `all`)

which can be called anywhere `load` and similar commands can be included.

**Describe alternatives you've considered**
Adding in my test_helper.bash file:
```bash
runit() {
  run --separate-stderr --keep-empty-lines -- "$@"
}
```
and then using it in my tests such as:
```bash
@test 'something' {
  runit bash -c "do something"
   [ "${lines[0]}" = "good output" ]
   [ "${stderr_lines[0]}" = "error output" ]
}
```

**Comment by martin-schulze-vireso** [comment]
While I feel your pain, I think the alternative solution is better than the main suggestion.

The problem with any implicit solution is, that it is hard to realise that there are changed options. Using another function name makes this much easier to discover.

We could introduce single letter flag aliases which would reduce the length of those commands, but you are running into a DRY problem as much as a length problem.

Another option on your end would be using `run "${run_flags[@]}" -- ...`, setting the `run_flags` array to the desired value. This has similar visibility as defining a new function. Maybe you can even combine this with your approach.

**Comment by rbairwell** [comment]
Hi @martin-schulze-vireso ,

Thanks. I perfectly understand where you are coming from and I'll stick with my `runit` approach for now: although the `run_flags` suggestion sounds a good idea.

Thank you very much!
