### ISSUE TITLE
Support for GitHub Job Summaries

### ISSUE THREAD

**Issue by jkroepke** [bats-core/bats-core#634]
**Is your feature request related to a problem? Please describe.**
Support for GitHub Job Summaries

**Describe the solution you'd like**

Each action on GitHub has a predefined environment variable named `GITHUB_STEP_SUMMARY`. It contains a file path. GitHub expect markdown inside the file. The markdown inside the file will be saved and printed on a job summary page.

**Describe alternatives you've considered**
Using the junit formatter and run junit-to-md. But I'm losing the TAP output on the action.

**Additional context**

https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/

**Comment by martin-schulze-vireso** [comment]
> Using the junit formatter and run junit-to-md. But I'm losing the TAP output on the action.

Did you try using `--report-formatter junit`?

**Comment by jkroepke** [comment]
No. Thanks for the hint. Thats works. I tried it this morning, but there is no good junit to markdown or tap to markdown converter which generate pretty markdown output (e.g. test result as table)

**Comment by martin-schulze-vireso** [comment]
> [...] there is no good junit to markdown or tap to markdown converter which generate pretty markdown output (e.g. test result as table)

I thought you already found when because of the mention of `junit-to-md`. We are not constrained to junit either. Every formatter can be used as a `--report-formatter` as well, so TAP[13] is also available. Adding more formatters to core is only feasible when there is no other way and the benefits are high. I think in this case we can do well with a simple tap to md converter that works as an external project.

**Comment by jkroepke** [comment]
From my point of view, using `--report-formatter junit` in combination with https://github.com/mikepenz/action-junit-report produce the best possible result. On top, `mikepenz/action-junit-report` already supports GitHub Job Summaries.

Feel free, to close this or leave it open, if you want to continue on the TAP-to-md solution.
