### ISSUE TITLE
setup_suite: exported variables are gone

### ISSUE THREAD

**Issue by jkroepke** [bats-core/bats-core#635]
**Describe the bug**
exported environment variables from setup_suite are not available on setup or `@test`

**To Reproduce**
```bash
setup_suite() {
    {
        export SETUP_SUITE="1"
    } >&2
}

setup_file() {
    {
        export SETUP_FILE="1"
    } >&2
}

setup() {
    {
        export SETUP_TEST="1"
    } >&2
}

@test "env" {
    run echo "${SETUP_TEST}"
    [ "$output" = "1" ]

    run echo "${SETUP_FILE}"
    [ "$output" = "1" ]

    run echo "${SETUP_SUITE}"
    [ "$output" = "1" ]
}
```

**Expected behavior**
exported variables from setup_suite should be available on test like exported variables from setup_file.

**Environment (please complete the following information):**
 - Bats Version: c97b3a1
 - OS: MacOS
 - Bash version: 3.2.57(1)-release

**Additional context**

**Comment by martin-schulze-vireso** [comment]
Your setup_suite won't be executed like that. Since it is intended to do setup for several test files, it must reside in its own `setup_suite.bash` at the root of the suite.

**Comment by jkroepke** [comment]
Thanks! I was not aware of this.

I read https://bats-core.readthedocs.io/en/stable/writing-tests.html#setup-and-teardown-pre-and-post-test-hooks before I start using setup_suite. 

The example mention about `setup_suite.bash`, but I did not through that is a requirement.

**Comment by jas-** [comment]
> setup_suite.bash

Is there any way I can see a somewhat robust working example of this? I am at 65+ test cases and the setup is a bottleneck at this point. Thanks!

**Comment by jkroepke** [comment]
Works since 2 years:

https://github.com/jkroepke/helm-secrets/blob/main/tests/lib/setup_suite.bash

222 tests in less than a minute

https://github.com/jkroepke/helm-secrets/actions/runs/11851831715/job/33028966548
