### ISSUE TITLE
load function not available in setup_suite

### ISSUE THREAD

**Issue by jkroepke** [bats-core/bats-core#637]
**Describe the bug**
load function not available in setup_suite

```
% ./tests/bats/core/bin/bats -r ./tests/unit/template.bats
/Users/jkr/IdeaProjects/private/helm-secrets/tests/unit/setup_suite.bash: line 3: load: command not found
 ✗ setup_suite
   bats warning: Executed 1 instead of expected 59 tests

59 tests, 1 failure, 58 not run
```

**To Reproduce**
1. Create a load.bash file inside test directory
2. Create a setup_suite.bash inside the test directory:
   ```bash
   load './load'

   setup_suite() {
     true
   }
   ```
3. Run test suite

**Expected behavior**
No error

**Environment (please complete the following information):**
 - Bats Version [e.g. 1.4.0 or commit hash] c97b3a1
 - OS: [e.g. Linux, FreeBSD, MacOS] MacOS
 - Bash version: [e.g. 5.1] 3.2.57(1)-release

**Additional context**

_Originally posted by @martin-schulze-vireso in https://github.com/bats-core/bats-core/discussions/636#discussioncomment-3440479_

**Comment by martin-schulze-vireso** [comment]
As a workaround you can `source "$BATS_ROOT/lib/bats-core/test_functions.bash"`.

**Comment by jkroepke** [comment]
> As a workaround you can `source "$BATS_ROOT/lib/bats-core/test_functions.bash"`.

Depends on the location of the helper file. In general source is a workaround here. Since the own helper functions are not inside bats core directory, $BATS_ROOT is not an option here.

**Comment by martin-schulze-vireso** [comment]
> Depends on the location of the helper file. 

No, what I meant was: You can use that `source` command to get the definition of `load` and then you can use that.

**Comment by jkroepke** [comment]
Thats what I', trying to say with

> In general source is a workaround here

Sorry, if it was not clear from my side.
