### ISSUE TITLE
unbound errors if setup_suite is present and SHELLOPTS="" ist set

### ISSUE THREAD

**Issue by jkroepke** [bats-core/bats-core#640]
**Describe the bug**
Hi,

i'm running some coverage test with bats and [bashcov](https://github.com/infertux/bashcov). By default, bashcov sets the `SHELLOPTS` environment variable to `xtrace`. This implicit enables `nounset` on the whole bats run, too. All errors are reproducible by having an empty `SHELLOPTS` variables defined. Thats the reason, why I'm report many unbound error in history.

Since I'm trying to integrate the `setup_suite` method on my current tests, I'm getting a unbound error
```
core/lib/bats-core/tracing.bash: line 19: BATS_TEST_NAME: unbound variable
```

by adding an empty `setup_suite` function on `setup_suite.bash`. In case, `setup_suite.bash` contains syntax errors, I'm getting

```
core/libexec/bats-core/bats-exec-suite: line 275: BATS_SETUP_SUITE_COMPLETED: unbound variable
```

On MacOS, there is always an additional error:

```
core/libexec/bats-core/bats-exec-suite: line 283: stack_trace[@]: unbound variable
```

**To Reproduce**
1. Create a load.bash file inside test directory
2. Create a setup_suite.bash inside the test directory:
   ```bash
   setup_suite() {
     true
   }
   ```
3. Run test suite with `--tap` and `env SHELLOPTS=""`, e.g. `env SHELLOPTS="" bats --tap -r tests`
    ```
    1..1
    /work/tests/bats/core/lib/bats-core/tracing.bash: line 19: BATS_TEST_NAME: unbound variable
    not ok 1 setup_suite
    ```
**Expected behavior**

**Environment (please complete the following information):**
 - Bats Version [e.g. 1.4.0 or commit hash] c97b3a1
 - OS: [e.g. Linux, FreeBSD, MacOS] Linux / MacOS
 - Bash version: [e.g. 5.1] 5.0.17(1)-release / 3.2.57(1)-release

**Additional context**
All error only appears, if a `setup_suite.bash` with a `setup_suite` function exists and SHELLOPTS is set.

**Comment by martin-schulze-vireso** [comment]
It is beyond me, why the existing tests did not already find this.

**Comment by jkroepke** [comment]
If you add the steps from above to the test folder, [adding a setup_suite.bash](https://github.com/jkroepke/bats-core/commit/5054a03e1cee1fed03c265fa811162d2e59555a8) into the test folder, the error is visible inside the CI (but not the MacOS one, since there is no nounset for mac) 

https://github.com/jkroepke/bats-core/runs/8102284665

**Comment by martin-schulze-vireso** [comment]
Well, there already ist a `setup_suite` test and the whole test suite is run with a `BASH_ENV` file that does `set -u` in the unset variables CI job. I'll have to investigate.

**Comment by jkroepke** [comment]
> Well, there already ist a setup_suite test

If bats test is calling bats again, the bats inside the tests gets all environment variables inherit from the running test suite.

For example, if `BATS_TEST_NAME` is already defined before bats is started, then this error does not appear anymore.

Additionally, the `suite_setup_teardown.bats` does not contain a test with formatter tap enabled.

If bats is calling an other bats test suite, make sure that the environment variables form the running suite are not inherit.

**Comment by martin-schulze-vireso** [comment]
You're right. That might be a hard problem to solve. I'll have to think about a better solution.
