### ISSUE TITLE
Test Dependency

### ISSUE THREAD

**Issue by nicola-lunghi** [bats-core/bats-core#647]
I have the following problem:

I have a first test (test_a) and I want to execute test_b and test_c only if test_a passes (running b and c coult cause problems if test_a is not successful

How can I handle dependencies?

**Comment by martin-schulze-vireso** [comment]
Dependencies between tests are not recommended. Mechanisms like filtering or parallel execution can interfere.

It sounds as if your dependent tests should have another setup function.

**Comment by martin-schulze-vireso** [comment]
Since there has been no further feedback I am closing this. Feel free to reopen with more details.
