### ISSUE TITLE
For tests that pass but which were retried, bats returns non-zero exit code 

### ISSUE THREAD

**Issue by djmcgreal-cc** [bats-core/bats-core#660]
**To Reproduce**
```sh
echo '
@test "fail once" {
    BATS_TEST_RETRIES=2
    ((BATS_TEST_TRY_NUMBER > 1)) || false
}
' > tst.bats
bats tst.bats
[ "$?" -eq 0 ] && echo 'reported success' || echo 'reported failure'
```

**Expected behavior**

`reported success` should be printed, as per the test output

**Environment (please complete the following information):**
 - Bats Version: 1.8
 - OS: MacOS
 - Bash version: [e.g. 5.1] 3.2

**Comment by martin-schulze-vireso** [comment]
I was surprised since there are tests in place but I am afraid that they don't check the exit code in isolation.
