### ISSUE TITLE
`exit 0' failed with status 0

### ISSUE THREAD

**Issue by adoyle-h** [bats-core/bats-core#680]
**Describe the bug**

I want to exit bats file immediately when `check` function returns true.

```sh
#!/usr/bin/env bats

check() {
  true
}

setup() {
  if check; then
    exit 0
  fi
}

@test "test" {
  # ...
}
```

But it throws an error.

```
 ✗ l.now_s, the length of result should be 10
   (from function `setup' in test file tests/modules/now_s.bats, line 9)
     `exit 0' failed

1 test, 1 failure
```

**Expected behavior**

Skip current bats file. Run next file.

I used c706d14 of bats-core before, it works well. After update to dc31213, it fails.

**Environment (please complete the following information):**
 - Bats Version: dc31213
 - OS: MacOS
 - Bash version: 5.2

**Comment by martin-schulze-vireso** [comment]
As you discovered in the other issue, you should use skip instead of exit.
