### ISSUE TITLE
`bats-examples`

### ISSUE THREAD

**Issue by brunolnetto** [bats-core/bats-core#681]
Hi,

I learn from bats as much as I learn from other tools for shell handling. I am an enthusiast of bringing Linux to people not familiar with shell or with just basic software engineering knowledge. 

Because of that, I lack some examples with common assertions and machine setup for some projects like many other test tools like jest, mocha, jasmine, or pytest. It requires great effort to downgrade the development mind-level to consumable material, but I think It is worth the effort.

**Comment by martin-schulze-vireso** [comment]
I am unsere what exactly you want. Did you See the tutorial at https://bats-core.readthedocs.io/en/stable/tutorial.html

**Comment by brunolnetto** [comment]
People in a hurry are interested on common use cases for testing their scripts. I know it is challenging the meaning of "common" in a general purpose :sweat_smile:. I wrote some scripts with docker commands to both train my shell and docker skills here: https://github.com/web-needle/sappio/tree/main/src%2Fscripts . It is kind of you in case you may help me covering its use cases.
