### ISSUE TITLE
Support `setup_file` and `test` in same process

### ISSUE THREAD

**Issue by adoyle-h** [bats-core/bats-core#682]
Current `setup_file` and `test` run in different process. I cannot [load bats-support, bats-assert, bats-file in `setup_file`](https://bats-core.readthedocs.io/en/stable/faq.html#how-can-i-use-helper-libraries-like-bats-assert). `assert_equal` function is not exported so that it will be not found in `test`.

It would be better that `setup_file` and `test` in same process just like `setup`.
I want to set helper functions and common variables for testing just once. It is too redundant that invoked multiple times in `setup`.

**Comment by martin-schulze-vireso** [comment]
This is designed in purpose. You should load your libraries in `setup()`.

Consider this: Putting setup_file in the same process as its associated tests means they also run in the same process as each other, this breaking test isolation.

**Comment by adoyle-h** [comment]
Alright
