### ISSUE TITLE
`bats` coverage feature

### ISSUE THREAD

**Issue by brunolnetto** [bats-core/bats-core#683]
**Is your feature request related to a problem? Please describe.**
Unit test coverage for `bats` library.

**Describe the solution you'd like**
Other languages like python and javascript have mature libraries for unit-testing. I know c++ has as well, which comes from google on repository [googletest](https://github.com/google/googletest). Does library `bats` have some coverage table?

**Comment by martin-schulze-vireso** [comment]
I think you already answered yourself in #15.

**Comment by brunolnetto** [comment]
It happens as often as I can guess.
