### ISSUE TITLE
test names containing "/" break --gether-test-outputs-in

### ISSUE THREAD

**Issue by klemensn** [bats-core/bats-core#688]
**Describe the bug**
`--gether-test-outputs-in <directory>` uses test names as file names and thusly fails if they contain the path separator `/`.
`/` and the NUL byte `\0` must not appear in file names for obvious reaons:

```
$ bats --gather-test-outputs-in ./test-results/
ok 1 simple put/get primary key
cp: ./test-results//1-simple put/get primary key.log: No such file or directory
```

Found through https://github.com/andrewchambers/bupstash/pull/364 where I propose replacing `/` with `+` in test names.

**To Reproduce**
1. create a test with the forward-slash "/" in its name
2. run it with `--gather-test-outputs-in <directory>`

**Expected behavior**

Either a warning/error that test names must not contain the path separator or automatic replacement of it when used as filename.

**Environment (please complete the following information):**
 - Bats Version: 1.8.2
 - OS: OpenBSD/amd64 7.2-current
 - Bash version: 5.2.15

**Additional context**
Both systematic fixes could potentially be a breaking change, i.e. either now valid tests with `/` in their name would become invalid or anything that parses test output would no longer match on the exact test name.

I do not intend to invest any time or effort into this issue, hence no PR.

**Comment by martin-schulze-vireso** [comment]
Assuming we got a UTF8 compatible shell, we could replace it with  ⧸ (U+29F8, BIG SOLIDUS). It reads slightly awkward but is better then a replacement:

```
/path/to/file_with⧸in_name.txt
```
