### ISSUE TITLE
Show tags of failing tests

### ISSUE THREAD

**Issue by rickynils** [bats-core/bats-core#689]
**Is your feature request related to a problem? Please describe.**
Sometimes I generate Bats test in a matrix-like fashion. That is, I run the same test with different parameters. Test tags are great in these situations because I can encode test parameters with them. Before Bats had tags I simply added the parameter values to the test name. Now I instead add a number to each test variant, to keep the names shorter. So I have `my_test_1`, `my_test_2` etc, with different combinations of tag values. However, when a test fails I only see the test name, not the tags. This makes it hard to track down exactly which test failed.

**Describe the solution you'd like**
I think it would make sense if Bats printed the tags together with the test name when a failure is found.

**Comment by martin-schulze-vireso** [comment]
In think this is a good idea. However, I am unsure how easy it will be to integrate with the existing code.

**Comment by rickynils** [comment]
For the moment, I'm printing out the tags in the beginning of each test, but it would be slightly nicer to get "native" support for it. I haven't looked at the implementation at all.
