### ISSUE TITLE
In BATS v1.7.0 and later, teardown_file() fails when `skip` is called

### ISSUE THREAD

**Issue by stefanlasiewski** [bats-core/bats-core#695]
**Describe the bug**

I upgraded from BATS v1.6.1 to v1.7.0 and noticed this behavior change in v1.7.0. I am not able to upgrade to v1.8.2 due to a different bug which is not relevant here (#686).

In this simplified example, I use `setup_file()` & `teardown_file()` to create and delete a file. Some example code is included at the bottom of this ticket.

Sometimes, I want to preserve the file for later inspection. I do that in `teardown_file()`. If the Bash variable `SKIPCLEANUP` is `true`, then I tell BATS to `skip` the teardown:

```
teardown_file() {
  [[ $SKIPCLEANUP == "true" ]] && skip "Not cleaning up"
  rm -v $FILENAME >&3 
}
```

In v1.6.x, this code worked fine. In v1.7.0, `teardown_file` fails and exits with `failed with status 0`. I can't figure out why this is happening, and I'm also confused by the message `failed with status 0` because in Bash, 0 means success.

**To Reproduce**
1. Install BATS v1.7.0 
2. save the code below as a file `setup-teardown.bats`
3. Run the code like so:

```
bats --timing setup-teardown.bats
```

5. You will see the error below.

```
$ bats --version
Bats 1.7.0
$ bats --timing setup-teardown-file.bats 
setup-teardown-file.bats

DEBUG
-rw-r--r--  1 stefanl  wheel  0 Feb  3 14:12 /tmp/file-20230203141241
 ✓ Does file exist in 0ms [0]
 ✗ teardown_file failed []
   (from function `teardown_file' in test file setup-teardown-file.bats, line 22)
     `[[ $SKIPCLEANUP == "true" ]] && skip "Not cleaning up"' failed with status 0
   bats warning: Executed 2 instead of expected 1 tests

1 test, 1 failure in 0 seconds
$
```

6. Optionally, downgrade to v1.6.1. It works:

```
$ bats --version
Bats 1.6.1
$ bats --timing setup-teardown-file.bats 

DEBUG
-rw-r--r--  1 stefanl  wheel  0 Feb  3 14:13 /tmp/file-20230203141320
 ✓ Does file exist [0]
$
```

**Expected behavior**

I expected the `skip` to be activated and skip the `teardown_file()` function.

**Environment (please complete the following information):**
 - Bats Version v1.7.0
 - OS: CentOS 7 & MacosX Monterey
 - Bash version: 5.2.15

**Additional context**

Here's the code:

```
#! /usr/bin/env bats

# An example of setup_file & teardown_file

# Sometimes we don't want to delete the file
SKIPCLEANUP=true

# Create unique file for each run
FILENAME="/tmp/file-$(date +%Y%m%d%H%M%S)"

setup_file() {
  touch $FILENAME >&3
  echo DEBUG >&3
  ls -ld $FILENAME >&3
}

@test "Does file exist" {
  run test -f $FILENAME
}

teardown_file() {
  [[ $SKIPCLEANUP == "true" ]] && skip "Not cleaning up"
  rm -v $FILENAME >&3 
}
```

**Comment by martin-schulze-vireso** [comment]
This sounds very similar to #686, is this already fixed in master?

**Comment by martin-schulze-vireso** [comment]
Okay, I could reproduce it but on every version since `setup_file`/`teardown_file` exists (1.2.1). What exactly is your expectation?

**Comment by stefanlasiewski** [comment]
My expectation is that `skip` in `teardown_file` will cause `teardown_file` to be skipped.

>  Did you perchance confuse this with skip in teardown() (note the missing _file suffix)?

Is `skip` not supported `teardown_file`? That would be odd, because it was working for me in Bats v1.6.1.

**Comment by stefanlasiewski** [comment]
> This sounds very similar to https://github.com/bats-core/bats-core/issues/686, is this already fixed in master?

Confirmed. This no longer happens in master. This must be the same bug as [#686](https://github.com/bats-core/bats-core/issues/686)

**Comment by stefanlasiewski** [comment]
Since this appears to be the same issue as #686, I'll close the issue.
