### ISSUE TITLE
Pull optimizations from mbland/bats

### ISSUE THREAD

**Issue by mbland** [bats-core/bats-core#7]
As I'd mentioned in https://github.com/sstephenson/bats/issues/150#issuecomment-280382449, my [mbland/bats optimization refactoring][opt] resulted in a very significant performance improvement, especially on Windows. Of course I'm happy to help with implementing the other roadmap features, but I'd encourage merging these changes ahead of the others, as it's a straight refactoring that adds zero new behavior.

[opt]: https://github.com/mbland/bats/releases/tag/optimized-20170317

**Comment by btamayo** [comment]
@mbland Nice! That's excellent work :) Would you mind creating a PR against this repo so we can see the diff better and I can also use it to set up a Windows CI. Thank you for this :)
