### ISSUE TITLE
`--keep-empty-lines` causes an empty line to be added to output

### ISSUE THREAD

**Issue by jrmash** [bats-core/bats-core#708]
**Describe the bug**
Invoking the `run` command with `--keep-empty-lines` causes an empty line to be appended to the end of the output.

**To Reproduce**
```shell
bats_require_minimum_version 1.9.0

f::lines() {
    echo "Line #1"
    echo "Line #2"
}

@test "f::lines produces only 2 lines -- Test shows 2 lines, 0 empty lines" {
    run f::lines
    [ "${lines[0]}" == "Line #1" ]
    [ "${lines[1]}" == "Line #2" ]
    [ "${#lines[*]}" -eq 2 ]
}
@test "f::lines produces only 2 lines -- --keep-empty-lines adds an empty line to output" {
    run --keep-empty-lines f::lines
    [ "${lines[0]}" == "Line #1" ]
    [ "${lines[1]}" == "Line #2" ]
    
    ## Third line exists and is empty
    [ "${lines[2]}" == "" ]
    [ "${#lines[*]}" -eq 2 ]
}
```

**Expected behavior**
Empty lines in the output should be preserved and no additional empty lines are added.

**Environment (please complete the following information):**
 - Bats Version: 1.9.0
 - OS: MacOS 13.2.1
 - Bash version: 5.2.15

**Comment by martin-schulze-vireso** [comment]
`[ "${#lines[*]}" -eq 2 ]` indicates there are only two lines. Did you mean to write `[ "${#lines[*]}" -eq 3 ]`?

**Comment by jrmash** [comment]
Those two checks just show that a blank line was added to the output when nothing else changed about the test except the addition of `--keep-empty-lines`.

- `[ "${lines[2]}" == "" ]` passes because there's a third, empty line exists in the output
- `[ "${#lines[*]}" -eq 2 ]` fails because there's three lines in the output instead of the expected two

**Comment by debarshiray** [comment]
Yay!  Thanks for fixing this, @martin-schulze-vireso !

I had gotten so used to having `run --keep-empty-lines` counting the trailing newline on the last line as a separate line that I was really pleasantly surprised when Bats 1.10.0 came out.  Thanks, again.
