### ISSUE TITLE
`setup_[suite|file]` errors are not reported (tests are skipped) making them hard to debug

### ISSUE THREAD

**Issue by djmcgreal-cc** [bats-core/bats-core#712]
**Describe the bug**

Errors in these functions are not reported to callers. It would be nice to see an error message. `-x` doesn't reveal them (though it does for `setup`).

**To Reproduce**
```
function setup_file(){
  false
}

@test blah {
  true
}
```

`blah` will be skipped, but without suggestion as to why.

**Expected behavior**

It would be nice to see that `false` failed. I appreciate this might be problematic for some output formatters.

**Environment (please complete the following information):**
- 1.8.2
- MacOS
- 3.2.57

**Comment by martin-schulze-vireso** [comment]
Does this issue still happen with Bats v1.9.0?

**Comment by djmcgreal-cc** [comment]
Oh, amazing :)
Thanks.
