### ISSUE TITLE
Print colorful diff between actual output and an expected output on test failure via smth like colordiff

### ISSUE THREAD

**Issue by EmilySeville7cfg** [bats-core/bats-core#713]
**Is your feature request related to a problem? Please describe.**
It's really hard to detect the difference between actual and expected output right from the bats message when the test fails. Because bats doesn't indicate what the difference between expectation and real result:

![image](https://user-images.githubusercontent.com/42812113/224472316-cbbf0c47-b154-4c89-8fcf-aa88d456a436.png)

Such message doesn't really show what should be changed to make test pass.

**Describe the solution you'd like**
I wanna `colordiff` to be integrated to bats core and used for coloring diff between `$output` and actual result.

**Describe alternatives you've considered**
Use `ydiff` instead of colordiff.

**Additional context**
Add any other context about the feature request here.

**Comment by jasonkarns** [comment]
Bats uses the standard [TAP](https://testanything.org) output format. As a fairly common, cross-platform format, I would imagine there are existing highlighters that could be piped to. One example here on npm: https://www.npmjs.com/package/tap-colorize

**Comment by martin-schulze-vireso** [comment]
I think this issued would be a better fit in bats-assert. Apart from that: you could also call your chosen diff executable without using [ ].

**Comment by EmilySeville7cfg** [comment]
@martin-schulze-vireso, I've moved this issue to bats-assert repo.
