### ISSUE TITLE
Bats project is supported in Command Line Interface Pages now

### ISSUE THREAD

**Issue by EmilySeville7cfg** [bats-core/bats-core#714]
![image](https://user-images.githubusercontent.com/42812113/224483928-594858f1-8123-4953-ad41-19473b496a37.png)

Page for your project has been added in [this](https://github.com/command-line-interface-pages/cli-pages/pull/83) PR. 😄

**Comment by martin-schulze-vireso** [comment]
Thanks foe including Bats.
