### ISSUE TITLE
Incorrect architecture reported when running tests

### ISSUE THREAD

**Issue by AlexSkrypnyk** [bats-core/bats-core#722]
**Describe the bug**
On Mac M1 with `arm` architecture, running `usname -m` or `arch` produces incorrect results.

**To Reproduce**

1. Create test file:
```
echo '#!/usr/bin/env bats

@test "Check arch" {
  uname -m >&3
  arch >&3
}' > test.bats

```
2. Run it on M1
```
bats test.bats
```
4. Assert output:
```
test.bats
 ✓ Check arch
x86_64
i386

1 test, 0 failures
```

**Expected behavior**
Same output as :
```
$ uname -m
arm64
```
or
```
$ arch
arm64
```

**Environment (please complete the following information):**
 - Bats Version `1.9.0`
 - OS: `Darwin MacBook-Pro.WORKGROUP 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64`
 - Bash version: `GNU bash, version 5.2.15(1)-release (x86_64-apple-darwin22.1.0)`

**Additional context**
It could be an issue with my environment, but I do not have a separate mac to test this. Would really appreciate if someone could confirm this.

**Comment by martin-schulze-vireso** [comment]
Seeing the bash version x86_64-apple-darwin22.1.0 my guess is that you are running bats in an emulated x86 env. What is the output of `bash -c arch`?

**Comment by AlexSkrypnyk** [comment]
Thank you for looking into this

```
$ bash -c arch
i386
```
I do have Rosetta installed. It could be a cause of this issue (I did not realise that it is going to interfere with shells).

**Comment by martin-schulze-vireso** [comment]
So this should be solved by using a bash version build for arm64. In any Case this is not a Bats issue.
