### ISSUE TITLE
Support for gnu parallel alternatives, e.g. rush

### ISSUE THREAD

**Issue by jkroepke** [bats-core/bats-core#725]
**Is your feature request related to a problem? Please describe.**
Hi,

i have to provide a shell script that works under Linux as well as Windows, too.

Setup GNU parallel under windows is a pain, since there are no packages available for MSYS or cygwin. However, the execution speed under windows is the slowest my test suite would have the most benefit by running the tests in parallel.

**Describe the solution you'd like**
I would love to see some support for [rush](https://github.com/shenwei356/rush). Rush is a single binary with also zero dependencies. Compared to GNU parallel, rush can be installed on a windows much easier, since its a single binary.

**Describe alternatives you've considered**
I already put the rush binary as parallel in path, but it seems like thats not working.

If I execute bats with --job, the help of rush is displayed with
```
unknown flag: --dummy-flag -j 4 -x 
   bats warning: Executed 0 instead of expected 12 tests
```

rush is not support the `:::` syntax, instead the input must be come from stdin, but like GNU parallel, rush supports `--jobs` and `--keep-order` which seems mandatory here.

https://github.com/bats-core/bats-core/blob/4417a96cfc5e4afc493df94eeef8af4eec760163/libexec/bats-core/bats-exec-suite#L444

**Additional context**

See also [DIFFERENCES BETWEEN Rush AND GNU Parallel](https://www.gnu.org/software/parallel/parallel_alternatives.html#DIFFERENCES-BETWEEN-Rush-AND-GNU-Parallel)

**Comment by jkroepke** [comment]
Changing the line 444 from

```bash
  parallel --keep-order --jobs "$num_jobs" bats-exec-file "$(printf "%q " "${flags[@]}")" "{}" "$TESTS_LIST_FILE" ::: "${BATS_UNIQUE_TEST_FILENAMES[@]}" 2>&1 || bats_exec_suite_status=1 
```

to

```bash
  parallel --keep-order --jobs "$num_jobs" -- bats-exec-file "$(printf "%q " "${flags[@]}")" "{}" "$TESTS_LIST_FILE" <<< "${BATS_UNIQUE_TEST_FILENAMES[@]}" 2>&1 || bats_exec_suite_status=1
```

seems enough to be compatible with rush, however I'm not aware for any incompatibilities with GNU parallel here. As I know, GNU parallel also support reading variables from stdin. It would be also great to habe an CLI flag for the name of the "parallel" binary.

**Comment by martin-schulze-vireso** [comment]
I've been meaning for ages to remove the dependency on `parallel`, since we already have a background process based solution for parallelization within files.

Regarding your suggestion: I am uncertain about whitespace handling in tets failenames with this solution but I would accept a PR with tests that shows this works.
