### ISSUE TITLE
Writing multiline string to file descriptor 3 gives results in incorrect output

### ISSUE THREAD

**Issue by paololazzari** [bats-core/bats-core#745]
```bash
$ bats --version
Bats 1.2.1
```
---

```bash
#!/usr/bin/env bats

@test "foo" {
    echo '# foo
    bar' >&3
}
```

```
$ bats foo.sh
    foo                                                                                                   1/1
 ✓ foo

1 test, 0 failures
```

the output is incorrect as the second line is missing

**Comment by martin-schulze-vireso** [comment]
Does this happen with the current version as well? Older versions mandated that each line sent to fd 3 has to be prefixed with `# `.

**Comment by paololazzari** [comment]
This works fine in `1.9.0`... I installed via `apt` and for some reason I got a rather old version..
