### ISSUE TITLE
Expose test status (failed or succeeded) in teardown

### ISSUE THREAD

**Issue by nieomylnieja** [bats-core/bats-core#746]
**Is your feature request related to a problem? Please describe.**
I'm writing e2e tests of a CLI which manages the creation of objects in a certain system. I'm performing cleanup (removing the applied objects) for each test I've written in teardown, which is costly. Normally if the test succeeds, it will remove these objects itself at the end, but If it fails, it won't do that.

**Describe the solution you'd like**
I'd love to be able to see if the test I'm performing the teardown for has failed and only then do some actions.

**Describe alternatives you've considered**
Expose a new variable. We have `$status`, but that is not sufficient since in some tests I'm expecting errors, so `run` status doesn't really tell me all that much, the new status would have to come from the assertion libraries I suppose, but I fell this should be unified under bats-core banner somehow.

**Additional context**
None.

**Comment by nieomylnieja** [comment]
I'm currently using `teardown_file` because it is easier, I still need to go through all of these objects and delete them all as I have no way of telling which test failed, and thus which objects might need a cleanup.

Ideally I'd run `teardown` and only delete the objects a given test has failed to clean up.

**Comment by martin-schulze-vireso** [comment]
I think this is an xy problem: it sounds like you actually want to do something (cleanup) only when a (specific) test fails.

While the solution above will work, I think a better fit would be some sort of on_failure callback. If you agree, you could open a new issue for that.

**Comment by martin-schulze-vireso** [comment]
I created issue #756 for that. There is a workaround for this problem in [pailsley's post](https://github.com/bats-core/bats-core/issues/746#issuecomment-1629686296) and I hope once #756 is implemented, this is trivial.
