### ISSUE TITLE
errexit is ignored in functions executed via run

### ISSUE THREAD

**Issue by jandubois** [bats-core/bats-core#748]
**Describe the bug**

Not sure if this is a bug, but it was a surprise to me, and not clear from reading the docs. If this is by-design, then maybe it should be listed under "Gotchas":

When you call a function via `run` then `set -o errexit` inside the function has no effect, and the function is executed to the last statement.

**To Reproduce**

1. Create example `file.bats` with following contents

```bash
load ./bats-support/load.bash
load ./bats-assert/load.bash

foo() {
    set -o errexit
    false
    true
}

@test 'without run' {
    foo
}

@test 'with run' {
    run foo
    assert_success
}
```

2. run `bats file.bats`

```
file.bats
 ✗ without run
   (from function `foo' in file file.bats, line 6,
    in test file file.bats, line 11)
     `foo' failed
 ✓ with run

2 tests, 1 failure
```

**Expected behavior**

I expected that the `false` command in `foo` would terminate the function and set `$status` to `1` when invoked via `run`. So I expected `with run` to fail as well.

**Environment (please complete the following information):**
 - Bats version [e.g. 1.4.0 or commit hash if applicable]

    ```
    commit f4552f12e8c1800bd2285c6aaec5e5e91d2afe76 (HEAD -> master, origin/master, origin/HEAD)
    Merge: 26e7408 596315d
    Author: Martin Schulze <37703201+martin-schulze-vireso@users.noreply.github.com>
    Date:   Tue Jun 13 01:20:56 2023 +0200

        Merge pull request #736 from martin-schulze-vireso/fix/mocking_date_breaks_timing

        Fix overriding date breaks timing
    ```

 - operating system (including version): [e.g. Linux (please name your distribution!), FreeBSD, MacOS]

    ```
    $ sw_vers
    ProductName:	macOS
    ProductVersion:	12.6.7
    BuildVersion:	21G651
    ```

 - `bash --version`: [e.g. 5.1]

    GNU bash, version 5.2.15(1)-release (x86_64-apple-darwin21.6.0)

 - Install method: [e.g. git submodule, distribution package manager, npm, homebrew, ...]

    git clone of all repos, just for this test

**Comment by martin-schulze-vireso** [comment]
Somewhat duplicate to #719

**Comment by jandubois** [comment]
Just for context, my actual use-case was running a helper function that would use `run` and `assert_xxx` internally. In one place I had to call the helper function via `run` and eventually noticed that in this case all the `assert_xxx` calls where ignored (except the one at the very end).

I've been thinking of run/assert as somewhat similar to a try/catch mechanism, where I could capture and inspect output in the helper, but then re-assert if needed at the call site.

Anyways, I think capturing `$output` and `$status` is somewhat orthogonal to disabling `errexit`, so I'm not sure why `run` does both. It would be nice if that behaviour would be configurable!

Now that I understand I can work around it by following each `assert_xxx` in the helper with an `if (($?)); then return; fi`, but it feels a bit weird.

**Comment by martin-schulze-vireso** [comment]
I think ` || return` would be less verbose as a workaround.

**Comment by jandubois** [comment]
> I think ` || return $?` would be less verbose as a workaround.

Indeed. Thanks for pointing that out! Also just ` || return` should work too.

**Comment by martin-schulze-vireso** [comment]
Closing in favor of #719
