### ISSUE TITLE
Add tests for install.sh

### ISSUE THREAD

**Issue by tterranigma** [bats-core/bats-core#76]
Also move the install.sh file into libexec.

**Comment by jasonkarns** [comment]
Rationale? It seems fairly conventional for install.sh to be at project root, no?

**Comment by tterranigma** [comment]
Well, I don't really know what my motivation was TBH. I wrote it rushing to a meeting and judging by the imperative clause I probably meant it as a reminder to myself to look into moving install.sh functionality into `libexec` to ease testing. Please ignore it and apologies if it sounded rude (it does to me after a good night sleep)!

**Comment by jasonkarns** [comment]
No worries!
