### ISSUE TITLE
How to display result of a command if the test is failed?

### ISSUE THREAD

**Issue by quanghoc** [bats-core/bats-core#77]
Let say if one test is failed, how to display some information from output of that command line in order to troubleshoot / diagnostic?

```
@test "addition using bc" {
  result="$(echo 2+2 | bc)"
  [ "$result" -eq 41 ]
}
```

I want to output `$result` (which is `4`). This doesn't work `[ "$result" -eq 41 ] || echo "$result"`

**Comment by tterranigma** [comment]
Your best option would be to use an assertions library like the first two files from [here](https://github.com/mbland/go-script-bash/tree/master/lib/bats). Just source them in your bats files and use the `assert_equal` or `assert_output_matches` functions. If they fail, they display the output of the failed command.

**Comment by alkhimey** [comment]
Why not make this library part of bats?

**Comment by jasonkarns** [comment]
We do have plans to likely incorporate some libraries into the bats org (if not into bats itself), but equally valid is keeping bats itself small and fast. (leaving helper libs to be picked and chosen by test authors not forced by the framework)

but it seems @tterranigma has addressed the original issue?
