### ISSUE TITLE
feature request: automake-compatible extension support

### ISSUE THREAD

**Issue by eedwards-sk** [bats-core/bats-core#78]
automake prefers `.test` as the extension for running tests

for whatever reason, if I run tests through their `tap-driver` and use any extension other than `.test`, it doesn't display the TAP output

example

```
#!/usr/bin/env bats

@test "hello world" {
  true
}
```

```
<snip>
PASS: tests/ut/list/api/create.test 1 hello world
<snip>
```

vs

```
<snip>
PASS: tests/ut/list/api/create.bats
<snip>
```

Notice how the `1 hello world` output is only shown if the file ended in `.test`

As it stands, bats requires `.bats` extension if you want to run bats directly and point it at a directory.

This is a request to support additional file extensions, e.g. to allow me to run bats against a directory but tell it to look for `*.test` rather than `*.bats`

**Comment by martin-schulze-vireso** [comment]
I don't see many people requesting this but it also seems to be easy/non intrusive (2 lines to change) to implement: Just let `libexec/bats` use a variable like `BATS_FILE_EXTENSION` for the (recursive) search and allow users to override it. @sublimino WDYT?

**Comment by sublimino** [comment]
SGTM, and agreed env var is better to avoid cluttering the CLI interface.
