### ISSUE TITLE
Option `--filter-tags a,b` does not filter with `# bats file_tags=`

### ISSUE THREAD

**Issue by jetm** [bats-core/bats-core#783]
**Describe the bug**
Option `--filter-tags a,b` does not filter with `# bats file_tags=`. It executes zero tests, but passing multiple `--filter-tags` does work, like `--filter-tags a --filter-tags b`

**To Reproduce**
```
$ cat tests/sample/*.bats             
#!/usr/bin/env bats

# bats file_tags=b
@test "Test B" {
  true
}
#!/usr/bin/env bats

# bats file_tags=a
@test "Test A" {
  true
}

$ bats -r --filter-tags a tests/sample
sample2.bats
sample.bats
 ✓ Test A

1 test, 0 failures

$ bats -r --filter-tags b tests/sample
sample2.bats
 ✓ Test B
sample.bats

1 test, 0 failures

$ bats -r --filter-tags a,b tests/sample

0 tests, 0 failures

$ bats -r --filter-tags a --filter-tags b tests/sample
sample2.bats
 ✓ Test B
sample.bats
 ✓ Test A

2 tests, 0 failures
```

**Expected behavior**
When filtering the tags using comma, run all those tests that are tagged with `file_tags`.

**Environment (please complete the following information):**
 - Bats 1.8 - 1.10 version
 - Linux
 - GNU bash, version 5.1.16(1)-release
 - Distribution package manager pacman

**Comment by martin-schulze-vireso** [comment]
It works as intended: multiple tags in the same `--filter-tags` statement means that only tests that have all these tags are executed. Conversely, when there are multiple `--filter-tags` statements, at least one needs to match for a test to be executed.

**Comment by jetm** [comment]
In the example above passing multiple tags to `--filter-tags` is not working, see:
```
$ bats -r --filter-tags a,b tests/sample

0 tests, 0 failures
```
No test is running

**Comment by jetm** [comment]
Got it. Thank you for the clarification
