### ISSUE TITLE
Syntax use misunderstanding or bug?

### ISSUE THREAD

**Issue by nsercproject** [bats-core/bats-core#814]
I am following the example in the documentation and learning how to write the tests.
I expected all three test cases to be equivalent. However the first one fails.
What is the reason?
Is it expected?
Is it a bug?
Thanks

```bash
#!/usr/bin/env bash
# file: myProject.sh
declare -r VAR1="example"
```
and the test file with 3 different ways of testing:
```bats
 #!/usr/bin/env bats
# file: test.bats
# shellcheck shell=bats
setup() {
  bats_load_library test_helper/bats-support/
  bats_load_library test_helper/bats-assert/
}

@test 'check var 1 - why fails?' {
  source ./myProject.sh
  echo "${VAR1}"
  assert_output "example" # if using bats-core/bats-assert
  [[ "${output}" == "example" ]] # if not
}

@test 'check var 2' {
  run bash -c 'source ./myProject.sh;echo "${VAR1}"'
  assert_output "example" # if using bats-core/bats-assert
  [[ "${output}" == "example" ]] # if not
}

@test 'check var 3' {
  source ./myProject.sh
  assert_equal "${VAR1}" "example" # if using bats-core/bats-assert
  [[ "${VAR1}" == "example" ]] # if not
}
```

and got the following results:
```
test.bats
 ✗ check var 1 - why fails?
   (in test file test.bats, line 11)
     `assert_output "example" # if using bats-core/bats-assert' failed
   example
   
   -- output differs --
   expected : example
   actual   :
   --
   
 ✓ check var 2
 ✓ check var 3

3 tests, 1 failure
```

I hope that helps!

I believe `check var 1` fails because the `echo` is within the test itself and so is not 'captured' by BATS (I've only really been using BATS for around a week myself so my explanation may not be 100% correct0

_Originally posted by @rbairwell in https://github.com/bats-core/bats-core/issues/625#issuecomment-1203820776_

**Comment by martin-schulze-vireso** [comment]
Thanks for your report. Unfortunately, this is a bit vague on what you want. Can you please add a better title and more information on what you want to achieve with this issue?

**Comment by nsercproject** [comment]
I edited the title and the intro to the issue. Sorry I did not have much time the first time. Thanks

**Comment by martin-schulze-vireso** [comment]
Well, `assert_output` checks if the variable `$output` equals the given value. `run` captures the output of the command it executes in this variable (`$output`). 

The first test fails, because `run` is not used and `$output` not set.

The second test uses `run` and therefore sets `$output`.

The third test uses `assert_equal` and does not rely on `$output`. Instead `$var1` is directly passed as parameter.

As you can see, everything works as expected, so this is not a bug.

Feel free to reopen if I misunderstood your intentions.

**Comment by nsercproject** [comment]
[like]  Pablo Adames reacted to your message:
________________________________
