### ISSUE TITLE
Strange (mis)behavior with shift in function under test

### ISSUE THREAD

**Issue by exoosh** [bats-core/bats-core#829]
**Describe the bug**
When using the builtin `shift <n>` in a function under test, somehow the meaning of the shift gets lost under some circumstances

**To Reproduce**

1. Create example `mwe.bats` with following contents
   ```
	function bla
	{
		local ARG1=$1 ARG2=$2 OPTARG3=$3
		shift 3
		local OPTARG4=${1:-foobar}
		local OPTARG4AGAIN=${4:-baz}
		declare -p ARG1 ARG2 OPTARG3 OPTARG4 OPTARG4AGAIN >&3
	}

	@test "reproduce issue" {
		run bla "argument one" "argument two"
	}
   ```
3. run `bats mwe.bats`
4. observe the output

**Expected behavior**
I would expect the output to show `declare -- OPTARG4="0"` instead of `declare -- OPTARG4="argument one"`

**Environment (please complete the following information):**
 - Bats version 43e88571d32af48d2f7f8d9592d5772ee2cc81d7
 - operating system (including version): MSYS2 (Bash from Git for Windows)
 - `bash --version`: `GNU bash, version 5.2.21(1)-release (x86_64-pc-msys)`
 - Install method: Git checkout then installed into local subfolder

**Additional context**
Normally one would expect the positional arguments to be consumed by the builtin `shift`. Evidently they aren't.

**Comment by martin-schulze-vireso** [comment]
This is not a Bats issue. I expanded your reproducer like this:

```
 function bla
 {
 	local ARG1=$1 ARG2=$2 OPTARG3=$3
 	shift $ARG1
	echo shift returned $?
 	local OPTARG4=${1:-foobar}
 	local OPTARG4AGAIN=${4:-baz}
	printf "%s\n" "$@"
 	declare -p ARG1 ARG2 OPTARG3 OPTARG4 OPTARG4AGAIN >&3
 }
exec 3>&1
 bla 1 "arg 1" "arg 2"
 bla 2 "arg 1" "arg 2"
 bla 3 "arg 1" "arg 2"
 bla 4 "arg 1" "arg 2"
```

And get the output:
```
$ bash mwe.bash 
shift returned 0
arg 1
arg 2
declare -- ARG1="1"
declare -- ARG2="arg 1"
declare -- OPTARG3="arg 2"
declare -- OPTARG4="arg 1"
declare -- OPTARG4AGAIN="baz"
shift returned 0
arg 2
declare -- ARG1="2"
declare -- ARG2="arg 1"
declare -- OPTARG3="arg 2"
declare -- OPTARG4="arg 2"
declare -- OPTARG4AGAIN="baz"
shift returned 0

declare -- ARG1="3"
declare -- ARG2="arg 1"
declare -- OPTARG3="arg 2"
declare -- OPTARG4="foobar"
declare -- OPTARG4AGAIN="baz"
shift returned 1
4
arg 1
arg 2
declare -- ARG1="4"
declare -- ARG2="arg 1"
declare -- OPTARG3="arg 2"
declare -- OPTARG4="4"
declare -- OPTARG4AGAIN="baz"
shift returned 1
```

As you can see, `shift` returns 1 when its argument is larger than the list of parameters and does not change the parameter list.

**Comment by exoosh** [comment]
@martin-schulze-vireso thanks for pointing that out. Already learned something today this way, so I guess it's a good day already! Cheers.
