### ISSUE TITLE
Run code before/after all tests in a bats file

### ISSUE THREAD

**Issue by alkhimey** [bats-core/bats-core#85]
This is a feature request.

The use case is having some kind of precondition checking or setup before all tests  are executed and a cleanup after all tests are complete.

This is different from `setup`/`teardown` as these functions run before/after *each* test execution.

**Comment by bvberkum** [comment]
Wrt. **before all** and/vs **before each** some thoughts are already exchanged in #39, 
and also on gitter https://gitter.im/bats-core/bats-core

I believe it is also on the 1.0

**Comment by alkhimey** [comment]
Since this feature was already suggested, I am closing the issue to reduce clutter.
