### ISSUE TITLE
Bats Summer Sprint 2018

### ISSUE THREAD

**Issue by nkakouros** [bats-core/bats-core#89]
Summer has just arrived and most of us will be having a little more time to spare on our favorite projects. How would you feel about organizing an online Bats sprint this summer?

My suggestion is a 1-2 day event to meet online, get to know each other and work on remaining and new bugs and features and plan the future. There is not a ton of work to carry but it would be nice to work on what there is on the issue tracker and on our minds cooperatively and in a dedicated manner.

Do you think it would be worth it?

**Comment by bvberkum** [comment]
I would be mildly interested. I can certainly make the time, and bats and its TAP output has been an important part of daily work.

Count me in.

**Comment by nylen** [comment]
I'd like to help, and I guess I already started with a couple of things I'd like to see :wink: #96, #97

**Comment by nylen** [comment]
It is a bit disappointing to see this repo suffering from similar maintenance issues as [the original](https://github.com/sstephenson/bats), though less severe

I'd be happy to help with that.  Probably the first things I would do: get more bash versions running on CI, then land https://github.com/bats-core/bats-core/issues/18, then clarify the direction around assertion libraries.

For now, though, I am just going to maintain the changes I need in my own fork https://github.com/nylen/bats-core
