### ISSUE TITLE
dockerhub tags are inconsistent

### ISSUE THREAD

**Issue by cdleonard** [bats-core/bats-core#897]
Look here: https://hub.docker.com/r/bats/bats/tags

There's an "1.11.0" tag and a "v1.10.0" tag but no "v1.11.0" or "1.10.0"

It would be nice to have a single convention: `docker run -it --rm bats/bats:$BATS_VERSION bats --version` should output `Bats $BATS_VERSION`

**Comment by martin-schulze-vireso** [comment]
I believe this is due to a manual error while fixing https://github.com/bats-core/bats-core/issues/796. The usual docker tag format is without the leading v but I have to be more careful when rerunning the release manually.
