### ISSUE TITLE
New file bin/bats breaks existing basher installations

### ISSUE THREAD

**Issue by bvberkum** [bats-core/bats-core#90]
The new ``bin/bats`` is a wrapper to call the bats frontend:
```
  exec "${0%/*}/../libexec/bats" "$@"
```
The ``$0`` in a basher installation and in other installations may be a symlink.
Taking the directory part of the symlink gives the wrong path, so an additional step is needed:
```
  _0=$(realpath "$0")
```
which is why perhaps a symlink is better. I see the objective (#32) is to avoid issues with symlinks on windows.

I'd really like to use a packer manager to get basher. basherpm works well for small projects, as long as some common sense rules are followed. Maybe this isn't supported, or maybe there is something better. What is the preferred installation method?

**Comment by mbland** [comment]
Gah, alright. I'll create a PR to restore the symlink, but to install a regular file on Windows.

Is this a hard blocker for you now? If not, I'll get to it in a couple days.

**Comment by bvberkum** [comment]
I'm sorry, I know it takes a bunch of work :)
No not a blocker ofcourse. I can use my own fork or hack it temporarily. My mind is on the deployment. Its so simple perhaps even a shell oneliner can do it, or some *shudder* 'curl ... | bash'. No rush.
