### ISSUE TITLE
setup function does not export associative arrays to test functions

### ISSUE THREAD

**Issue by garylavayou** [bats-core/bats-core#922]
**Describe the bug**

Tests fail if the test code contains command to access bash associative arrays that are defined in the loaded files in `setup()`.

**To Reproduce**

1. Create example `file.bats` and `shell.sh` with following contents:

   ```bash
   #!/usr/bin/env -S bats --timing --show-output-of-passing-tests --verbose-run
   function setup() {
       source ./shell.sh
   }

   @test "show load variables" {
       declare -p X
       declare -p array
       declare -p dict
   }  
   
   @test "show local variables" {
       source ./shell.sh
       declare -p X
       declare -p array
       declare -p dict
   }   
   ```

   ```
   #!/bin/bash
   X=1
   array=(1 2 3)
   declare -A dict=([a]=1 [b]=2 [c]=3)
   ```

3. run `./file.bats` (makesure it is executable)
4. The test "`show load variables`"  failed with the following message:

   ```log
   declare -- X="1"
   declare -a array=([0]="1" [1]="2" [2]="3")
   /.../file.bats: line xxx: declare: dict: not found
   ```

**Expected behavior**
`setup` should also make the associative array (e.g., `dict` in the above example) available to test functions. So the "`show load variables`" will success as "`show local variables`".

**Environment (please complete the following information):**
 - Bats version: `1.11.0`
 - operating system (including version): Ubuntu 22.04.4 LTS, Linux 5.15.146.1-microsoft-standard-WSL2
 - `bash --version`: `5.1.16`
 - Install method: `npm`

**Additional context**

**Comment by martin-schulze-vireso** [comment]
This is expected behavior of `declare`. To quote the [documentation](https://www.gnu.org/software/bash/manual/bash.html#index-declare):

>  When used in a function, `declare' makes NAMEs local, as with the `local'  command.  The `-g' option suppresses this behavior.

Since `shell.sh`'s code is executed inside the function `setup`, the variable `dict` stays local to that function. In your second test it stays local to the test function which is sufficient.

One workaround would be to explicitly use `declare -Ap`.

**Comment by garylavayou** [comment]
> This is expected behavior of `declare`. To quote the [documentation](https://www.gnu.org/software/bash/manual/bash.html#index-declare):
> 
> >  When used in a function, `declare' makes NAMEs local, as with the `local'  command.  The `-g' option suppresses this behavior.
> 
> Since `shell.sh`'s code is executed inside the function `setup`, the variable `dict` stays local to that function. In your second test it stays local to the test function which is sufficient.
> 
> One workaround would be to explicitly use `declare -Ap`.

Do you mean `declare -Ag` to make the array variable visible at the global scope? As far as I know, the `-p` option is used to print the variable.

> The -p option will display the attributes and values of each name.

**Comment by martin-schulze-vireso** [comment]
You're right, I meant `declare -Ag`
