### ISSUE TITLE
bats-action: generates warnings trying to untar the cache

### ISSUE THREAD

**Issue by dekimsey** [bats-core/bats-core#926]
**Describe the bug**
The bats-core/bats-action GitHub Action generates a number of tar extraction warnings while unpacking the cache.

Note: This is reported here because the bats-core/bats-action repository doesn't have issues enabled, I hope I haven't misunderstood!

**To Reproduce**

1. Run GHA workflow that populates the cache
2. Run workflow again

**Expected behavior**
Cache extraction should succeed and not generate warnings.

**Environment (please complete the following information):**
 - bats-core/bats-action@2.0.0
 - Ubuntu 22.04
 - GHA Runner: 2.316.1
 - Install method: GHA

**Additional context**

Self-hosted runner.

First run:
```
Run actions/cache@v4
Cache not found for input keys: Linux-bats-
Run # In $HOME to avoid sudo requirements
Installed Bats to /home/runner/.local/share/bats/bin/bats
Bats v1.11.0 installed in /home/runner/.local/share/bats
Run actions/cache@v4
Cache not found for input keys: Linux-bats-support-0.3.0
Run VERSION=0.3.0
Bats Support v0.3.0 installed in /usr/lib/bats-support
```

Subsequent runs:
```
Run actions/cache@v4
Cache Size: ~0 MB (3640 B)
/usr/bin/tar -xf /home/runner/work/_temp/8b89cf35-d286-498e-9531-00378454e3da/cache.tzst -P -C /home/runner/work/expert-happiness/expert-happiness --use-compress-program unzstd
/usr/bin/tar: ../../../../../usr/lib/bats-support: Cannot mkdir: Permission denied
/usr/bin/tar: ../../../../../usr/lib/bats-support: Cannot mkdir: Permission denied
/usr/bin/tar: ../../../../../usr/lib/bats-support/load.bash: Cannot open: No such file or directory
/usr/bin/tar: ../../../../../usr/lib/bats-support: Cannot mkdir: Permission denied
/usr/bin/tar: ../../../../../usr/lib/bats-support/src: Cannot mkdir: No such file or directory
/usr/bin/tar: ../../../../../usr/lib/bats-support: Cannot mkdir: Permission denied
/usr/bin/tar: ../../../../../usr/lib/bats-support/src/output.bash: Cannot open: No such file or directory
/usr/bin/tar: ../../../../../usr/lib/bats-support: Cannot mkdir: Permission denied
/usr/bin/tar: ../../../../../usr/lib/bats-support/src/error.bash: Cannot open: No such file or directory
/usr/bin/tar: ../../../../../usr/lib/bats-support: Cannot mkdir: Permission denied
/usr/bin/tar: ../../../../../usr/lib/bats-support/src/lang.bash: Cannot open: No such file or directory
/usr/bin/tar: Exiting with failure status due to previous errors
Warning: Failed to restore: "/usr/bin/tar" failed with error: The process '/usr/bin/tar' failed with exit code 2
Cache not found for input keys: Linux-bats-support-0.3.0
```

Attached are more detailed logs of both.
  - [bats-action.first-run.log](https://github.com/bats-core/bats-core/files/15474496/bats-action.first-run.log)
  - [bats-action.cache-load.log](https://github.com/bats-core/bats-core/files/15474494/bats-action.cache-load.log)

**Comment by martin-schulze-vireso** [comment]
Please report this here: https://github.com/bats-core/bats-action

**Comment by brokenpip3** [comment]
Hi @dekimsey this is a well know issue, check the readme: https://github.com/bats-core/bats-action?tab=readme-ov-file#about-caching or this [issue](https://github.com/brokenpip3/setup-bats-libs/issues/18)
