### ISSUE TITLE
Is it possible to use `only` to run only marked tests, and skip everything other tests

### ISSUE THREAD

**Issue by coderaiser** [bats-core/bats-core#945]
As I understand there is a way to skip some tests, but is it possible to run only marked tests and skip all others, this is very useful for TDD and while fixing a bug.

**Comment by martin-schulze-vireso** [comment]
Yes, you can mark tests with the [bats:focus]https://bats-core.readthedocs.io/en/stable/writing-tests.html#focusing-on-tests-with-bats-focus-tag) tag:

```
# bats test_tags=bats:focus 
@test focussed Test { 
....
```
