### ISSUE TITLE
Links in the PR template are broken

### ISSUE THREAD

**Issue by jasonkarns** [bats-core/bats-core#95]
Links in the PR template point to .github/ for contributing and code of conduct files. (I'm assuming they're relative URLs.)

Should those files go under `.github/`? Or at the very least, make the links absolute? (I'm partial to moving the files under .github if github recognizes those files in there.)

**Comment by mbland** [comment]
Pretty sure they'll need to be absolute. I'll push an update to #92.

**Comment by jasonkarns** [comment]
I just checked the github docs for both of these files. In addition to the .github directory, they can also live in `docs/`. I propose we move both CoC and Contributing to docs/ to help clean up the root and keep things organized. (Especially since each of these files aren't strictly unique to github.)

https://help.github.com/articles/setting-guidelines-for-repository-contributors/
https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/

With that in mind, I think the CODEOWNERS and PR template should go in docs/ as well.

**Comment by mbland** [comment]
Just pushed a commit to #92 to do this.
