### ISSUE TITLE
set +e is ignored

### ISSUE THREAD

**Issue by nouaman** [bats-core/bats-core#953]
**Describe the bug**

Hello, Im facing a problem when setting a set +e inside a function that Im mocking : 

- I create a wrapper around test_function_1 to catch output but mostly variables (not included in the examples)
- I mock test_function_2 to control when to trigger the error 
- Im not using run because I need to capture the variables changed inside my function.
- When I mark test_function_2 as should fail, the whole test fail and set +e is ignored

**To Reproduce**

1. run bats on this content
```
#!/usr/bin/env bats

test_function_1(){
    result=$(test_function_2) && exit_code=0 || exit_code=$?
    if [[ $exit_code -eq 0 ]]; then
        echo "test_function_1 passed"
        export TEST_FUNCTION_1_RESULT="$result"
    else
        echo "test_function_1 failed"
        exit 1
    fi
}


test_function_2() {
  echo "test function 2 called"
}


setup(){
    output_file=$(mktemp)

    eval "$(declare -f test_function_1 | perl -0777 -pe 's/test_function_1/original_test_function_1/' )"

  # shellcheck disable=SC2317
  test_function_1() {
    set +e
    original_test_function_1 "$@" > "$output_file" && exit_code=0 || exit_code=$?
    set -e

    output="$(cat "$output_file")"
    echo "exit code : $exit_code"
    echo "output : $output"
  }

  # shellcheck disable=SC2317
  test_function_2() {
    echo "test function 2 called"
    if [[ "$MAKE_IT_FAIL" == "true" ]]; then
      exit 1
    fi
  }

}

teardown() {
  # Delete the temp file
  rm "$output_file"
}

@test "Successfully test_function_1" {
  test_function_1

  [ "$exit_code" -eq 0 ]
  [ "$output" = "test_function_1 passed" ]
  [ "$TEST_FUNCTION_1_RESULT" = "test function 2 called" ]

}

@test "failed test_function_1" {
  MAKE_IT_FAIL=true
  test_function_1

  [ "$exit_code" -eq 1 ]
  [ "$output" = "test_function_1 failed" ]
  [ -z "$TEST_FUNCTION_1_RESULT" ]

}
```
**Expected behavior**
Expected both test to pass but this is the result I have : 
```
bats test_file.sh
test_file.sh
 ✓ Successfully test_function_1
 ✗ failed test_function_1
   (from function `original_test_function_1' in file test_file.sh, line 31,
    from function `test_function_1' in file test_file.sh, line 29,
    in test file test_file.sh, line 63)
     `test_function_1' failed
```
2 tests, 1 failure

**Environment :**
 - Bats version Bats 1.11.0
 - operating system (including version): macOS 14.5
 - `bash --version`: 5.2.15(1)-release

**Comment by martin-schulze-vireso** [comment]
I think `set +e` is totally irrelevant when using `exit 1` in original_test_function_1. Does the problem persist when using `return 1` instead?

**Comment by nouaman** [comment]
Yes it work with return, I was hoping it would work like run but I suppose run execute it in a subshell.
thank you for your answer
