### ISSUE TITLE
Add bash to bats Dockerfile.

### ISSUE THREAD

**Issue by pauldruce** [bats-core/bats-core#958]
**Is your feature request related to a problem? Please describe.**
I think a good majority of people are testing against bash scripts and the current dockerfile doesn't have it installed.
You get weird/cryptic error messages from bats when you try to execute a bash script in the dockerfile. 
I.e. `cannot execute: required file not found`

Yes you can create your own image and use that - but it would be nice to just have bash installed in the docker image.

**Describe the solution you'd like**
Add bash support into the Dockerfile

**Describe alternatives you've considered**
Have a specific docker image for bash and another for just sh - could be managed by tags or something. 
bat/bats:latest and bat/bats:sh-latest - sh only
bat/bats:bash-latest - bash image.

**Comment by pauldruce** [comment]
I.e. if you run: `docker run -it --entrypoint /bin/sh bats/bats:latest` you will get an interactive shell. But if you run:

`docker run -it --entrypoint /bin/bash bats/bats:latest` you will get the following error:

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:377: starting container process caused: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown.
ERRO[0000] error waiting for container: context canceled 
```

**Comment by martin-schulze-vireso** [comment]
I think `/usr/bin/env bash` is recommended outside of Docker as well, since different distros use different paths.

**Comment by brokenpip3** [comment]
> I think `/usr/bin/env bash` is recommended outside of Docker as well, since different distros use different paths.

:100: 
like nix for instance

**Comment by pauldruce** [comment]
So a quick search of GitHub shows that 8 million files use #!/bin/bash - and as it stands those files can't be tested using the bats docker image. 

Whereas 2 million have "#!/usr/bin/env bash". 

I guess my point is, this tool is less useful than it could be. And I don't see a reason to not also symlink bash to /bin. 
I don't think it would break the "/usr/bin/env bash" users, and it would make the bats docker image usable without any extra faff for a lot more use cases.
