### ISSUE TITLE
libexec/bats-core/bats-gather-tests should use $BATS_LIBDIR not /lib

### ISSUE THREAD

**Issue by pscn** [bats-core/bats-core#982]
**Describe the bug**
bats-gather-tests has a hard coded reference to lib and does not use $BATS_LIB when sourcing common.bash and others.

```
$ bats .
/usr/libexec/bats-core/bats-gather-tests: line 10: /usr/lib/bats-core/common.bash: No such file or directory
```

**To Reproduce**

1. Install bats-core to lib64
2. run `bats .` in a directory containing multiple bats files

**Expected behavior**
bats should run all tests

**Environment (please complete the following information):**
 - Bats version [e.g. 1.4.0 or commit hash if applicable]:  master
 - operating system (including version): [e.g. Linux (please name your distribution!), FreeBSD, MacOS]: CentOS 7.9
 - `bash --version`: [e.g. 5.1] 4.2.46
 - Install method: [e.g. git submodule, distribution package manager, npm, homebrew, ...] bash install.sh /usr lib64

Cheers,
  Peter

**Comment by martin-schulze-vireso** [comment]
Thank you for your report. Would you mind creating a PR for that?

**Comment by pscn** [comment]
Been a long time since I did anything on github.  Maybe like this #984
